// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/event/v1alpha1/event.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSeverity int32

const (
	EventSeverity_EVENT_SEVERITY_INFO  EventSeverity = 0
	EventSeverity_EVENT_SEVERITY_WARN  EventSeverity = 1
	EventSeverity_EVENT_SEVERITY_ERROR EventSeverity = 2
)

// Enum value maps for EventSeverity.
var (
	EventSeverity_name = map[int32]string{
		0: "EVENT_SEVERITY_INFO",
		1: "EVENT_SEVERITY_WARN",
		2: "EVENT_SEVERITY_ERROR",
	}
	EventSeverity_value = map[string]int32{
		"EVENT_SEVERITY_INFO":  0,
		"EVENT_SEVERITY_WARN":  1,
		"EVENT_SEVERITY_ERROR": 2,
	}
)

func (x EventSeverity) Enum() *EventSeverity {
	p := new(EventSeverity)
	*p = x
	return p
}

func (x EventSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_event_v1alpha1_event_proto_enumTypes[0].Descriptor()
}

func (EventSeverity) Type() protoreflect.EnumType {
	return &file_pkg_api_event_v1alpha1_event_proto_enumTypes[0]
}

func (x EventSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSeverity.Descriptor instead.
func (EventSeverity) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{0}
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{0}
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []string               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListEventRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Severity *EventSeverity         `protobuf:"varint,1,opt,name=severity,proto3,enum=event.v1alpha1.EventSeverity,oneof" json:"severity,omitempty"`
	Group    string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Maximum number of most recently reported events to return; 0 returns all.
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventRequest) Reset() {
	*x = ListEventRequest{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventRequest) ProtoMessage() {}

func (x *ListEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventRequest.ProtoReflect.Descriptor instead.
func (*ListEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventRequest) GetSeverity() EventSeverity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return EventSeverity_EVENT_SEVERITY_INFO
}

func (x *ListEventRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ListEventRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventResponse) Reset() {
	*x = ListEventResponse{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventResponse) ProtoMessage() {}

func (x *ListEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventResponse.ProtoReflect.Descriptor instead.
func (*ListEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type WatchEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      *EventSeverity         `protobuf:"varint,1,opt,name=severity,proto3,enum=event.v1alpha1.EventSeverity,oneof" json:"severity,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventRequest) Reset() {
	*x = WatchEventRequest{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventRequest) ProtoMessage() {}

func (x *WatchEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventRequest.ProtoReflect.Descriptor instead.
func (*WatchEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{4}
}

func (x *WatchEventRequest) GetSeverity() EventSeverity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return EventSeverity_EVENT_SEVERITY_INFO
}

func (x *WatchEventRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type WatchEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventResponse) Reset() {
	*x = WatchEventResponse{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventResponse) ProtoMessage() {}

func (x *WatchEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventResponse.ProtoReflect.Descriptor instead.
func (*WatchEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{5}
}

func (x *WatchEventResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      EventSeverity          `protobuf:"varint,1,opt,name=severity,proto3,enum=event.v1alpha1.EventSeverity" json:"severity,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Details       *EventDetails          `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	ObjectRefs    []*EventRef            `protobuf:"bytes,4,rep,name=object_refs,json=objectRefs,proto3" json:"object_refs,omitempty"`
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetSeverity() EventSeverity {
	if x != nil {
		return x.Severity
	}
	return EventSeverity_EVENT_SEVERITY_INFO
}

func (x *Event) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Event) GetDetails() *EventDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Event) GetObjectRefs() []*EventRef {
	if x != nil {
		return x.ObjectRefs
	}
	return nil
}

func (x *Event) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

type EventRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRef) Reset() {
	*x = EventRef{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRef) ProtoMessage() {}

func (x *EventRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRef.ProtoReflect.Descriptor instead.
func (*EventRef) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{7}
}

func (x *EventRef) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *EventRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type EventDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDetails) Reset() {
	*x = EventDetails{}
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetails) ProtoMessage() {}

func (x *EventDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_event_v1alpha1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDetails.ProtoReflect.Descriptor instead.
func (*EventDetails) Descriptor() ([]byte, []int) {
	return file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP(), []int{8}
}

func (x *EventDetails) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_api_event_v1alpha1_event_proto protoreflect.FileDescriptor

const file_pkg_api_event_v1alpha1_event_proto_rawDesc = "" +
	"\n" +
	"\"pkg/api/event/v1alpha1/event.proto\x12\x0eevent.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fGetGroupRequest\"*\n" +
	"\x10GetGroupResponse\x12\x16\n" +
	"\x06groups\x18\x01 \x03(\tR\x06groups\"\x8b\x01\n" +
	"\x10ListEventRequest\x12>\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x1d.event.v1alpha1.EventSeverityH\x00R\bseverity\x88\x01\x01\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\v\n" +
	"\t_severity\"B\n" +
	"\x11ListEventResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.event.v1alpha1.EventR\x06events\"v\n" +
	"\x11WatchEventRequest\x12>\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x1d.event.v1alpha1.EventSeverityH\x00R\bseverity\x88\x01\x01\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05groupB\v\n" +
	"\t_severity\"C\n" +
	"\x12WatchEventResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.event.v1alpha1.EventR\x06events\"\x88\x02\n" +
	"\x05Event\x129\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x1d.event.v1alpha1.EventSeverityR\bseverity\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x126\n" +
	"\adetails\x18\x03 \x01(\v2\x1c.event.v1alpha1.EventDetailsR\adetails\x129\n" +
	"\vobject_refs\x18\x04 \x03(\v2\x18.event.v1alpha1.EventRefR\n" +
	"objectRefs\x12;\n" +
	"\vreported_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\"7\n" +
	"\bEventRef\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"&\n" +
	"\fEventDetails\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*[\n" +
	"\rEventSeverity\x12\x17\n" +
	"\x13EVENT_SEVERITY_INFO\x10\x00\x12\x17\n" +
	"\x13EVENT_SEVERITY_WARN\x10\x01\x12\x18\n" +
	"\x14EVENT_SEVERITY_ERROR\x10\x022\xfd\x01\n" +
	"\fEventService\x12N\n" +
	"\tGetGroups\x12\x1f.event.v1alpha1.GetGroupRequest\x1a .event.v1alpha1.GetGroupResponse\x12K\n" +
	"\x04List\x12 .event.v1alpha1.ListEventRequest\x1a!.event.v1alpha1.ListEventResponse\x12P\n" +
	"\x05Watch\x12!.event.v1alpha1.WatchEventRequest\x1a\".event.v1alpha1.WatchEventResponse0\x01B7Z5github.com/otelfleet/otelfleet/pkg/api/event/v1alpha1b\x06proto3"

var (
	file_pkg_api_event_v1alpha1_event_proto_rawDescOnce sync.Once
	file_pkg_api_event_v1alpha1_event_proto_rawDescData []byte
)

func file_pkg_api_event_v1alpha1_event_proto_rawDescGZIP() []byte {
	file_pkg_api_event_v1alpha1_event_proto_rawDescOnce.Do(func() {
		file_pkg_api_event_v1alpha1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_event_v1alpha1_event_proto_rawDesc), len(file_pkg_api_event_v1alpha1_event_proto_rawDesc)))
	})
	return file_pkg_api_event_v1alpha1_event_proto_rawDescData
}

var file_pkg_api_event_v1alpha1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_event_v1alpha1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_event_v1alpha1_event_proto_goTypes = []any{
	(EventSeverity)(0),            // 0: event.v1alpha1.EventSeverity
	(*GetGroupRequest)(nil),       // 1: event.v1alpha1.GetGroupRequest
	(*GetGroupResponse)(nil),      // 2: event.v1alpha1.GetGroupResponse
	(*ListEventRequest)(nil),      // 3: event.v1alpha1.ListEventRequest
	(*ListEventResponse)(nil),     // 4: event.v1alpha1.ListEventResponse
	(*WatchEventRequest)(nil),     // 5: event.v1alpha1.WatchEventRequest
	(*WatchEventResponse)(nil),    // 6: event.v1alpha1.WatchEventResponse
	(*Event)(nil),                 // 7: event.v1alpha1.Event
	(*EventRef)(nil),              // 8: event.v1alpha1.EventRef
	(*EventDetails)(nil),          // 9: event.v1alpha1.EventDetails
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_pkg_api_event_v1alpha1_event_proto_depIdxs = []int32{
	0,  // 0: event.v1alpha1.ListEventRequest.severity:type_name -> event.v1alpha1.EventSeverity
	7,  // 1: event.v1alpha1.ListEventResponse.events:type_name -> event.v1alpha1.Event
	0,  // 2: event.v1alpha1.WatchEventRequest.severity:type_name -> event.v1alpha1.EventSeverity
	7,  // 3: event.v1alpha1.WatchEventResponse.events:type_name -> event.v1alpha1.Event
	0,  // 4: event.v1alpha1.Event.severity:type_name -> event.v1alpha1.EventSeverity
	9,  // 5: event.v1alpha1.Event.details:type_name -> event.v1alpha1.EventDetails
	8,  // 6: event.v1alpha1.Event.object_refs:type_name -> event.v1alpha1.EventRef
	10, // 7: event.v1alpha1.Event.reported_at:type_name -> google.protobuf.Timestamp
	1,  // 8: event.v1alpha1.EventService.GetGroups:input_type -> event.v1alpha1.GetGroupRequest
	3,  // 9: event.v1alpha1.EventService.List:input_type -> event.v1alpha1.ListEventRequest
	5,  // 10: event.v1alpha1.EventService.Watch:input_type -> event.v1alpha1.WatchEventRequest
	2,  // 11: event.v1alpha1.EventService.GetGroups:output_type -> event.v1alpha1.GetGroupResponse
	4,  // 12: event.v1alpha1.EventService.List:output_type -> event.v1alpha1.ListEventResponse
	6,  // 13: event.v1alpha1.EventService.Watch:output_type -> event.v1alpha1.WatchEventResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_api_event_v1alpha1_event_proto_init() }
func file_pkg_api_event_v1alpha1_event_proto_init() {
	if File_pkg_api_event_v1alpha1_event_proto != nil {
		return
	}
	file_pkg_api_event_v1alpha1_event_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_api_event_v1alpha1_event_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_event_v1alpha1_event_proto_rawDesc), len(file_pkg_api_event_v1alpha1_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_event_v1alpha1_event_proto_goTypes,
		DependencyIndexes: file_pkg_api_event_v1alpha1_event_proto_depIdxs,
		EnumInfos:         file_pkg_api_event_v1alpha1_event_proto_enumTypes,
		MessageInfos:      file_pkg_api_event_v1alpha1_event_proto_msgTypes,
	}.Build()
	File_pkg_api_event_v1alpha1_event_proto = out.File
	file_pkg_api_event_v1alpha1_event_proto_goTypes = nil
	file_pkg_api_event_v1alpha1_event_proto_depIdxs = nil
}
