// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/config/v1alpha1/config.proto

package v1alpha1

import (
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/resources/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignedState int32

const (
	AssignedState_ASSIGNED_STATE_UNKNOWN     AssignedState = 0
	AssignedState_ASSIGNED_STATE_PENDING     AssignedState = 1
	AssignedState_ASSIGNED_STATE_PLANNED     AssignedState = 2
	AssignedState_ASSIGNED_STATE_APPLIED     AssignedState = 3
	AssignedState_ASSIGNED_STATE_NOT_APPLIED AssignedState = 4
)

// Enum value maps for AssignedState.
var (
	AssignedState_name = map[int32]string{
		0: "ASSIGNED_STATE_UNKNOWN",
		1: "ASSIGNED_STATE_PENDING",
		2: "ASSIGNED_STATE_PLANNED",
		3: "ASSIGNED_STATE_APPLIED",
		4: "ASSIGNED_STATE_NOT_APPLIED",
	}
	AssignedState_value = map[string]int32{
		"ASSIGNED_STATE_UNKNOWN":     0,
		"ASSIGNED_STATE_PENDING":     1,
		"ASSIGNED_STATE_PLANNED":     2,
		"ASSIGNED_STATE_APPLIED":     3,
		"ASSIGNED_STATE_NOT_APPLIED": 4,
	}
)

func (x AssignedState) Enum() *AssignedState {
	p := new(AssignedState)
	*p = x
	return p
}

func (x AssignedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignedState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_config_v1alpha1_config_proto_enumTypes[0].Descriptor()
}

func (AssignedState) Type() protoreflect.EnumType {
	return &file_pkg_api_config_v1alpha1_config_proto_enumTypes[0]
}

func (x AssignedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignedState.Descriptor instead.
func (AssignedState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_config_v1alpha1_config_proto_rawDescGZIP(), []int{0}
}

type AssignedConfig struct {
	state      protoimpl.MessageState    `protogen:"open.v1"`
	Config     *v1alpha1.CollectorConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ApplyState AssignedState             `protobuf:"varint,2,opt,name=apply_state,json=applyState,proto3,enum=config.v1alpha1.AssignedState" json:"apply_state,omitempty"`
	// details on failures
	Details       string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedConfig) Reset() {
	*x = AssignedConfig{}
	mi := &file_pkg_api_config_v1alpha1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedConfig) ProtoMessage() {}

func (x *AssignedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_config_v1alpha1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedConfig.ProtoReflect.Descriptor instead.
func (*AssignedConfig) Descriptor() ([]byte, []int) {
	return file_pkg_api_config_v1alpha1_config_proto_rawDescGZIP(), []int{0}
}

func (x *AssignedConfig) GetConfig() *v1alpha1.CollectorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AssignedConfig) GetApplyState() AssignedState {
	if x != nil {
		return x.ApplyState
	}
	return AssignedState_ASSIGNED_STATE_UNKNOWN
}

func (x *AssignedConfig) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_pkg_api_config_v1alpha1_config_proto protoreflect.FileDescriptor

const file_pkg_api_config_v1alpha1_config_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/config/v1alpha1/config.proto\x12\x0fconfig.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*pkg/api/resources/v1alpha1/resources.proto\"\xa8\x01\n" +
	"\x0eAssignedConfig\x12;\n" +
	"\x06config\x18\x01 \x01(\v2#.resources.v1alpha1.CollectorConfigR\x06config\x12?\n" +
	"\vapply_state\x18\x02 \x01(\x0e2\x1e.config.v1alpha1.AssignedStateR\n" +
	"applyState\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails*\x9f\x01\n" +
	"\rAssignedState\x12\x1a\n" +
	"\x16ASSIGNED_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16ASSIGNED_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16ASSIGNED_STATE_PLANNED\x10\x02\x12\x1a\n" +
	"\x16ASSIGNED_STATE_APPLIED\x10\x03\x12\x1e\n" +
	"\x1aASSIGNED_STATE_NOT_APPLIED\x10\x04B8Z6github.com/otelfleet/otelfleet/pkg/api/config/v1alpha1b\x06proto3"

var (
	file_pkg_api_config_v1alpha1_config_proto_rawDescOnce sync.Once
	file_pkg_api_config_v1alpha1_config_proto_rawDescData []byte
)

func file_pkg_api_config_v1alpha1_config_proto_rawDescGZIP() []byte {
	file_pkg_api_config_v1alpha1_config_proto_rawDescOnce.Do(func() {
		file_pkg_api_config_v1alpha1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_config_v1alpha1_config_proto_rawDesc), len(file_pkg_api_config_v1alpha1_config_proto_rawDesc)))
	})
	return file_pkg_api_config_v1alpha1_config_proto_rawDescData
}

var file_pkg_api_config_v1alpha1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_config_v1alpha1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_api_config_v1alpha1_config_proto_goTypes = []any{
	(AssignedState)(0),               // 0: config.v1alpha1.AssignedState
	(*AssignedConfig)(nil),           // 1: config.v1alpha1.AssignedConfig
	(*v1alpha1.CollectorConfig)(nil), // 2: resources.v1alpha1.CollectorConfig
}
var file_pkg_api_config_v1alpha1_config_proto_depIdxs = []int32{
	2, // 0: config.v1alpha1.AssignedConfig.config:type_name -> resources.v1alpha1.CollectorConfig
	0, // 1: config.v1alpha1.AssignedConfig.apply_state:type_name -> config.v1alpha1.AssignedState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_config_v1alpha1_config_proto_init() }
func file_pkg_api_config_v1alpha1_config_proto_init() {
	if File_pkg_api_config_v1alpha1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_config_v1alpha1_config_proto_rawDesc), len(file_pkg_api_config_v1alpha1_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_config_v1alpha1_config_proto_goTypes,
		DependencyIndexes: file_pkg_api_config_v1alpha1_config_proto_depIdxs,
		EnumInfos:         file_pkg_api_config_v1alpha1_config_proto_enumTypes,
		MessageInfos:      file_pkg_api_config_v1alpha1_config_proto_msgTypes,
	}.Build()
	File_pkg_api_config_v1alpha1_config_proto = out.File
	file_pkg_api_config_v1alpha1_config_proto_goTypes = nil
	file_pkg_api_config_v1alpha1_config_proto_depIdxs = nil
}
