syntax = "proto3";
package config.v1alpha1;

// import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "pkg/api/resources/v1alpha1/resources.proto";

option go_package = "github.com/otelfleet/otelfleet/pkg/api/config/v1alpha1";

message AssignedConfig {
  resources.v1alpha1.CollectorConfig config = 1;
  AssignedState apply_state = 2;
  // details on failures
  string details = 3;
}

enum AssignedState {
  ASSIGNED_STATE_UNKNOWN = 0;
  ASSIGNED_STATE_PENDING = 1;
  ASSIGNED_STATE_PLANNED = 2;
  ASSIGNED_STATE_APPLIED = 3;
  ASSIGNED_STATE_NOT_APPLIED = 4;
}