/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as ConfigfilterRouteImport } from './routes/configfilter'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensTokenIdRouteImport } from './routes/tokens.$tokenId'
import { Route as ResourcesTypeRouteImport } from './routes/resources.$type'
import { Route as DeploymentsAgentIdRouteImport } from './routes/deployments.$agentId'
import { Route as ConfigfilterEditorRouteImport } from './routes/configfilter_.editor'
import { Route as ResourcesTypeEditorRouteImport } from './routes/resources.$type_.editor'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigfilterRoute = ConfigfilterRouteImport.update({
  id: '/configfilter',
  path: '/configfilter',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTokenIdRoute = TokensTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => TokensRoute,
} as any)
const ResourcesTypeRoute = ResourcesTypeRouteImport.update({
  id: '/resources/$type',
  path: '/resources/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsAgentIdRoute = DeploymentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => DeploymentsRoute,
} as any)
const ConfigfilterEditorRoute = ConfigfilterEditorRouteImport.update({
  id: '/configfilter_/editor',
  path: '/configfilter/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTypeEditorRoute = ResourcesTypeEditorRouteImport.update({
  id: '/resources/$type_/editor',
  path: '/resources/$type/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configfilter': typeof ConfigfilterRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/tokens': typeof TokensRouteWithChildren
  '/configfilter/editor': typeof ConfigfilterEditorRoute
  '/deployments/$agentId': typeof DeploymentsAgentIdRoute
  '/resources/$type': typeof ResourcesTypeRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/resources/$type/editor': typeof ResourcesTypeEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configfilter': typeof ConfigfilterRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/tokens': typeof TokensRouteWithChildren
  '/configfilter/editor': typeof ConfigfilterEditorRoute
  '/deployments/$agentId': typeof DeploymentsAgentIdRoute
  '/resources/$type': typeof ResourcesTypeRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/resources/$type/editor': typeof ResourcesTypeEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configfilter': typeof ConfigfilterRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/tokens': typeof TokensRouteWithChildren
  '/configfilter_/editor': typeof ConfigfilterEditorRoute
  '/deployments/$agentId': typeof DeploymentsAgentIdRoute
  '/resources/$type': typeof ResourcesTypeRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/resources/$type_/editor': typeof ResourcesTypeEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/configfilter'
    | '/deployments'
    | '/tokens'
    | '/configfilter/editor'
    | '/deployments/$agentId'
    | '/resources/$type'
    | '/tokens/$tokenId'
    | '/resources/$type/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/configfilter'
    | '/deployments'
    | '/tokens'
    | '/configfilter/editor'
    | '/deployments/$agentId'
    | '/resources/$type'
    | '/tokens/$tokenId'
    | '/resources/$type/editor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/configfilter'
    | '/deployments'
    | '/tokens'
    | '/configfilter_/editor'
    | '/deployments/$agentId'
    | '/resources/$type'
    | '/tokens/$tokenId'
    | '/resources/$type_/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfigfilterRoute: typeof ConfigfilterRoute
  DeploymentsRoute: typeof DeploymentsRouteWithChildren
  TokensRoute: typeof TokensRouteWithChildren
  ConfigfilterEditorRoute: typeof ConfigfilterEditorRoute
  ResourcesTypeRoute: typeof ResourcesTypeRoute
  ResourcesTypeEditorRoute: typeof ResourcesTypeEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configfilter': {
      id: '/configfilter'
      path: '/configfilter'
      fullPath: '/configfilter'
      preLoaderRoute: typeof ConfigfilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$tokenId': {
      id: '/tokens/$tokenId'
      path: '/$tokenId'
      fullPath: '/tokens/$tokenId'
      preLoaderRoute: typeof TokensTokenIdRouteImport
      parentRoute: typeof TokensRoute
    }
    '/resources/$type': {
      id: '/resources/$type'
      path: '/resources/$type'
      fullPath: '/resources/$type'
      preLoaderRoute: typeof ResourcesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$agentId': {
      id: '/deployments/$agentId'
      path: '/$agentId'
      fullPath: '/deployments/$agentId'
      preLoaderRoute: typeof DeploymentsAgentIdRouteImport
      parentRoute: typeof DeploymentsRoute
    }
    '/configfilter_/editor': {
      id: '/configfilter_/editor'
      path: '/configfilter/editor'
      fullPath: '/configfilter/editor'
      preLoaderRoute: typeof ConfigfilterEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$type_/editor': {
      id: '/resources/$type_/editor'
      path: '/resources/$type/editor'
      fullPath: '/resources/$type/editor'
      preLoaderRoute: typeof ResourcesTypeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeploymentsRouteChildren {
  DeploymentsAgentIdRoute: typeof DeploymentsAgentIdRoute
}

const DeploymentsRouteChildren: DeploymentsRouteChildren = {
  DeploymentsAgentIdRoute: DeploymentsAgentIdRoute,
}

const DeploymentsRouteWithChildren = DeploymentsRoute._addFileChildren(
  DeploymentsRouteChildren,
)

interface TokensRouteChildren {
  TokensTokenIdRoute: typeof TokensTokenIdRoute
}

const TokensRouteChildren: TokensRouteChildren = {
  TokensTokenIdRoute: TokensTokenIdRoute,
}

const TokensRouteWithChildren =
  TokensRoute._addFileChildren(TokensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfigfilterRoute: ConfigfilterRoute,
  DeploymentsRoute: DeploymentsRouteWithChildren,
  TokensRoute: TokensRouteWithChildren,
  ConfigfilterEditorRoute: ConfigfilterEditorRoute,
  ResourcesTypeRoute: ResourcesTypeRoute,
  ResourcesTypeEditorRoute: ResourcesTypeEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
