// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/common/v1alpha1/common.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchType int32

const (
	MatchType_MATCH_TYPE_EQ  MatchType = 0
	MatchType_MATCH_TYPE_NEQ MatchType = 1
	MatchType_MATCH_TYPE_RE  MatchType = 2
	MatchType_MATCH_TYPE_NRE MatchType = 3
)

// Enum value maps for MatchType.
var (
	MatchType_name = map[int32]string{
		0: "MATCH_TYPE_EQ",
		1: "MATCH_TYPE_NEQ",
		2: "MATCH_TYPE_RE",
		3: "MATCH_TYPE_NRE",
	}
	MatchType_value = map[string]int32{
		"MATCH_TYPE_EQ":  0,
		"MATCH_TYPE_NEQ": 1,
		"MATCH_TYPE_RE":  2,
		"MATCH_TYPE_NRE": 3,
	}
)

func (x MatchType) Enum() *MatchType {
	p := new(MatchType)
	*p = x
	return p
}

func (x MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_common_v1alpha1_common_proto_enumTypes[0].Descriptor()
}

func (MatchType) Type() protoreflect.EnumType {
	return &file_pkg_api_common_v1alpha1_common_proto_enumTypes[0]
}

func (x MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchType.Descriptor instead.
func (MatchType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

type LabelType int32

const (
	// For user configured labels on a collector instance
	LabelType_LabelTypeOtelfleet LabelType = 0
	// For runtime information reported by the opamp supervisor,
	// related to the collector distribution
	LabelType_LabelTypeIdentifying LabelType = 1
	// For runtime information reported by the opamp supervisor,
	// related to the host information or other
	LabelType_LabelTypeNonIdentifying LabelType = 2
)

// Enum value maps for LabelType.
var (
	LabelType_name = map[int32]string{
		0: "LabelTypeOtelfleet",
		1: "LabelTypeIdentifying",
		2: "LabelTypeNonIdentifying",
	}
	LabelType_value = map[string]int32{
		"LabelTypeOtelfleet":      0,
		"LabelTypeIdentifying":    1,
		"LabelTypeNonIdentifying": 2,
	}
)

func (x LabelType) Enum() *LabelType {
	p := new(LabelType)
	*p = x
	return p
}

func (x LabelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_common_v1alpha1_common_proto_enumTypes[1].Descriptor()
}

func (LabelType) Type() protoreflect.EnumType {
	return &file_pkg_api_common_v1alpha1_common_proto_enumTypes[1]
}

func (x LabelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelType.Descriptor instead.
func (LabelType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

type VersionOrdering int32

const (
	VersionOrdering_VERSION_ORDERING_SEMVER VersionOrdering = 0
)

// Enum value maps for VersionOrdering.
var (
	VersionOrdering_name = map[int32]string{
		0: "VERSION_ORDERING_SEMVER",
	}
	VersionOrdering_value = map[string]int32{
		"VERSION_ORDERING_SEMVER": 0,
	}
)

func (x VersionOrdering) Enum() *VersionOrdering {
	p := new(VersionOrdering)
	*p = x
	return p
}

func (x VersionOrdering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionOrdering) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_common_v1alpha1_common_proto_enumTypes[2].Descriptor()
}

func (VersionOrdering) Type() protoreflect.EnumType {
	return &file_pkg_api_common_v1alpha1_common_proto_enumTypes[2]
}

func (x VersionOrdering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionOrdering.Descriptor instead.
func (VersionOrdering) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{2}
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LabelFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LabelType              `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1alpha1.LabelType" json:"type,omitempty"`
	Filters       []*KeyPairFilter       `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelFilter) Reset() {
	*x = LabelFilter{}
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelFilter) ProtoMessage() {}

func (x *LabelFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelFilter.ProtoReflect.Descriptor instead.
func (*LabelFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

func (x *LabelFilter) GetType() LabelType {
	if x != nil {
		return x.Type
	}
	return LabelType_LabelTypeOtelfleet
}

func (x *LabelFilter) GetFilters() []*KeyPairFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type KeyPairFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchType     MatchType              `protobuf:"varint,1,opt,name=match_type,json=matchType,proto3,enum=common.v1alpha1.MatchType" json:"match_type,omitempty"`
	Label         *Label                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPairFilter) Reset() {
	*x = KeyPairFilter{}
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPairFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPairFilter) ProtoMessage() {}

func (x *KeyPairFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPairFilter.ProtoReflect.Descriptor instead.
func (*KeyPairFilter) Descriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPairFilter) GetMatchType() MatchType {
	if x != nil {
		return x.MatchType
	}
	return MatchType_MATCH_TYPE_EQ
}

func (x *KeyPairFilter) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

type CompatibilityMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constraints   []*VersionConstraits   `protobuf:"bytes,1,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompatibilityMatrix) Reset() {
	*x = CompatibilityMatrix{}
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityMatrix) ProtoMessage() {}

func (x *CompatibilityMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityMatrix.ProtoReflect.Descriptor instead.
func (*CompatibilityMatrix) Descriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{3}
}

func (x *CompatibilityMatrix) GetConstraints() []*VersionConstraits {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type VersionConstraits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ordering      VersionOrdering        `protobuf:"varint,1,opt,name=ordering,proto3,enum=common.v1alpha1.VersionOrdering" json:"ordering,omitempty"`
	Distribution  string                 `protobuf:"bytes,2,opt,name=distribution,proto3" json:"distribution,omitempty"`
	MinVersion    *string                `protobuf:"bytes,3,opt,name=min_version,json=minVersion,proto3,oneof" json:"min_version,omitempty"`
	MaxVersion    *string                `protobuf:"bytes,4,opt,name=max_version,json=maxVersion,proto3,oneof" json:"max_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionConstraits) Reset() {
	*x = VersionConstraits{}
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionConstraits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionConstraits) ProtoMessage() {}

func (x *VersionConstraits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionConstraits.ProtoReflect.Descriptor instead.
func (*VersionConstraits) Descriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{4}
}

func (x *VersionConstraits) GetOrdering() VersionOrdering {
	if x != nil {
		return x.Ordering
	}
	return VersionOrdering_VERSION_ORDERING_SEMVER
}

func (x *VersionConstraits) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

func (x *VersionConstraits) GetMinVersion() string {
	if x != nil && x.MinVersion != nil {
		return *x.MinVersion
	}
	return ""
}

func (x *VersionConstraits) GetMaxVersion() string {
	if x != nil && x.MaxVersion != nil {
		return *x.MaxVersion
	}
	return ""
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_common_v1alpha1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP(), []int{5}
}

func (x *Reference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Reference) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_pkg_api_common_v1alpha1_common_proto protoreflect.FileDescriptor

const file_pkg_api_common_v1alpha1_common_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/common/v1alpha1/common.proto\x12\x0fcommon.v1alpha1\"/\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"w\n" +
	"\vLabelFilter\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.common.v1alpha1.LabelTypeR\x04type\x128\n" +
	"\afilters\x18\x02 \x03(\v2\x1e.common.v1alpha1.KeyPairFilterR\afilters\"x\n" +
	"\rKeyPairFilter\x129\n" +
	"\n" +
	"match_type\x18\x01 \x01(\x0e2\x1a.common.v1alpha1.MatchTypeR\tmatchType\x12,\n" +
	"\x05label\x18\x02 \x01(\v2\x16.common.v1alpha1.LabelR\x05label\"[\n" +
	"\x13CompatibilityMatrix\x12D\n" +
	"\vconstraints\x18\x01 \x03(\v2\".common.v1alpha1.VersionConstraitsR\vconstraints\"\xe1\x01\n" +
	"\x11VersionConstraits\x12<\n" +
	"\bordering\x18\x01 \x01(\x0e2 .common.v1alpha1.VersionOrderingR\bordering\x12\"\n" +
	"\fdistribution\x18\x02 \x01(\tR\fdistribution\x12$\n" +
	"\vmin_version\x18\x03 \x01(\tH\x00R\n" +
	"minVersion\x88\x01\x01\x12$\n" +
	"\vmax_version\x18\x04 \x01(\tH\x01R\n" +
	"maxVersion\x88\x01\x01B\x0e\n" +
	"\f_min_versionB\x0e\n" +
	"\f_max_version\"9\n" +
	"\tReference\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision*Y\n" +
	"\tMatchType\x12\x11\n" +
	"\rMATCH_TYPE_EQ\x10\x00\x12\x12\n" +
	"\x0eMATCH_TYPE_NEQ\x10\x01\x12\x11\n" +
	"\rMATCH_TYPE_RE\x10\x02\x12\x12\n" +
	"\x0eMATCH_TYPE_NRE\x10\x03*Z\n" +
	"\tLabelType\x12\x16\n" +
	"\x12LabelTypeOtelfleet\x10\x00\x12\x18\n" +
	"\x14LabelTypeIdentifying\x10\x01\x12\x1b\n" +
	"\x17LabelTypeNonIdentifying\x10\x02*.\n" +
	"\x0fVersionOrdering\x12\x1b\n" +
	"\x17VERSION_ORDERING_SEMVER\x10\x00B8Z6github.com/otelfleet/otelfleet/pkg/api/common/v1alpha1b\x06proto3"

var (
	file_pkg_api_common_v1alpha1_common_proto_rawDescOnce sync.Once
	file_pkg_api_common_v1alpha1_common_proto_rawDescData []byte
)

func file_pkg_api_common_v1alpha1_common_proto_rawDescGZIP() []byte {
	file_pkg_api_common_v1alpha1_common_proto_rawDescOnce.Do(func() {
		file_pkg_api_common_v1alpha1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_common_v1alpha1_common_proto_rawDesc), len(file_pkg_api_common_v1alpha1_common_proto_rawDesc)))
	})
	return file_pkg_api_common_v1alpha1_common_proto_rawDescData
}

var file_pkg_api_common_v1alpha1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_api_common_v1alpha1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_api_common_v1alpha1_common_proto_goTypes = []any{
	(MatchType)(0),              // 0: common.v1alpha1.MatchType
	(LabelType)(0),              // 1: common.v1alpha1.LabelType
	(VersionOrdering)(0),        // 2: common.v1alpha1.VersionOrdering
	(*Label)(nil),               // 3: common.v1alpha1.Label
	(*LabelFilter)(nil),         // 4: common.v1alpha1.LabelFilter
	(*KeyPairFilter)(nil),       // 5: common.v1alpha1.KeyPairFilter
	(*CompatibilityMatrix)(nil), // 6: common.v1alpha1.CompatibilityMatrix
	(*VersionConstraits)(nil),   // 7: common.v1alpha1.VersionConstraits
	(*Reference)(nil),           // 8: common.v1alpha1.Reference
}
var file_pkg_api_common_v1alpha1_common_proto_depIdxs = []int32{
	1, // 0: common.v1alpha1.LabelFilter.type:type_name -> common.v1alpha1.LabelType
	5, // 1: common.v1alpha1.LabelFilter.filters:type_name -> common.v1alpha1.KeyPairFilter
	0, // 2: common.v1alpha1.KeyPairFilter.match_type:type_name -> common.v1alpha1.MatchType
	3, // 3: common.v1alpha1.KeyPairFilter.label:type_name -> common.v1alpha1.Label
	7, // 4: common.v1alpha1.CompatibilityMatrix.constraints:type_name -> common.v1alpha1.VersionConstraits
	2, // 5: common.v1alpha1.VersionConstraits.ordering:type_name -> common.v1alpha1.VersionOrdering
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_api_common_v1alpha1_common_proto_init() }
func file_pkg_api_common_v1alpha1_common_proto_init() {
	if File_pkg_api_common_v1alpha1_common_proto != nil {
		return
	}
	file_pkg_api_common_v1alpha1_common_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_common_v1alpha1_common_proto_rawDesc), len(file_pkg_api_common_v1alpha1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_common_v1alpha1_common_proto_goTypes,
		DependencyIndexes: file_pkg_api_common_v1alpha1_common_proto_depIdxs,
		EnumInfos:         file_pkg_api_common_v1alpha1_common_proto_enumTypes,
		MessageInfos:      file_pkg_api_common_v1alpha1_common_proto_msgTypes,
	}.Build()
	File_pkg_api_common_v1alpha1_common_proto = out.File
	file_pkg_api_common_v1alpha1_common_proto_goTypes = nil
	file_pkg_api_common_v1alpha1_common_proto_depIdxs = nil
}
