// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/api/event/v1alpha1/event.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/event/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "event.v1alpha1.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServiceGetGroupsProcedure is the fully-qualified name of the EventService's GetGroups RPC.
	EventServiceGetGroupsProcedure = "/event.v1alpha1.EventService/GetGroups"
	// EventServiceListProcedure is the fully-qualified name of the EventService's List RPC.
	EventServiceListProcedure = "/event.v1alpha1.EventService/List"
	// EventServiceWatchProcedure is the fully-qualified name of the EventService's Watch RPC.
	EventServiceWatchProcedure = "/event.v1alpha1.EventService/Watch"
)

// EventServiceClient is a client for the event.v1alpha1.EventService service.
type EventServiceClient interface {
	GetGroups(context.Context, *connect.Request[v1alpha1.GetGroupRequest]) (*connect.Response[v1alpha1.GetGroupResponse], error)
	List(context.Context, *connect.Request[v1alpha1.ListEventRequest]) (*connect.Response[v1alpha1.ListEventResponse], error)
	Watch(context.Context, *connect.Request[v1alpha1.WatchEventRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchEventResponse], error)
}

// NewEventServiceClient constructs a client for the event.v1alpha1.EventService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := v1alpha1.File_pkg_api_event_v1alpha1_event_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		getGroups: connect.NewClient[v1alpha1.GetGroupRequest, v1alpha1.GetGroupResponse](
			httpClient,
			baseURL+EventServiceGetGroupsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("GetGroups")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1alpha1.ListEventRequest, v1alpha1.ListEventResponse](
			httpClient,
			baseURL+EventServiceListProcedure,
			connect.WithSchema(eventServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1alpha1.WatchEventRequest, v1alpha1.WatchEventResponse](
			httpClient,
			baseURL+EventServiceWatchProcedure,
			connect.WithSchema(eventServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	getGroups *connect.Client[v1alpha1.GetGroupRequest, v1alpha1.GetGroupResponse]
	list      *connect.Client[v1alpha1.ListEventRequest, v1alpha1.ListEventResponse]
	watch     *connect.Client[v1alpha1.WatchEventRequest, v1alpha1.WatchEventResponse]
}

// GetGroups calls event.v1alpha1.EventService.GetGroups.
func (c *eventServiceClient) GetGroups(ctx context.Context, req *connect.Request[v1alpha1.GetGroupRequest]) (*connect.Response[v1alpha1.GetGroupResponse], error) {
	return c.getGroups.CallUnary(ctx, req)
}

// List calls event.v1alpha1.EventService.List.
func (c *eventServiceClient) List(ctx context.Context, req *connect.Request[v1alpha1.ListEventRequest]) (*connect.Response[v1alpha1.ListEventResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls event.v1alpha1.EventService.Watch.
func (c *eventServiceClient) Watch(ctx context.Context, req *connect.Request[v1alpha1.WatchEventRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchEventResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// EventServiceHandler is an implementation of the event.v1alpha1.EventService service.
type EventServiceHandler interface {
	GetGroups(context.Context, *connect.Request[v1alpha1.GetGroupRequest]) (*connect.Response[v1alpha1.GetGroupResponse], error)
	List(context.Context, *connect.Request[v1alpha1.ListEventRequest]) (*connect.Response[v1alpha1.ListEventResponse], error)
	Watch(context.Context, *connect.Request[v1alpha1.WatchEventRequest], *connect.ServerStream[v1alpha1.WatchEventResponse]) error
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := v1alpha1.File_pkg_api_event_v1alpha1_event_proto.Services().ByName("EventService").Methods()
	eventServiceGetGroupsHandler := connect.NewUnaryHandler(
		EventServiceGetGroupsProcedure,
		svc.GetGroups,
		connect.WithSchema(eventServiceMethods.ByName("GetGroups")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListHandler := connect.NewUnaryHandler(
		EventServiceListProcedure,
		svc.List,
		connect.WithSchema(eventServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceWatchHandler := connect.NewServerStreamHandler(
		EventServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(eventServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/event.v1alpha1.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServiceGetGroupsProcedure:
			eventServiceGetGroupsHandler.ServeHTTP(w, r)
		case EventServiceListProcedure:
			eventServiceListHandler.ServeHTTP(w, r)
		case EventServiceWatchProcedure:
			eventServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) GetGroups(context.Context, *connect.Request[v1alpha1.GetGroupRequest]) (*connect.Response[v1alpha1.GetGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1alpha1.EventService.GetGroups is not implemented"))
}

func (UnimplementedEventServiceHandler) List(context.Context, *connect.Request[v1alpha1.ListEventRequest]) (*connect.Response[v1alpha1.ListEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1alpha1.EventService.List is not implemented"))
}

func (UnimplementedEventServiceHandler) Watch(context.Context, *connect.Request[v1alpha1.WatchEventRequest], *connect.ServerStream[v1alpha1.WatchEventResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("event.v1alpha1.EventService.Watch is not implemented"))
}
