// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/event/v1alpha1/event.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterEventServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterEventServiceHandler(mux *mux.Router, svc EventServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/event.v1alpha1.EventService/GetGroups", connect.NewUnaryHandler(
		"/event.v1alpha1.EventService/GetGroups",
		svc.GetGroups,
		opts...,
	))
	mux.Handle("/event.v1alpha1.EventService/List", connect.NewUnaryHandler(
		"/event.v1alpha1.EventService/List",
		svc.List,
		opts...,
	))
	mux.Handle("/event.v1alpha1.EventService/Watch", connect.NewServerStreamHandler(
		"/event.v1alpha1.EventService/Watch",
		svc.Watch,
		opts...,
	))
}
