// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/api/agents/v1alpha1/agents.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/agents/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "config.v1alpha1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceListAgentsProcedure is the fully-qualified name of the AgentService's ListAgents RPC.
	AgentServiceListAgentsProcedure = "/config.v1alpha1.AgentService/ListAgents"
	// AgentServiceGetAgentProcedure is the fully-qualified name of the AgentService's GetAgent RPC.
	AgentServiceGetAgentProcedure = "/config.v1alpha1.AgentService/GetAgent"
	// AgentServiceStatusProcedure is the fully-qualified name of the AgentService's Status RPC.
	AgentServiceStatusProcedure = "/config.v1alpha1.AgentService/Status"
)

// AgentServiceClient is a client for the config.v1alpha1.AgentService service.
type AgentServiceClient interface {
	ListAgents(context.Context, *connect.Request[v1alpha1.ListAgentsRequest]) (*connect.Response[v1alpha1.ListAgentsReponse], error)
	GetAgent(context.Context, *connect.Request[v1alpha1.GetAgentRequest]) (*connect.Response[v1alpha1.GetAgentResponse], error)
	Status(context.Context, *connect.Request[v1alpha1.GetAgentStatusRequest]) (*connect.Response[v1alpha1.AgentStatus], error)
}

// NewAgentServiceClient constructs a client for the config.v1alpha1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1alpha1.File_pkg_api_agents_v1alpha1_agents_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		listAgents: connect.NewClient[v1alpha1.ListAgentsRequest, v1alpha1.ListAgentsReponse](
			httpClient,
			baseURL+AgentServiceListAgentsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1alpha1.GetAgentRequest, v1alpha1.GetAgentResponse](
			httpClient,
			baseURL+AgentServiceGetAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[v1alpha1.GetAgentStatusRequest, v1alpha1.AgentStatus](
			httpClient,
			baseURL+AgentServiceStatusProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	listAgents *connect.Client[v1alpha1.ListAgentsRequest, v1alpha1.ListAgentsReponse]
	getAgent   *connect.Client[v1alpha1.GetAgentRequest, v1alpha1.GetAgentResponse]
	status     *connect.Client[v1alpha1.GetAgentStatusRequest, v1alpha1.AgentStatus]
}

// ListAgents calls config.v1alpha1.AgentService.ListAgents.
func (c *agentServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1alpha1.ListAgentsRequest]) (*connect.Response[v1alpha1.ListAgentsReponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// GetAgent calls config.v1alpha1.AgentService.GetAgent.
func (c *agentServiceClient) GetAgent(ctx context.Context, req *connect.Request[v1alpha1.GetAgentRequest]) (*connect.Response[v1alpha1.GetAgentResponse], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// Status calls config.v1alpha1.AgentService.Status.
func (c *agentServiceClient) Status(ctx context.Context, req *connect.Request[v1alpha1.GetAgentStatusRequest]) (*connect.Response[v1alpha1.AgentStatus], error) {
	return c.status.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the config.v1alpha1.AgentService service.
type AgentServiceHandler interface {
	ListAgents(context.Context, *connect.Request[v1alpha1.ListAgentsRequest]) (*connect.Response[v1alpha1.ListAgentsReponse], error)
	GetAgent(context.Context, *connect.Request[v1alpha1.GetAgentRequest]) (*connect.Response[v1alpha1.GetAgentResponse], error)
	Status(context.Context, *connect.Request[v1alpha1.GetAgentStatusRequest]) (*connect.Response[v1alpha1.AgentStatus], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1alpha1.File_pkg_api_agents_v1alpha1_agents_proto.Services().ByName("AgentService").Methods()
	agentServiceListAgentsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAgentHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStatusHandler := connect.NewUnaryHandler(
		AgentServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(agentServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	return "/config.v1alpha1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceListAgentsProcedure:
			agentServiceListAgentsHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentProcedure:
			agentServiceGetAgentHandler.ServeHTTP(w, r)
		case AgentServiceStatusProcedure:
			agentServiceStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) ListAgents(context.Context, *connect.Request[v1alpha1.ListAgentsRequest]) (*connect.Response[v1alpha1.ListAgentsReponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.AgentService.ListAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgent(context.Context, *connect.Request[v1alpha1.GetAgentRequest]) (*connect.Response[v1alpha1.GetAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.AgentService.GetAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) Status(context.Context, *connect.Request[v1alpha1.GetAgentStatusRequest]) (*connect.Response[v1alpha1.AgentStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.AgentService.Status is not implemented"))
}
