// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/agents/v1alpha1/agents.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterAgentServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterAgentServiceHandler(mux *mux.Router, svc AgentServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/config.v1alpha1.AgentService/ListAgents", connect.NewUnaryHandler(
		"/config.v1alpha1.AgentService/ListAgents",
		svc.ListAgents,
		opts...,
	))
	mux.Handle("/config.v1alpha1.AgentService/GetAgent", connect.NewUnaryHandler(
		"/config.v1alpha1.AgentService/GetAgent",
		svc.GetAgent,
		opts...,
	))
	mux.Handle("/config.v1alpha1.AgentService/Status", connect.NewUnaryHandler(
		"/config.v1alpha1.AgentService/Status",
		svc.Status,
		opts...,
	))
}
