// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/deployment/v1alpha1/deployment.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterCollectorServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterCollectorServiceHandler(mux *mux.Router, svc CollectorServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/deployment.v1alpha1.CollectorService/ListCollectors", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/ListCollectors",
		svc.ListCollectors,
		opts...,
	))
	mux.Handle("/deployment.v1alpha1.CollectorService/GetCollector", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/GetCollector",
		svc.GetCollector,
		opts...,
	))
	mux.Handle("/deployment.v1alpha1.CollectorService/CollectorHistory", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/CollectorHistory",
		svc.CollectorHistory,
		opts...,
	))
	mux.Handle("/deployment.v1alpha1.CollectorService/Status", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/Status",
		svc.Status,
		opts...,
	))
	mux.Handle("/deployment.v1alpha1.CollectorService/DeleteCollector", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/DeleteCollector",
		svc.DeleteCollector,
		opts...,
	))
	mux.Handle("/deployment.v1alpha1.CollectorService/ValidateRouter", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/ValidateRouter",
		svc.ValidateRouter,
		opts...,
	))
	mux.Handle("/deployment.v1alpha1.CollectorService/PreviewRouter", connect.NewUnaryHandler(
		"/deployment.v1alpha1.CollectorService/PreviewRouter",
		svc.PreviewRouter,
		opts...,
	))
}
