// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/api/config/v1alpha1/config.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/config/v1alpha1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "config.v1alpha1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServicePutConfigFilterProcedure is the fully-qualified name of the ConfigService's
	// PutConfigFilter RPC.
	ConfigServicePutConfigFilterProcedure = "/config.v1alpha1.ConfigService/PutConfigFilter"
	// ConfigServiceGetConfigFilterProcedure is the fully-qualified name of the ConfigService's
	// GetConfigFilter RPC.
	ConfigServiceGetConfigFilterProcedure = "/config.v1alpha1.ConfigService/GetConfigFilter"
	// ConfigServiceDeleteConfigFilterProcedure is the fully-qualified name of the ConfigService's
	// DeleteConfigFilter RPC.
	ConfigServiceDeleteConfigFilterProcedure = "/config.v1alpha1.ConfigService/DeleteConfigFilter"
	// ConfigServiceListConfigFiltersProcedure is the fully-qualified name of the ConfigService's
	// ListConfigFilters RPC.
	ConfigServiceListConfigFiltersProcedure = "/config.v1alpha1.ConfigService/ListConfigFilters"
)

// ConfigServiceClient is a client for the config.v1alpha1.ConfigService service.
type ConfigServiceClient interface {
	PutConfigFilter(context.Context, *connect.Request[v1alpha1.PutConfigFilterRequest]) (*connect.Response[emptypb.Empty], error)
	GetConfigFilter(context.Context, *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[v1alpha1.ConfigFilter], error)
	DeleteConfigFilter(context.Context, *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[emptypb.Empty], error)
	ListConfigFilters(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListConfigFiltersResponse], error)
}

// NewConfigServiceClient constructs a client for the config.v1alpha1.ConfigService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1alpha1.File_pkg_api_config_v1alpha1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		putConfigFilter: connect.NewClient[v1alpha1.PutConfigFilterRequest, emptypb.Empty](
			httpClient,
			baseURL+ConfigServicePutConfigFilterProcedure,
			connect.WithSchema(configServiceMethods.ByName("PutConfigFilter")),
			connect.WithClientOptions(opts...),
		),
		getConfigFilter: connect.NewClient[v1alpha1.ConfigFilterReference, v1alpha1.ConfigFilter](
			httpClient,
			baseURL+ConfigServiceGetConfigFilterProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetConfigFilter")),
			connect.WithClientOptions(opts...),
		),
		deleteConfigFilter: connect.NewClient[v1alpha1.ConfigFilterReference, emptypb.Empty](
			httpClient,
			baseURL+ConfigServiceDeleteConfigFilterProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteConfigFilter")),
			connect.WithClientOptions(opts...),
		),
		listConfigFilters: connect.NewClient[emptypb.Empty, v1alpha1.ListConfigFiltersResponse](
			httpClient,
			baseURL+ConfigServiceListConfigFiltersProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListConfigFilters")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	putConfigFilter    *connect.Client[v1alpha1.PutConfigFilterRequest, emptypb.Empty]
	getConfigFilter    *connect.Client[v1alpha1.ConfigFilterReference, v1alpha1.ConfigFilter]
	deleteConfigFilter *connect.Client[v1alpha1.ConfigFilterReference, emptypb.Empty]
	listConfigFilters  *connect.Client[emptypb.Empty, v1alpha1.ListConfigFiltersResponse]
}

// PutConfigFilter calls config.v1alpha1.ConfigService.PutConfigFilter.
func (c *configServiceClient) PutConfigFilter(ctx context.Context, req *connect.Request[v1alpha1.PutConfigFilterRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.putConfigFilter.CallUnary(ctx, req)
}

// GetConfigFilter calls config.v1alpha1.ConfigService.GetConfigFilter.
func (c *configServiceClient) GetConfigFilter(ctx context.Context, req *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[v1alpha1.ConfigFilter], error) {
	return c.getConfigFilter.CallUnary(ctx, req)
}

// DeleteConfigFilter calls config.v1alpha1.ConfigService.DeleteConfigFilter.
func (c *configServiceClient) DeleteConfigFilter(ctx context.Context, req *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteConfigFilter.CallUnary(ctx, req)
}

// ListConfigFilters calls config.v1alpha1.ConfigService.ListConfigFilters.
func (c *configServiceClient) ListConfigFilters(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListConfigFiltersResponse], error) {
	return c.listConfigFilters.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the config.v1alpha1.ConfigService service.
type ConfigServiceHandler interface {
	PutConfigFilter(context.Context, *connect.Request[v1alpha1.PutConfigFilterRequest]) (*connect.Response[emptypb.Empty], error)
	GetConfigFilter(context.Context, *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[v1alpha1.ConfigFilter], error)
	DeleteConfigFilter(context.Context, *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[emptypb.Empty], error)
	ListConfigFilters(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListConfigFiltersResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1alpha1.File_pkg_api_config_v1alpha1_config_proto.Services().ByName("ConfigService").Methods()
	configServicePutConfigFilterHandler := connect.NewUnaryHandler(
		ConfigServicePutConfigFilterProcedure,
		svc.PutConfigFilter,
		connect.WithSchema(configServiceMethods.ByName("PutConfigFilter")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetConfigFilterHandler := connect.NewUnaryHandler(
		ConfigServiceGetConfigFilterProcedure,
		svc.GetConfigFilter,
		connect.WithSchema(configServiceMethods.ByName("GetConfigFilter")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteConfigFilterHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteConfigFilterProcedure,
		svc.DeleteConfigFilter,
		connect.WithSchema(configServiceMethods.ByName("DeleteConfigFilter")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListConfigFiltersHandler := connect.NewUnaryHandler(
		ConfigServiceListConfigFiltersProcedure,
		svc.ListConfigFilters,
		connect.WithSchema(configServiceMethods.ByName("ListConfigFilters")),
		connect.WithHandlerOptions(opts...),
	)
	return "/config.v1alpha1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServicePutConfigFilterProcedure:
			configServicePutConfigFilterHandler.ServeHTTP(w, r)
		case ConfigServiceGetConfigFilterProcedure:
			configServiceGetConfigFilterHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteConfigFilterProcedure:
			configServiceDeleteConfigFilterHandler.ServeHTTP(w, r)
		case ConfigServiceListConfigFiltersProcedure:
			configServiceListConfigFiltersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) PutConfigFilter(context.Context, *connect.Request[v1alpha1.PutConfigFilterRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.PutConfigFilter is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetConfigFilter(context.Context, *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[v1alpha1.ConfigFilter], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.GetConfigFilter is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteConfigFilter(context.Context, *connect.Request[v1alpha1.ConfigFilterReference]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.DeleteConfigFilter is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListConfigFilters(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListConfigFiltersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.ListConfigFilters is not implemented"))
}
