// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/config/v1alpha1/config.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterConfigServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterConfigServiceHandler(mux *mux.Router, svc ConfigServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/config.v1alpha1.ConfigService/ValidConfig", connect.NewUnaryHandler(
		"/config.v1alpha1.ConfigService/ValidConfig",
		svc.ValidConfig,
		opts...,
	))
	mux.Handle("/config.v1alpha1.ConfigService/UpdateConfig", connect.NewUnaryHandler(
		"/config.v1alpha1.ConfigService/UpdateConfig",
		svc.UpdateConfig,
		opts...,
	))
	mux.Handle("/config.v1alpha1.ConfigService/GetConfig", connect.NewUnaryHandler(
		"/config.v1alpha1.ConfigService/GetConfig",
		svc.GetConfig,
		opts...,
	))
	mux.Handle("/config.v1alpha1.ConfigService/DeleteConfig", connect.NewUnaryHandler(
		"/config.v1alpha1.ConfigService/DeleteConfig",
		svc.DeleteConfig,
		opts...,
	))
	mux.Handle("/config.v1alpha1.ConfigService/ListConfigs", connect.NewUnaryHandler(
		"/config.v1alpha1.ConfigService/ListConfigs",
		svc.ListConfigs,
		opts...,
	))
	mux.Handle("/config.v1alpha1.ConfigService/SetDefaultConfig", connect.NewUnaryHandler(
		"/config.v1alpha1.ConfigService/SetDefaultConfig",
		svc.SetDefaultConfig,
		opts...,
	))
}
