// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pkg/api/agents/v1alpha1/agents.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState int32

const (
	AgentState_AGENT_STATE_UNKNOWN      AgentState = 0
	AgentState_AGENT_STATE_CONNECTED    AgentState = 1
	AgentState_AGENT_STATE_DISCONNECTED AgentState = 2
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNKNOWN",
		1: "AGENT_STATE_CONNECTED",
		2: "AGENT_STATE_DISCONNECTED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNKNOWN":      0,
		"AGENT_STATE_CONNECTED":    1,
		"AGENT_STATE_DISCONNECTED": 2,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{0}
}

// ConfigSyncStatus represents the unified config synchronization status.
// This is server-computed based on comparing assigned config hash with agent-reported hash.
type ConfigSyncStatus int32

const (
	ConfigSyncStatus_CONFIG_SYNC_STATUS_UNKNOWN     ConfigSyncStatus = 0 // No assignment or unable to determine
	ConfigSyncStatus_CONFIG_SYNC_STATUS_IN_SYNC     ConfigSyncStatus = 1 // Assigned config hash matches reported hash and status is APPLIED
	ConfigSyncStatus_CONFIG_SYNC_STATUS_OUT_OF_SYNC ConfigSyncStatus = 2 // Hash mismatch or no status reported
	ConfigSyncStatus_CONFIG_SYNC_STATUS_APPLYING    ConfigSyncStatus = 3 // Agent is currently applying the config
	ConfigSyncStatus_CONFIG_SYNC_STATUS_ERROR       ConfigSyncStatus = 4 // Agent reported failure applying config
)

// Enum value maps for ConfigSyncStatus.
var (
	ConfigSyncStatus_name = map[int32]string{
		0: "CONFIG_SYNC_STATUS_UNKNOWN",
		1: "CONFIG_SYNC_STATUS_IN_SYNC",
		2: "CONFIG_SYNC_STATUS_OUT_OF_SYNC",
		3: "CONFIG_SYNC_STATUS_APPLYING",
		4: "CONFIG_SYNC_STATUS_ERROR",
	}
	ConfigSyncStatus_value = map[string]int32{
		"CONFIG_SYNC_STATUS_UNKNOWN":     0,
		"CONFIG_SYNC_STATUS_IN_SYNC":     1,
		"CONFIG_SYNC_STATUS_OUT_OF_SYNC": 2,
		"CONFIG_SYNC_STATUS_APPLYING":    3,
		"CONFIG_SYNC_STATUS_ERROR":       4,
	}
)

func (x ConfigSyncStatus) Enum() *ConfigSyncStatus {
	p := new(ConfigSyncStatus)
	*p = x
	return p
}

func (x ConfigSyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigSyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[1].Descriptor()
}

func (ConfigSyncStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[1]
}

func (x ConfigSyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigSyncStatus.Descriptor instead.
func (ConfigSyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{1}
}

type RemoteConfigStatuses int32

const (
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_UNSET    RemoteConfigStatuses = 0
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_APPLIED  RemoteConfigStatuses = 1
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_APPLYING RemoteConfigStatuses = 2
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_FAILED   RemoteConfigStatuses = 3
)

// Enum value maps for RemoteConfigStatuses.
var (
	RemoteConfigStatuses_name = map[int32]string{
		0: "REMOTE_CONFIG_STATUSES_UNSET",
		1: "REMOTE_CONFIG_STATUSES_APPLIED",
		2: "REMOTE_CONFIG_STATUSES_APPLYING",
		3: "REMOTE_CONFIG_STATUSES_FAILED",
	}
	RemoteConfigStatuses_value = map[string]int32{
		"REMOTE_CONFIG_STATUSES_UNSET":    0,
		"REMOTE_CONFIG_STATUSES_APPLIED":  1,
		"REMOTE_CONFIG_STATUSES_APPLYING": 2,
		"REMOTE_CONFIG_STATUSES_FAILED":   3,
	}
)

func (x RemoteConfigStatuses) Enum() *RemoteConfigStatuses {
	p := new(RemoteConfigStatuses)
	*p = x
	return p
}

func (x RemoteConfigStatuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteConfigStatuses) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[2].Descriptor()
}

func (RemoteConfigStatuses) Type() protoreflect.EnumType {
	return &file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[2]
}

func (x RemoteConfigStatuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteConfigStatuses.Descriptor instead.
func (RemoteConfigStatuses) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{2}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithStatus    bool                   `protobuf:"varint,1,opt,name=with_status,json=withStatus,proto3" json:"with_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetWithStatus() bool {
	if x != nil {
		return x.WithStatus
	}
	return false
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Agents        []*AgentDescriptionAndStatus `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetAgents() []*AgentDescriptionAndStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

// AgentView combines registration and status for list/get responses.
// This is the preferred type name for combined agent data.
type AgentView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *AgentRegistration     `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentView) Reset() {
	*x = AgentView{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentView) ProtoMessage() {}

func (x *AgentView) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentView.ProtoReflect.Descriptor instead.
func (*AgentView) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *AgentView) GetRegistration() *AgentRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *AgentView) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AgentDescriptionAndStatus is kept for backward compatibility.
// Use AgentView for new code.
type AgentDescriptionAndStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescription      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDescriptionAndStatus) Reset() {
	*x = AgentDescriptionAndStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescriptionAndStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescriptionAndStatus) ProtoMessage() {}

func (x *AgentDescriptionAndStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescriptionAndStatus.ProtoReflect.Descriptor instead.
func (*AgentDescriptionAndStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *AgentDescriptionAndStatus) GetAgent() *AgentDescription {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AgentDescriptionAndStatus) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescription      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentResponse) GetAgent() *AgentDescription {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AgentStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgentStatusResponse) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	State              AgentState             `protobuf:"varint,1,opt,name=state,proto3,enum=config.v1alpha1.AgentState" json:"state,omitempty"`
	Health             *ComponentHealth       `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	EffectiveConfig    *EffectiveConfig       `protobuf:"bytes,3,opt,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty"`
	RemoteConfigStatus *RemoteConfigStatus    `protobuf:"bytes,4,opt,name=remote_config_status,json=remoteConfigStatus,proto3" json:"remote_config_status,omitempty"`
	// New fields for unified status
	LastSeen         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ConfigSyncStatus ConfigSyncStatus       `protobuf:"varint,6,opt,name=config_sync_status,json=configSyncStatus,proto3,enum=config.v1alpha1.ConfigSyncStatus" json:"config_sync_status,omitempty"`
	ConfigSyncReason string                 `protobuf:"bytes,7,opt,name=config_sync_reason,json=configSyncReason,proto3" json:"config_sync_reason,omitempty"`
	ConnectedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{9}
}

func (x *AgentStatus) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNKNOWN
}

func (x *AgentStatus) GetHealth() *ComponentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *AgentStatus) GetEffectiveConfig() *EffectiveConfig {
	if x != nil {
		return x.EffectiveConfig
	}
	return nil
}

func (x *AgentStatus) GetRemoteConfigStatus() *RemoteConfigStatus {
	if x != nil {
		return x.RemoteConfigStatus
	}
	return nil
}

func (x *AgentStatus) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *AgentStatus) GetConfigSyncStatus() ConfigSyncStatus {
	if x != nil {
		return x.ConfigSyncStatus
	}
	return ConfigSyncStatus_CONFIG_SYNC_STATUS_UNKNOWN
}

func (x *AgentStatus) GetConfigSyncReason() string {
	if x != nil {
		return x.ConfigSyncReason
	}
	return ""
}

func (x *AgentStatus) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *AgentStatus) GetDisconnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectedAt
	}
	return nil
}

// AgentRegistration represents the core agent identity and attributes.
// This is the preferred type name for agent registration data.
type AgentRegistration struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string                 `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	// Attributes that identify the Agent (e.g., service.name, service.version, service.instance.id).
	IdentifyingAttributes []*KeyValue `protobuf:"bytes,3,rep,name=identifying_attributes,json=identifyingAttributes,proto3" json:"identifying_attributes,omitempty"`
	// Attributes that do not necessarily identify the Agent but help describe where it runs.
	NonIdentifyingAttributes []*KeyValue `protobuf:"bytes,4,rep,name=non_identifying_attributes,json=nonIdentifyingAttributes,proto3" json:"non_identifying_attributes,omitempty"`
	Capabilities             []string    `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{10}
}

func (x *AgentRegistration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentRegistration) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *AgentRegistration) GetIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.IdentifyingAttributes
	}
	return nil
}

func (x *AgentRegistration) GetNonIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.NonIdentifyingAttributes
	}
	return nil
}

func (x *AgentRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AgentDescription is kept for backward compatibility.
// Use AgentRegistration for new code.
type AgentDescription struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string                 `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	// Attributes that identify the Agent (e.g., service.name, service.version, service.instance.id).
	// These attributes uniquely identify the agent and should be used for its own telemetry.
	IdentifyingAttributes []*KeyValue `protobuf:"bytes,3,rep,name=identifying_attributes,json=identifyingAttributes,proto3" json:"identifying_attributes,omitempty"`
	// Attributes that do not necessarily identify the Agent but help describe where it runs
	// (e.g., os.type, os.version, host.*, cloud.*).
	NonIdentifyingAttributes []*KeyValue `protobuf:"bytes,4,rep,name=non_identifying_attributes,json=nonIdentifyingAttributes,proto3" json:"non_identifying_attributes,omitempty"`
	Capabilities             []string    `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentDescription) Reset() {
	*x = AgentDescription{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescription) ProtoMessage() {}

func (x *AgentDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescription.ProtoReflect.Descriptor instead.
func (*AgentDescription) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{11}
}

func (x *AgentDescription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDescription) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *AgentDescription) GetIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.IdentifyingAttributes
	}
	return nil
}

func (x *AgentDescription) GetNonIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.NonIdentifyingAttributes
	}
	return nil
}

func (x *AgentDescription) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// KeyValue represents a key-value pair with support for various value types.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *AnyValue              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{12}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *AnyValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// AnyValue represents a value that can be one of several types.
type AnyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BoolValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_BytesValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_KvlistValue
	Value         isAnyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyValue) Reset() {
	*x = AnyValue{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyValue) ProtoMessage() {}

func (x *AnyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyValue.ProtoReflect.Descriptor instead.
func (*AnyValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{13}
}

func (x *AnyValue) GetValue() isAnyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnyValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AnyValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnyValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AnyValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *AnyValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *AnyValue) GetKvlistValue() *KeyValueList {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnyValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AnyValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AnyValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type AnyValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,6,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type AnyValue_KvlistValue struct {
	KvlistValue *KeyValueList `protobuf:"bytes,7,opt,name=kvlist_value,json=kvlistValue,proto3,oneof"`
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

func (*AnyValue_BoolValue) isAnyValue_Value() {}

func (*AnyValue_IntValue) isAnyValue_Value() {}

func (*AnyValue_DoubleValue) isAnyValue_Value() {}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

func (*AnyValue_ArrayValue) isAnyValue_Value() {}

func (*AnyValue_KvlistValue) isAnyValue_Value() {}

// ArrayValue holds an array of AnyValue.
type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AnyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{14}
}

func (x *ArrayValue) GetValues() []*AnyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValueList holds a list of KeyValue pairs.
type KeyValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KeyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueList) Reset() {
	*x = KeyValueList{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueList) ProtoMessage() {}

func (x *KeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueList.ProtoReflect.Descriptor instead.
func (*KeyValueList) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{15}
}

func (x *KeyValueList) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// AgentConnectionState represents the persisted connection state of an agent.
// This replaces the in-memory AgentTracker state.
type AgentConnectionState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	State          AgentState             `protobuf:"varint,2,opt,name=state,proto3,enum=config.v1alpha1.AgentState" json:"state,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ConnectedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	InstanceUid    []byte                 `protobuf:"bytes,6,opt,name=instance_uid,json=instanceUid,proto3" json:"instance_uid,omitempty"`
	Capabilities   uint64                 `protobuf:"varint,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	SequenceNum    uint64                 `protobuf:"varint,8,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentConnectionState) Reset() {
	*x = AgentConnectionState{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnectionState) ProtoMessage() {}

func (x *AgentConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnectionState.ProtoReflect.Descriptor instead.
func (*AgentConnectionState) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{16}
}

func (x *AgentConnectionState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentConnectionState) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNKNOWN
}

func (x *AgentConnectionState) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *AgentConnectionState) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *AgentConnectionState) GetDisconnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectedAt
	}
	return nil
}

func (x *AgentConnectionState) GetInstanceUid() []byte {
	if x != nil {
		return x.InstanceUid
	}
	return nil
}

func (x *AgentConnectionState) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *AgentConnectionState) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

// ComponentHealth represents the health status of an agent and its components.
type ComponentHealth struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Healthy            bool                        `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	StartTimeUnixNano  uint64                      `protobuf:"varint,2,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	LastError          string                      `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Status             string                      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StatusTimeUnixNano uint64                      `protobuf:"varint,5,opt,name=status_time_unix_nano,json=statusTimeUnixNano,proto3" json:"status_time_unix_nano,omitempty"`
	ComponentHealthMap map[string]*ComponentHealth `protobuf:"bytes,6,rep,name=component_health_map,json=componentHealthMap,proto3" json:"component_health_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *ComponentHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetStatusTimeUnixNano() uint64 {
	if x != nil {
		return x.StatusTimeUnixNano
	}
	return 0
}

func (x *ComponentHealth) GetComponentHealthMap() map[string]*ComponentHealth {
	if x != nil {
		return x.ComponentHealthMap
	}
	return nil
}

// EffectiveConfig represents the current effective configuration of an agent.
type EffectiveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigMap     *AgentConfigMap        `protobuf:"bytes,1,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveConfig) Reset() {
	*x = EffectiveConfig{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveConfig) ProtoMessage() {}

func (x *EffectiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveConfig.ProtoReflect.Descriptor instead.
func (*EffectiveConfig) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{18}
}

func (x *EffectiveConfig) GetConfigMap() *AgentConfigMap {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

// AgentConfigMap holds a map of config file names to their content.
type AgentConfigMap struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ConfigMap     map[string]*AgentConfigFile `protobuf:"bytes,1,rep,name=config_map,json=configMap,proto3" json:"config_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigMap) Reset() {
	*x = AgentConfigMap{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigMap) ProtoMessage() {}

func (x *AgentConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigMap.ProtoReflect.Descriptor instead.
func (*AgentConfigMap) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{19}
}

func (x *AgentConfigMap) GetConfigMap() map[string]*AgentConfigFile {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

// AgentConfigFile represents a single configuration file.
type AgentConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigFile) Reset() {
	*x = AgentConfigFile{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigFile) ProtoMessage() {}

func (x *AgentConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigFile.ProtoReflect.Descriptor instead.
func (*AgentConfigFile) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{20}
}

func (x *AgentConfigFile) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentConfigFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// RemoteConfigStatus represents the status of a remote configuration on an agent.
type RemoteConfigStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LastRemoteConfigHash []byte                 `protobuf:"bytes,1,opt,name=last_remote_config_hash,json=lastRemoteConfigHash,proto3" json:"last_remote_config_hash,omitempty"`
	Status               RemoteConfigStatuses   `protobuf:"varint,2,opt,name=status,proto3,enum=config.v1alpha1.RemoteConfigStatuses" json:"status,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoteConfigStatus) Reset() {
	*x = RemoteConfigStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteConfigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfigStatus) ProtoMessage() {}

func (x *RemoteConfigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfigStatus.ProtoReflect.Descriptor instead.
func (*RemoteConfigStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{21}
}

func (x *RemoteConfigStatus) GetLastRemoteConfigHash() []byte {
	if x != nil {
		return x.LastRemoteConfigHash
	}
	return nil
}

func (x *RemoteConfigStatus) GetStatus() RemoteConfigStatuses {
	if x != nil {
		return x.Status
	}
	return RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_UNSET
}

func (x *RemoteConfigStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_api_agents_v1alpha1_agents_proto protoreflect.FileDescriptor

const file_pkg_api_agents_v1alpha1_agents_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/agents/v1alpha1/agents.proto\x12\x0fconfig.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\x11ListAgentsRequest\x12\x1f\n" +
	"\vwith_status\x18\x01 \x01(\bR\n" +
	"withStatus\"X\n" +
	"\x12ListAgentsResponse\x12B\n" +
	"\x06agents\x18\x01 \x03(\v2*.config.v1alpha1.AgentDescriptionAndStatusR\x06agents\"\x89\x01\n" +
	"\tAgentView\x12F\n" +
	"\fregistration\x18\x01 \x01(\v2\".config.v1alpha1.AgentRegistrationR\fregistration\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1c.config.v1alpha1.AgentStatusR\x06status\"\x8a\x01\n" +
	"\x19AgentDescriptionAndStatus\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.config.v1alpha1.AgentDescriptionR\x05agent\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1c.config.v1alpha1.AgentStatusR\x06status\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"K\n" +
	"\x10GetAgentResponse\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.config.v1alpha1.AgentDescriptionR\x05agent\"2\n" +
	"\x15GetAgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"N\n" +
	"\x16GetAgentStatusResponse\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x1c.config.v1alpha1.AgentStatusR\x06status\"/\n" +
	"\x12DeleteAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xda\x04\n" +
	"\vAgentStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.config.v1alpha1.AgentStateR\x05state\x128\n" +
	"\x06health\x18\x02 \x01(\v2 .config.v1alpha1.ComponentHealthR\x06health\x12K\n" +
	"\x10effective_config\x18\x03 \x01(\v2 .config.v1alpha1.EffectiveConfigR\x0feffectiveConfig\x12U\n" +
	"\x14remote_config_status\x18\x04 \x01(\v2#.config.v1alpha1.RemoteConfigStatusR\x12remoteConfigStatus\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12O\n" +
	"\x12config_sync_status\x18\x06 \x01(\x0e2!.config.v1alpha1.ConfigSyncStatusR\x10configSyncStatus\x12,\n" +
	"\x12config_sync_reason\x18\a \x01(\tR\x10configSyncReason\x12=\n" +
	"\fconnected_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12C\n" +
	"\x0fdisconnected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectedAt\"\x97\x02\n" +
	"\x11AgentRegistration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfriendly_name\x18\x02 \x01(\tR\ffriendlyName\x12P\n" +
	"\x16identifying_attributes\x18\x03 \x03(\v2\x19.config.v1alpha1.KeyValueR\x15identifyingAttributes\x12W\n" +
	"\x1anon_identifying_attributes\x18\x04 \x03(\v2\x19.config.v1alpha1.KeyValueR\x18nonIdentifyingAttributes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\x96\x02\n" +
	"\x10AgentDescription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfriendly_name\x18\x02 \x01(\tR\ffriendlyName\x12P\n" +
	"\x16identifying_attributes\x18\x03 \x03(\v2\x19.config.v1alpha1.KeyValueR\x15identifyingAttributes\x12W\n" +
	"\x1anon_identifying_attributes\x18\x04 \x03(\v2\x19.config.v1alpha1.KeyValueR\x18nonIdentifyingAttributes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"M\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.config.v1alpha1.AnyValueR\x05value\"\xc4\x02\n" +
	"\bAnyValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12>\n" +
	"\varray_value\x18\x06 \x01(\v2\x1b.config.v1alpha1.ArrayValueH\x00R\n" +
	"arrayValue\x12B\n" +
	"\fkvlist_value\x18\a \x01(\v2\x1d.config.v1alpha1.KeyValueListH\x00R\vkvlistValueB\a\n" +
	"\x05value\"?\n" +
	"\n" +
	"ArrayValue\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.config.v1alpha1.AnyValueR\x06values\"A\n" +
	"\fKeyValueList\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.config.v1alpha1.KeyValueR\x06values\"\x8b\x03\n" +
	"\x14AgentConnectionState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x121\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.config.v1alpha1.AgentStateR\x05state\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12=\n" +
	"\fconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12C\n" +
	"\x0fdisconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectedAt\x12!\n" +
	"\finstance_uid\x18\x06 \x01(\fR\vinstanceUid\x12\"\n" +
	"\fcapabilities\x18\a \x01(\x04R\fcapabilities\x12!\n" +
	"\fsequence_num\x18\b \x01(\x04R\vsequenceNum\"\x9b\x03\n" +
	"\x0fComponentHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12/\n" +
	"\x14start_time_unix_nano\x18\x02 \x01(\x04R\x11startTimeUnixNano\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x121\n" +
	"\x15status_time_unix_nano\x18\x05 \x01(\x04R\x12statusTimeUnixNano\x12j\n" +
	"\x14component_health_map\x18\x06 \x03(\v28.config.v1alpha1.ComponentHealth.ComponentHealthMapEntryR\x12componentHealthMap\x1ag\n" +
	"\x17ComponentHealthMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .config.v1alpha1.ComponentHealthR\x05value:\x028\x01\"Q\n" +
	"\x0fEffectiveConfig\x12>\n" +
	"\n" +
	"config_map\x18\x01 \x01(\v2\x1f.config.v1alpha1.AgentConfigMapR\tconfigMap\"\xbf\x01\n" +
	"\x0eAgentConfigMap\x12M\n" +
	"\n" +
	"config_map\x18\x01 \x03(\v2..config.v1alpha1.AgentConfigMap.ConfigMapEntryR\tconfigMap\x1a^\n" +
	"\x0eConfigMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .config.v1alpha1.AgentConfigFileR\x05value:\x028\x01\"H\n" +
	"\x0fAgentConfigFile\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xaf\x01\n" +
	"\x12RemoteConfigStatus\x125\n" +
	"\x17last_remote_config_hash\x18\x01 \x01(\fR\x14lastRemoteConfigHash\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.config.v1alpha1.RemoteConfigStatusesR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*^\n" +
	"\n" +
	"AgentState\x12\x17\n" +
	"\x13AGENT_STATE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15AGENT_STATE_CONNECTED\x10\x01\x12\x1c\n" +
	"\x18AGENT_STATE_DISCONNECTED\x10\x02*\xb5\x01\n" +
	"\x10ConfigSyncStatus\x12\x1e\n" +
	"\x1aCONFIG_SYNC_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aCONFIG_SYNC_STATUS_IN_SYNC\x10\x01\x12\"\n" +
	"\x1eCONFIG_SYNC_STATUS_OUT_OF_SYNC\x10\x02\x12\x1f\n" +
	"\x1bCONFIG_SYNC_STATUS_APPLYING\x10\x03\x12\x1c\n" +
	"\x18CONFIG_SYNC_STATUS_ERROR\x10\x04*\xa4\x01\n" +
	"\x14RemoteConfigStatuses\x12 \n" +
	"\x1cREMOTE_CONFIG_STATUSES_UNSET\x10\x00\x12\"\n" +
	"\x1eREMOTE_CONFIG_STATUSES_APPLIED\x10\x01\x12#\n" +
	"\x1fREMOTE_CONFIG_STATUSES_APPLYING\x10\x02\x12!\n" +
	"\x1dREMOTE_CONFIG_STATUSES_FAILED\x10\x032\xdd\x02\n" +
	"\fAgentService\x12U\n" +
	"\n" +
	"ListAgents\x12\".config.v1alpha1.ListAgentsRequest\x1a#.config.v1alpha1.ListAgentsResponse\x12O\n" +
	"\bGetAgent\x12 .config.v1alpha1.GetAgentRequest\x1a!.config.v1alpha1.GetAgentResponse\x12Y\n" +
	"\x06Status\x12&.config.v1alpha1.GetAgentStatusRequest\x1a'.config.v1alpha1.GetAgentStatusResponse\x12J\n" +
	"\vDeleteAgent\x12#.config.v1alpha1.DeleteAgentRequest\x1a\x16.google.protobuf.EmptyB8Z6github.com/otelfleet/otelfleet/pkg/api/agents/v1alpha1b\x06proto3"

var (
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescOnce sync.Once
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescData []byte
)

func file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP() []byte {
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescOnce.Do(func() {
		file_pkg_api_agents_v1alpha1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc), len(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc)))
	})
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescData
}

var file_pkg_api_agents_v1alpha1_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_api_agents_v1alpha1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_api_agents_v1alpha1_agents_proto_goTypes = []any{
	(AgentState)(0),                   // 0: config.v1alpha1.AgentState
	(ConfigSyncStatus)(0),             // 1: config.v1alpha1.ConfigSyncStatus
	(RemoteConfigStatuses)(0),         // 2: config.v1alpha1.RemoteConfigStatuses
	(*ListAgentsRequest)(nil),         // 3: config.v1alpha1.ListAgentsRequest
	(*ListAgentsResponse)(nil),        // 4: config.v1alpha1.ListAgentsResponse
	(*AgentView)(nil),                 // 5: config.v1alpha1.AgentView
	(*AgentDescriptionAndStatus)(nil), // 6: config.v1alpha1.AgentDescriptionAndStatus
	(*GetAgentRequest)(nil),           // 7: config.v1alpha1.GetAgentRequest
	(*GetAgentResponse)(nil),          // 8: config.v1alpha1.GetAgentResponse
	(*GetAgentStatusRequest)(nil),     // 9: config.v1alpha1.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil),    // 10: config.v1alpha1.GetAgentStatusResponse
	(*DeleteAgentRequest)(nil),        // 11: config.v1alpha1.DeleteAgentRequest
	(*AgentStatus)(nil),               // 12: config.v1alpha1.AgentStatus
	(*AgentRegistration)(nil),         // 13: config.v1alpha1.AgentRegistration
	(*AgentDescription)(nil),          // 14: config.v1alpha1.AgentDescription
	(*KeyValue)(nil),                  // 15: config.v1alpha1.KeyValue
	(*AnyValue)(nil),                  // 16: config.v1alpha1.AnyValue
	(*ArrayValue)(nil),                // 17: config.v1alpha1.ArrayValue
	(*KeyValueList)(nil),              // 18: config.v1alpha1.KeyValueList
	(*AgentConnectionState)(nil),      // 19: config.v1alpha1.AgentConnectionState
	(*ComponentHealth)(nil),           // 20: config.v1alpha1.ComponentHealth
	(*EffectiveConfig)(nil),           // 21: config.v1alpha1.EffectiveConfig
	(*AgentConfigMap)(nil),            // 22: config.v1alpha1.AgentConfigMap
	(*AgentConfigFile)(nil),           // 23: config.v1alpha1.AgentConfigFile
	(*RemoteConfigStatus)(nil),        // 24: config.v1alpha1.RemoteConfigStatus
	nil,                               // 25: config.v1alpha1.ComponentHealth.ComponentHealthMapEntry
	nil,                               // 26: config.v1alpha1.AgentConfigMap.ConfigMapEntry
	(*timestamppb.Timestamp)(nil),     // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 28: google.protobuf.Empty
}
var file_pkg_api_agents_v1alpha1_agents_proto_depIdxs = []int32{
	6,  // 0: config.v1alpha1.ListAgentsResponse.agents:type_name -> config.v1alpha1.AgentDescriptionAndStatus
	13, // 1: config.v1alpha1.AgentView.registration:type_name -> config.v1alpha1.AgentRegistration
	12, // 2: config.v1alpha1.AgentView.status:type_name -> config.v1alpha1.AgentStatus
	14, // 3: config.v1alpha1.AgentDescriptionAndStatus.agent:type_name -> config.v1alpha1.AgentDescription
	12, // 4: config.v1alpha1.AgentDescriptionAndStatus.status:type_name -> config.v1alpha1.AgentStatus
	14, // 5: config.v1alpha1.GetAgentResponse.agent:type_name -> config.v1alpha1.AgentDescription
	12, // 6: config.v1alpha1.GetAgentStatusResponse.status:type_name -> config.v1alpha1.AgentStatus
	0,  // 7: config.v1alpha1.AgentStatus.state:type_name -> config.v1alpha1.AgentState
	20, // 8: config.v1alpha1.AgentStatus.health:type_name -> config.v1alpha1.ComponentHealth
	21, // 9: config.v1alpha1.AgentStatus.effective_config:type_name -> config.v1alpha1.EffectiveConfig
	24, // 10: config.v1alpha1.AgentStatus.remote_config_status:type_name -> config.v1alpha1.RemoteConfigStatus
	27, // 11: config.v1alpha1.AgentStatus.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 12: config.v1alpha1.AgentStatus.config_sync_status:type_name -> config.v1alpha1.ConfigSyncStatus
	27, // 13: config.v1alpha1.AgentStatus.connected_at:type_name -> google.protobuf.Timestamp
	27, // 14: config.v1alpha1.AgentStatus.disconnected_at:type_name -> google.protobuf.Timestamp
	15, // 15: config.v1alpha1.AgentRegistration.identifying_attributes:type_name -> config.v1alpha1.KeyValue
	15, // 16: config.v1alpha1.AgentRegistration.non_identifying_attributes:type_name -> config.v1alpha1.KeyValue
	15, // 17: config.v1alpha1.AgentDescription.identifying_attributes:type_name -> config.v1alpha1.KeyValue
	15, // 18: config.v1alpha1.AgentDescription.non_identifying_attributes:type_name -> config.v1alpha1.KeyValue
	16, // 19: config.v1alpha1.KeyValue.value:type_name -> config.v1alpha1.AnyValue
	17, // 20: config.v1alpha1.AnyValue.array_value:type_name -> config.v1alpha1.ArrayValue
	18, // 21: config.v1alpha1.AnyValue.kvlist_value:type_name -> config.v1alpha1.KeyValueList
	16, // 22: config.v1alpha1.ArrayValue.values:type_name -> config.v1alpha1.AnyValue
	15, // 23: config.v1alpha1.KeyValueList.values:type_name -> config.v1alpha1.KeyValue
	0,  // 24: config.v1alpha1.AgentConnectionState.state:type_name -> config.v1alpha1.AgentState
	27, // 25: config.v1alpha1.AgentConnectionState.last_seen:type_name -> google.protobuf.Timestamp
	27, // 26: config.v1alpha1.AgentConnectionState.connected_at:type_name -> google.protobuf.Timestamp
	27, // 27: config.v1alpha1.AgentConnectionState.disconnected_at:type_name -> google.protobuf.Timestamp
	25, // 28: config.v1alpha1.ComponentHealth.component_health_map:type_name -> config.v1alpha1.ComponentHealth.ComponentHealthMapEntry
	22, // 29: config.v1alpha1.EffectiveConfig.config_map:type_name -> config.v1alpha1.AgentConfigMap
	26, // 30: config.v1alpha1.AgentConfigMap.config_map:type_name -> config.v1alpha1.AgentConfigMap.ConfigMapEntry
	2,  // 31: config.v1alpha1.RemoteConfigStatus.status:type_name -> config.v1alpha1.RemoteConfigStatuses
	20, // 32: config.v1alpha1.ComponentHealth.ComponentHealthMapEntry.value:type_name -> config.v1alpha1.ComponentHealth
	23, // 33: config.v1alpha1.AgentConfigMap.ConfigMapEntry.value:type_name -> config.v1alpha1.AgentConfigFile
	3,  // 34: config.v1alpha1.AgentService.ListAgents:input_type -> config.v1alpha1.ListAgentsRequest
	7,  // 35: config.v1alpha1.AgentService.GetAgent:input_type -> config.v1alpha1.GetAgentRequest
	9,  // 36: config.v1alpha1.AgentService.Status:input_type -> config.v1alpha1.GetAgentStatusRequest
	11, // 37: config.v1alpha1.AgentService.DeleteAgent:input_type -> config.v1alpha1.DeleteAgentRequest
	4,  // 38: config.v1alpha1.AgentService.ListAgents:output_type -> config.v1alpha1.ListAgentsResponse
	8,  // 39: config.v1alpha1.AgentService.GetAgent:output_type -> config.v1alpha1.GetAgentResponse
	10, // 40: config.v1alpha1.AgentService.Status:output_type -> config.v1alpha1.GetAgentStatusResponse
	28, // 41: config.v1alpha1.AgentService.DeleteAgent:output_type -> google.protobuf.Empty
	38, // [38:42] is the sub-list for method output_type
	34, // [34:38] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_pkg_api_agents_v1alpha1_agents_proto_init() }
func file_pkg_api_agents_v1alpha1_agents_proto_init() {
	if File_pkg_api_agents_v1alpha1_agents_proto != nil {
		return
	}
	file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[13].OneofWrappers = []any{
		(*AnyValue_StringValue)(nil),
		(*AnyValue_BoolValue)(nil),
		(*AnyValue_IntValue)(nil),
		(*AnyValue_DoubleValue)(nil),
		(*AnyValue_BytesValue)(nil),
		(*AnyValue_ArrayValue)(nil),
		(*AnyValue_KvlistValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc), len(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_agents_v1alpha1_agents_proto_goTypes,
		DependencyIndexes: file_pkg_api_agents_v1alpha1_agents_proto_depIdxs,
		EnumInfos:         file_pkg_api_agents_v1alpha1_agents_proto_enumTypes,
		MessageInfos:      file_pkg_api_agents_v1alpha1_agents_proto_msgTypes,
	}.Build()
	File_pkg_api_agents_v1alpha1_agents_proto = out.File
	file_pkg_api_agents_v1alpha1_agents_proto_goTypes = nil
	file_pkg_api_agents_v1alpha1_agents_proto_depIdxs = nil
}
