// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/agents/v1alpha1/agents.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState int32

const (
	AgentState_AGENT_STATE_UNKNOWN      AgentState = 0
	AgentState_AGENT_STATE_CONNECTED    AgentState = 1
	AgentState_AGENT_STATE_DISCONNECTED AgentState = 2
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNKNOWN",
		1: "AGENT_STATE_CONNECTED",
		2: "AGENT_STATE_DISCONNECTED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNKNOWN":      0,
		"AGENT_STATE_CONNECTED":    1,
		"AGENT_STATE_DISCONNECTED": 2,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{0}
}

type RemoteConfigStatuses int32

const (
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_UNSET    RemoteConfigStatuses = 0
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_APPLIED  RemoteConfigStatuses = 1
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_APPLYING RemoteConfigStatuses = 2
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_FAILED   RemoteConfigStatuses = 3
)

// Enum value maps for RemoteConfigStatuses.
var (
	RemoteConfigStatuses_name = map[int32]string{
		0: "REMOTE_CONFIG_STATUSES_UNSET",
		1: "REMOTE_CONFIG_STATUSES_APPLIED",
		2: "REMOTE_CONFIG_STATUSES_APPLYING",
		3: "REMOTE_CONFIG_STATUSES_FAILED",
	}
	RemoteConfigStatuses_value = map[string]int32{
		"REMOTE_CONFIG_STATUSES_UNSET":    0,
		"REMOTE_CONFIG_STATUSES_APPLIED":  1,
		"REMOTE_CONFIG_STATUSES_APPLYING": 2,
		"REMOTE_CONFIG_STATUSES_FAILED":   3,
	}
)

func (x RemoteConfigStatuses) Enum() *RemoteConfigStatuses {
	p := new(RemoteConfigStatuses)
	*p = x
	return p
}

func (x RemoteConfigStatuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteConfigStatuses) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[1].Descriptor()
}

func (RemoteConfigStatuses) Type() protoreflect.EnumType {
	return &file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[1]
}

func (x RemoteConfigStatuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteConfigStatuses.Descriptor instead.
func (RemoteConfigStatuses) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{1}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithStatus    bool                   `protobuf:"varint,1,opt,name=with_status,json=withStatus,proto3" json:"with_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetWithStatus() bool {
	if x != nil {
		return x.WithStatus
	}
	return false
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Agents        []*AgentDescriptionAndStatus `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetAgents() []*AgentDescriptionAndStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentDescriptionAndStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescription      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDescriptionAndStatus) Reset() {
	*x = AgentDescriptionAndStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescriptionAndStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescriptionAndStatus) ProtoMessage() {}

func (x *AgentDescriptionAndStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescriptionAndStatus.ProtoReflect.Descriptor instead.
func (*AgentDescriptionAndStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *AgentDescriptionAndStatus) GetAgent() *AgentDescription {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AgentDescriptionAndStatus) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescription      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentResponse) GetAgent() *AgentDescription {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AgentStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentStatusResponse) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AgentStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	State              AgentState             `protobuf:"varint,1,opt,name=state,proto3,enum=config.v1alpha1.AgentState" json:"state,omitempty"`
	Health             *ComponentHealth       `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	EffectiveConfig    *EffectiveConfig       `protobuf:"bytes,3,opt,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty"`
	RemoteConfigStatus *RemoteConfigStatus    `protobuf:"bytes,4,opt,name=remote_config_status,json=remoteConfigStatus,proto3" json:"remote_config_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{7}
}

func (x *AgentStatus) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNKNOWN
}

func (x *AgentStatus) GetHealth() *ComponentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *AgentStatus) GetEffectiveConfig() *EffectiveConfig {
	if x != nil {
		return x.EffectiveConfig
	}
	return nil
}

func (x *AgentStatus) GetRemoteConfigStatus() *RemoteConfigStatus {
	if x != nil {
		return x.RemoteConfigStatus
	}
	return nil
}

type AgentDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName  string                 `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDescription) Reset() {
	*x = AgentDescription{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescription) ProtoMessage() {}

func (x *AgentDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescription.ProtoReflect.Descriptor instead.
func (*AgentDescription) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{8}
}

func (x *AgentDescription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDescription) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

// ComponentHealth represents the health status of an agent and its components.
type ComponentHealth struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Healthy            bool                        `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	StartTimeUnixNano  uint64                      `protobuf:"varint,2,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	LastError          string                      `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Status             string                      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StatusTimeUnixNano uint64                      `protobuf:"varint,5,opt,name=status_time_unix_nano,json=statusTimeUnixNano,proto3" json:"status_time_unix_nano,omitempty"`
	ComponentHealthMap map[string]*ComponentHealth `protobuf:"bytes,6,rep,name=component_health_map,json=componentHealthMap,proto3" json:"component_health_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{9}
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *ComponentHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetStatusTimeUnixNano() uint64 {
	if x != nil {
		return x.StatusTimeUnixNano
	}
	return 0
}

func (x *ComponentHealth) GetComponentHealthMap() map[string]*ComponentHealth {
	if x != nil {
		return x.ComponentHealthMap
	}
	return nil
}

// EffectiveConfig represents the current effective configuration of an agent.
type EffectiveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigMap     *AgentConfigMap        `protobuf:"bytes,1,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveConfig) Reset() {
	*x = EffectiveConfig{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveConfig) ProtoMessage() {}

func (x *EffectiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveConfig.ProtoReflect.Descriptor instead.
func (*EffectiveConfig) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{10}
}

func (x *EffectiveConfig) GetConfigMap() *AgentConfigMap {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

// AgentConfigMap holds a map of config file names to their content.
type AgentConfigMap struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ConfigMap     map[string]*AgentConfigFile `protobuf:"bytes,1,rep,name=config_map,json=configMap,proto3" json:"config_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigMap) Reset() {
	*x = AgentConfigMap{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigMap) ProtoMessage() {}

func (x *AgentConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigMap.ProtoReflect.Descriptor instead.
func (*AgentConfigMap) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{11}
}

func (x *AgentConfigMap) GetConfigMap() map[string]*AgentConfigFile {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

// AgentConfigFile represents a single configuration file.
type AgentConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigFile) Reset() {
	*x = AgentConfigFile{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigFile) ProtoMessage() {}

func (x *AgentConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigFile.ProtoReflect.Descriptor instead.
func (*AgentConfigFile) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{12}
}

func (x *AgentConfigFile) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentConfigFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// RemoteConfigStatus represents the status of a remote configuration on an agent.
type RemoteConfigStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LastRemoteConfigHash []byte                 `protobuf:"bytes,1,opt,name=last_remote_config_hash,json=lastRemoteConfigHash,proto3" json:"last_remote_config_hash,omitempty"`
	Status               RemoteConfigStatuses   `protobuf:"varint,2,opt,name=status,proto3,enum=config.v1alpha1.RemoteConfigStatuses" json:"status,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoteConfigStatus) Reset() {
	*x = RemoteConfigStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteConfigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfigStatus) ProtoMessage() {}

func (x *RemoteConfigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfigStatus.ProtoReflect.Descriptor instead.
func (*RemoteConfigStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{13}
}

func (x *RemoteConfigStatus) GetLastRemoteConfigHash() []byte {
	if x != nil {
		return x.LastRemoteConfigHash
	}
	return nil
}

func (x *RemoteConfigStatus) GetStatus() RemoteConfigStatuses {
	if x != nil {
		return x.Status
	}
	return RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_UNSET
}

func (x *RemoteConfigStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_api_agents_v1alpha1_agents_proto protoreflect.FileDescriptor

const file_pkg_api_agents_v1alpha1_agents_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/agents/v1alpha1/agents.proto\x12\x0fconfig.v1alpha1\"4\n" +
	"\x11ListAgentsRequest\x12\x1f\n" +
	"\vwith_status\x18\x01 \x01(\bR\n" +
	"withStatus\"X\n" +
	"\x12ListAgentsResponse\x12B\n" +
	"\x06agents\x18\x01 \x03(\v2*.config.v1alpha1.AgentDescriptionAndStatusR\x06agents\"\x8a\x01\n" +
	"\x19AgentDescriptionAndStatus\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.config.v1alpha1.AgentDescriptionR\x05agent\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1c.config.v1alpha1.AgentStatusR\x06status\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"K\n" +
	"\x10GetAgentResponse\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.config.v1alpha1.AgentDescriptionR\x05agent\"2\n" +
	"\x15GetAgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"N\n" +
	"\x16GetAgentStatusResponse\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x1c.config.v1alpha1.AgentStatusR\x06status\"\x9e\x02\n" +
	"\vAgentStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.config.v1alpha1.AgentStateR\x05state\x128\n" +
	"\x06health\x18\x02 \x01(\v2 .config.v1alpha1.ComponentHealthR\x06health\x12K\n" +
	"\x10effective_config\x18\x03 \x01(\v2 .config.v1alpha1.EffectiveConfigR\x0feffectiveConfig\x12U\n" +
	"\x14remote_config_status\x18\x04 \x01(\v2#.config.v1alpha1.RemoteConfigStatusR\x12remoteConfigStatus\"G\n" +
	"\x10AgentDescription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfriendly_name\x18\x02 \x01(\tR\ffriendlyName\"\x9b\x03\n" +
	"\x0fComponentHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12/\n" +
	"\x14start_time_unix_nano\x18\x02 \x01(\x04R\x11startTimeUnixNano\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x121\n" +
	"\x15status_time_unix_nano\x18\x05 \x01(\x04R\x12statusTimeUnixNano\x12j\n" +
	"\x14component_health_map\x18\x06 \x03(\v28.config.v1alpha1.ComponentHealth.ComponentHealthMapEntryR\x12componentHealthMap\x1ag\n" +
	"\x17ComponentHealthMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .config.v1alpha1.ComponentHealthR\x05value:\x028\x01\"Q\n" +
	"\x0fEffectiveConfig\x12>\n" +
	"\n" +
	"config_map\x18\x01 \x01(\v2\x1f.config.v1alpha1.AgentConfigMapR\tconfigMap\"\xbf\x01\n" +
	"\x0eAgentConfigMap\x12M\n" +
	"\n" +
	"config_map\x18\x01 \x03(\v2..config.v1alpha1.AgentConfigMap.ConfigMapEntryR\tconfigMap\x1a^\n" +
	"\x0eConfigMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .config.v1alpha1.AgentConfigFileR\x05value:\x028\x01\"H\n" +
	"\x0fAgentConfigFile\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xaf\x01\n" +
	"\x12RemoteConfigStatus\x125\n" +
	"\x17last_remote_config_hash\x18\x01 \x01(\fR\x14lastRemoteConfigHash\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.config.v1alpha1.RemoteConfigStatusesR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*^\n" +
	"\n" +
	"AgentState\x12\x17\n" +
	"\x13AGENT_STATE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15AGENT_STATE_CONNECTED\x10\x01\x12\x1c\n" +
	"\x18AGENT_STATE_DISCONNECTED\x10\x02*\xa4\x01\n" +
	"\x14RemoteConfigStatuses\x12 \n" +
	"\x1cREMOTE_CONFIG_STATUSES_UNSET\x10\x00\x12\"\n" +
	"\x1eREMOTE_CONFIG_STATUSES_APPLIED\x10\x01\x12#\n" +
	"\x1fREMOTE_CONFIG_STATUSES_APPLYING\x10\x02\x12!\n" +
	"\x1dREMOTE_CONFIG_STATUSES_FAILED\x10\x032\x91\x02\n" +
	"\fAgentService\x12U\n" +
	"\n" +
	"ListAgents\x12\".config.v1alpha1.ListAgentsRequest\x1a#.config.v1alpha1.ListAgentsResponse\x12O\n" +
	"\bGetAgent\x12 .config.v1alpha1.GetAgentRequest\x1a!.config.v1alpha1.GetAgentResponse\x12Y\n" +
	"\x06Status\x12&.config.v1alpha1.GetAgentStatusRequest\x1a'.config.v1alpha1.GetAgentStatusResponseB8Z6github.com/otelfleet/otelfleet/pkg/api/agents/v1alpha1b\x06proto3"

var (
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescOnce sync.Once
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescData []byte
)

func file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP() []byte {
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescOnce.Do(func() {
		file_pkg_api_agents_v1alpha1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc), len(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc)))
	})
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescData
}

var file_pkg_api_agents_v1alpha1_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_agents_v1alpha1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_api_agents_v1alpha1_agents_proto_goTypes = []any{
	(AgentState)(0),                   // 0: config.v1alpha1.AgentState
	(RemoteConfigStatuses)(0),         // 1: config.v1alpha1.RemoteConfigStatuses
	(*ListAgentsRequest)(nil),         // 2: config.v1alpha1.ListAgentsRequest
	(*ListAgentsResponse)(nil),        // 3: config.v1alpha1.ListAgentsResponse
	(*AgentDescriptionAndStatus)(nil), // 4: config.v1alpha1.AgentDescriptionAndStatus
	(*GetAgentRequest)(nil),           // 5: config.v1alpha1.GetAgentRequest
	(*GetAgentResponse)(nil),          // 6: config.v1alpha1.GetAgentResponse
	(*GetAgentStatusRequest)(nil),     // 7: config.v1alpha1.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil),    // 8: config.v1alpha1.GetAgentStatusResponse
	(*AgentStatus)(nil),               // 9: config.v1alpha1.AgentStatus
	(*AgentDescription)(nil),          // 10: config.v1alpha1.AgentDescription
	(*ComponentHealth)(nil),           // 11: config.v1alpha1.ComponentHealth
	(*EffectiveConfig)(nil),           // 12: config.v1alpha1.EffectiveConfig
	(*AgentConfigMap)(nil),            // 13: config.v1alpha1.AgentConfigMap
	(*AgentConfigFile)(nil),           // 14: config.v1alpha1.AgentConfigFile
	(*RemoteConfigStatus)(nil),        // 15: config.v1alpha1.RemoteConfigStatus
	nil,                               // 16: config.v1alpha1.ComponentHealth.ComponentHealthMapEntry
	nil,                               // 17: config.v1alpha1.AgentConfigMap.ConfigMapEntry
}
var file_pkg_api_agents_v1alpha1_agents_proto_depIdxs = []int32{
	4,  // 0: config.v1alpha1.ListAgentsResponse.agents:type_name -> config.v1alpha1.AgentDescriptionAndStatus
	10, // 1: config.v1alpha1.AgentDescriptionAndStatus.agent:type_name -> config.v1alpha1.AgentDescription
	9,  // 2: config.v1alpha1.AgentDescriptionAndStatus.status:type_name -> config.v1alpha1.AgentStatus
	10, // 3: config.v1alpha1.GetAgentResponse.agent:type_name -> config.v1alpha1.AgentDescription
	9,  // 4: config.v1alpha1.GetAgentStatusResponse.status:type_name -> config.v1alpha1.AgentStatus
	0,  // 5: config.v1alpha1.AgentStatus.state:type_name -> config.v1alpha1.AgentState
	11, // 6: config.v1alpha1.AgentStatus.health:type_name -> config.v1alpha1.ComponentHealth
	12, // 7: config.v1alpha1.AgentStatus.effective_config:type_name -> config.v1alpha1.EffectiveConfig
	15, // 8: config.v1alpha1.AgentStatus.remote_config_status:type_name -> config.v1alpha1.RemoteConfigStatus
	16, // 9: config.v1alpha1.ComponentHealth.component_health_map:type_name -> config.v1alpha1.ComponentHealth.ComponentHealthMapEntry
	13, // 10: config.v1alpha1.EffectiveConfig.config_map:type_name -> config.v1alpha1.AgentConfigMap
	17, // 11: config.v1alpha1.AgentConfigMap.config_map:type_name -> config.v1alpha1.AgentConfigMap.ConfigMapEntry
	1,  // 12: config.v1alpha1.RemoteConfigStatus.status:type_name -> config.v1alpha1.RemoteConfigStatuses
	11, // 13: config.v1alpha1.ComponentHealth.ComponentHealthMapEntry.value:type_name -> config.v1alpha1.ComponentHealth
	14, // 14: config.v1alpha1.AgentConfigMap.ConfigMapEntry.value:type_name -> config.v1alpha1.AgentConfigFile
	2,  // 15: config.v1alpha1.AgentService.ListAgents:input_type -> config.v1alpha1.ListAgentsRequest
	5,  // 16: config.v1alpha1.AgentService.GetAgent:input_type -> config.v1alpha1.GetAgentRequest
	7,  // 17: config.v1alpha1.AgentService.Status:input_type -> config.v1alpha1.GetAgentStatusRequest
	3,  // 18: config.v1alpha1.AgentService.ListAgents:output_type -> config.v1alpha1.ListAgentsResponse
	6,  // 19: config.v1alpha1.AgentService.GetAgent:output_type -> config.v1alpha1.GetAgentResponse
	8,  // 20: config.v1alpha1.AgentService.Status:output_type -> config.v1alpha1.GetAgentStatusResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_api_agents_v1alpha1_agents_proto_init() }
func file_pkg_api_agents_v1alpha1_agents_proto_init() {
	if File_pkg_api_agents_v1alpha1_agents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc), len(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_agents_v1alpha1_agents_proto_goTypes,
		DependencyIndexes: file_pkg_api_agents_v1alpha1_agents_proto_depIdxs,
		EnumInfos:         file_pkg_api_agents_v1alpha1_agents_proto_enumTypes,
		MessageInfos:      file_pkg_api_agents_v1alpha1_agents_proto_msgTypes,
	}.Build()
	File_pkg_api_agents_v1alpha1_agents_proto = out.File
	file_pkg_api_agents_v1alpha1_agents_proto_goTypes = nil
	file_pkg_api_agents_v1alpha1_agents_proto_depIdxs = nil
}
