// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pkg/api/agents/v1alpha1/agents.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState int32

const (
	AgentState_AgentStateUnknown      AgentState = 0
	AgentState_AgentStateConnected    AgentState = 1
	AgentState_AgentStateDisconnected AgentState = 2
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AgentStateUnknown",
		1: "AgentStateConnected",
		2: "AgentStateDisconnected",
	}
	AgentState_value = map[string]int32{
		"AgentStateUnknown":      0,
		"AgentStateConnected":    1,
		"AgentStateDisconnected": 2,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_pkg_api_agents_v1alpha1_agents_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{0}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithStatus    bool                   `protobuf:"varint,1,opt,name=withStatus,proto3" json:"withStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetWithStatus() bool {
	if x != nil {
		return x.WithStatus
	}
	return false
}

type ListAgentsReponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Agents        []*AgentDescriptionAndStatus `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsReponse) Reset() {
	*x = ListAgentsReponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsReponse) ProtoMessage() {}

func (x *ListAgentsReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsReponse.ProtoReflect.Descriptor instead.
func (*ListAgentsReponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsReponse) GetAgents() []*AgentDescriptionAndStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentDescriptionAndStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescription      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDescriptionAndStatus) Reset() {
	*x = AgentDescriptionAndStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescriptionAndStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescriptionAndStatus) ProtoMessage() {}

func (x *AgentDescriptionAndStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescriptionAndStatus.ProtoReflect.Descriptor instead.
func (*AgentDescriptionAndStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *AgentDescriptionAndStatus) GetAgent() *AgentDescription {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AgentDescriptionAndStatus) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{3}
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{4}
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{5}
}

type AgentDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName  string                 `protobuf:"bytes,2,opt,name=friendlyName,proto3" json:"friendlyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDescription) Reset() {
	*x = AgentDescription{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescription) ProtoMessage() {}

func (x *AgentDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescription.ProtoReflect.Descriptor instead.
func (*AgentDescription) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *AgentDescription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDescription) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         AgentState             `protobuf:"varint,1,opt,name=state,proto3,enum=config.v1alpha1.AgentState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agents_v1alpha1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP(), []int{7}
}

func (x *AgentStatus) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AgentStateUnknown
}

var File_pkg_api_agents_v1alpha1_agents_proto protoreflect.FileDescriptor

const file_pkg_api_agents_v1alpha1_agents_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/agents/v1alpha1/agents.proto\x12\x0fconfig.v1alpha1\"3\n" +
	"\x11ListAgentsRequest\x12\x1e\n" +
	"\n" +
	"withStatus\x18\x01 \x01(\bR\n" +
	"withStatus\"W\n" +
	"\x11ListAgentsReponse\x12B\n" +
	"\x06agents\x18\x01 \x03(\v2*.config.v1alpha1.AgentDescriptionAndStatusR\x06agents\"\x8a\x01\n" +
	"\x19AgentDescriptionAndStatus\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.config.v1alpha1.AgentDescriptionR\x05agent\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1c.config.v1alpha1.AgentStatusR\x06status\"\x11\n" +
	"\x0fGetAgentRequest\"\x12\n" +
	"\x10GetAgentResponse\"\x17\n" +
	"\x15GetAgentStatusRequest\"F\n" +
	"\x10AgentDescription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\ffriendlyName\x18\x02 \x01(\tR\ffriendlyName\"@\n" +
	"\vAgentStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.config.v1alpha1.AgentStateR\x05state*X\n" +
	"\n" +
	"AgentState\x12\x15\n" +
	"\x11AgentStateUnknown\x10\x00\x12\x17\n" +
	"\x13AgentStateConnected\x10\x01\x12\x1a\n" +
	"\x16AgentStateDisconnected\x10\x022\x85\x02\n" +
	"\fAgentService\x12T\n" +
	"\n" +
	"ListAgents\x12\".config.v1alpha1.ListAgentsRequest\x1a\".config.v1alpha1.ListAgentsReponse\x12O\n" +
	"\bGetAgent\x12 .config.v1alpha1.GetAgentRequest\x1a!.config.v1alpha1.GetAgentResponse\x12N\n" +
	"\x06Status\x12&.config.v1alpha1.GetAgentStatusRequest\x1a\x1c.config.v1alpha1.AgentStatusB8Z6github.com/otelfleet/otelfleet/pkg/api/agents/v1alpha1b\x06proto3"

var (
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescOnce sync.Once
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescData []byte
)

func file_pkg_api_agents_v1alpha1_agents_proto_rawDescGZIP() []byte {
	file_pkg_api_agents_v1alpha1_agents_proto_rawDescOnce.Do(func() {
		file_pkg_api_agents_v1alpha1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc), len(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc)))
	})
	return file_pkg_api_agents_v1alpha1_agents_proto_rawDescData
}

var file_pkg_api_agents_v1alpha1_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_agents_v1alpha1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_api_agents_v1alpha1_agents_proto_goTypes = []any{
	(AgentState)(0),                   // 0: config.v1alpha1.AgentState
	(*ListAgentsRequest)(nil),         // 1: config.v1alpha1.ListAgentsRequest
	(*ListAgentsReponse)(nil),         // 2: config.v1alpha1.ListAgentsReponse
	(*AgentDescriptionAndStatus)(nil), // 3: config.v1alpha1.AgentDescriptionAndStatus
	(*GetAgentRequest)(nil),           // 4: config.v1alpha1.GetAgentRequest
	(*GetAgentResponse)(nil),          // 5: config.v1alpha1.GetAgentResponse
	(*GetAgentStatusRequest)(nil),     // 6: config.v1alpha1.GetAgentStatusRequest
	(*AgentDescription)(nil),          // 7: config.v1alpha1.AgentDescription
	(*AgentStatus)(nil),               // 8: config.v1alpha1.AgentStatus
}
var file_pkg_api_agents_v1alpha1_agents_proto_depIdxs = []int32{
	3, // 0: config.v1alpha1.ListAgentsReponse.agents:type_name -> config.v1alpha1.AgentDescriptionAndStatus
	7, // 1: config.v1alpha1.AgentDescriptionAndStatus.agent:type_name -> config.v1alpha1.AgentDescription
	8, // 2: config.v1alpha1.AgentDescriptionAndStatus.status:type_name -> config.v1alpha1.AgentStatus
	0, // 3: config.v1alpha1.AgentStatus.state:type_name -> config.v1alpha1.AgentState
	1, // 4: config.v1alpha1.AgentService.ListAgents:input_type -> config.v1alpha1.ListAgentsRequest
	4, // 5: config.v1alpha1.AgentService.GetAgent:input_type -> config.v1alpha1.GetAgentRequest
	6, // 6: config.v1alpha1.AgentService.Status:input_type -> config.v1alpha1.GetAgentStatusRequest
	2, // 7: config.v1alpha1.AgentService.ListAgents:output_type -> config.v1alpha1.ListAgentsReponse
	5, // 8: config.v1alpha1.AgentService.GetAgent:output_type -> config.v1alpha1.GetAgentResponse
	8, // 9: config.v1alpha1.AgentService.Status:output_type -> config.v1alpha1.AgentStatus
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_agents_v1alpha1_agents_proto_init() }
func file_pkg_api_agents_v1alpha1_agents_proto_init() {
	if File_pkg_api_agents_v1alpha1_agents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc), len(file_pkg_api_agents_v1alpha1_agents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_agents_v1alpha1_agents_proto_goTypes,
		DependencyIndexes: file_pkg_api_agents_v1alpha1_agents_proto_depIdxs,
		EnumInfos:         file_pkg_api_agents_v1alpha1_agents_proto_enumTypes,
		MessageInfos:      file_pkg_api_agents_v1alpha1_agents_proto_msgTypes,
	}.Build()
	File_pkg_api_agents_v1alpha1_agents_proto = out.File
	file_pkg_api_agents_v1alpha1_agents_proto_goTypes = nil
	file_pkg_api_agents_v1alpha1_agents_proto_depIdxs = nil
}
