// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/deployment/v1alpha1/deployment.proto

package v1alpha1

import (
	_ "github.com/otelfleet/otelfleet/pkg/api/resources/v1alpha1"
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/route/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorState int32

const (
	CollectorState_COLLECTOR_STATE_UNKNOWN      CollectorState = 0
	CollectorState_COLLECTOR_STATE_CONNECTED    CollectorState = 1
	CollectorState_COLLECTOR_STATE_DISCONNECTED CollectorState = 2
)

// Enum value maps for CollectorState.
var (
	CollectorState_name = map[int32]string{
		0: "COLLECTOR_STATE_UNKNOWN",
		1: "COLLECTOR_STATE_CONNECTED",
		2: "COLLECTOR_STATE_DISCONNECTED",
	}
	CollectorState_value = map[string]int32{
		"COLLECTOR_STATE_UNKNOWN":      0,
		"COLLECTOR_STATE_CONNECTED":    1,
		"COLLECTOR_STATE_DISCONNECTED": 2,
	}
)

func (x CollectorState) Enum() *CollectorState {
	p := new(CollectorState)
	*p = x
	return p
}

func (x CollectorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectorState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes[0].Descriptor()
}

func (CollectorState) Type() protoreflect.EnumType {
	return &file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes[0]
}

func (x CollectorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectorState.Descriptor instead.
func (CollectorState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{0}
}

// Server-computed by comparing the assigned config hash with the collector-reported hash.
type ConfigSyncStatus int32

const (
	ConfigSyncStatus_CONFIG_SYNC_STATUS_UNKNOWN     ConfigSyncStatus = 0
	ConfigSyncStatus_CONFIG_SYNC_STATUS_IN_SYNC     ConfigSyncStatus = 1
	ConfigSyncStatus_CONFIG_SYNC_STATUS_OUT_OF_SYNC ConfigSyncStatus = 2
	ConfigSyncStatus_CONFIG_SYNC_STATUS_APPLYING    ConfigSyncStatus = 3
	ConfigSyncStatus_CONFIG_SYNC_STATUS_ERROR       ConfigSyncStatus = 4
)

// Enum value maps for ConfigSyncStatus.
var (
	ConfigSyncStatus_name = map[int32]string{
		0: "CONFIG_SYNC_STATUS_UNKNOWN",
		1: "CONFIG_SYNC_STATUS_IN_SYNC",
		2: "CONFIG_SYNC_STATUS_OUT_OF_SYNC",
		3: "CONFIG_SYNC_STATUS_APPLYING",
		4: "CONFIG_SYNC_STATUS_ERROR",
	}
	ConfigSyncStatus_value = map[string]int32{
		"CONFIG_SYNC_STATUS_UNKNOWN":     0,
		"CONFIG_SYNC_STATUS_IN_SYNC":     1,
		"CONFIG_SYNC_STATUS_OUT_OF_SYNC": 2,
		"CONFIG_SYNC_STATUS_APPLYING":    3,
		"CONFIG_SYNC_STATUS_ERROR":       4,
	}
)

func (x ConfigSyncStatus) Enum() *ConfigSyncStatus {
	p := new(ConfigSyncStatus)
	*p = x
	return p
}

func (x ConfigSyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigSyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes[1].Descriptor()
}

func (ConfigSyncStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes[1]
}

func (x ConfigSyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigSyncStatus.Descriptor instead.
func (ConfigSyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{1}
}

type RemoteConfigStatuses int32

const (
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_UNSET    RemoteConfigStatuses = 0
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_APPLIED  RemoteConfigStatuses = 1
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_APPLYING RemoteConfigStatuses = 2
	RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_FAILED   RemoteConfigStatuses = 3
)

// Enum value maps for RemoteConfigStatuses.
var (
	RemoteConfigStatuses_name = map[int32]string{
		0: "REMOTE_CONFIG_STATUSES_UNSET",
		1: "REMOTE_CONFIG_STATUSES_APPLIED",
		2: "REMOTE_CONFIG_STATUSES_APPLYING",
		3: "REMOTE_CONFIG_STATUSES_FAILED",
	}
	RemoteConfigStatuses_value = map[string]int32{
		"REMOTE_CONFIG_STATUSES_UNSET":    0,
		"REMOTE_CONFIG_STATUSES_APPLIED":  1,
		"REMOTE_CONFIG_STATUSES_APPLYING": 2,
		"REMOTE_CONFIG_STATUSES_FAILED":   3,
	}
)

func (x RemoteConfigStatuses) Enum() *RemoteConfigStatuses {
	p := new(RemoteConfigStatuses)
	*p = x
	return p
}

func (x RemoteConfigStatuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteConfigStatuses) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes[2].Descriptor()
}

func (RemoteConfigStatuses) Type() protoreflect.EnumType {
	return &file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes[2]
}

func (x RemoteConfigStatuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteConfigStatuses.Descriptor instead.
func (RemoteConfigStatuses) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{2}
}

type ValidateRouterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Router        *v1alpha1.Router       `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRouterRequest) Reset() {
	*x = ValidateRouterRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRouterRequest) ProtoMessage() {}

func (x *ValidateRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRouterRequest.ProtoReflect.Descriptor instead.
func (*ValidateRouterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRouterRequest) GetRouter() *v1alpha1.Router {
	if x != nil {
		return x.Router
	}
	return nil
}

type ValidateRouterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRouterResponse) Reset() {
	*x = ValidateRouterResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRouterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRouterResponse) ProtoMessage() {}

func (x *ValidateRouterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRouterResponse.ProtoReflect.Descriptor instead.
func (*ValidateRouterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{1}
}

type PreviewRouterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Router        *v1alpha1.Router       `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRouterRequest) Reset() {
	*x = PreviewRouterRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRouterRequest) ProtoMessage() {}

func (x *PreviewRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRouterRequest.ProtoReflect.Descriptor instead.
func (*PreviewRouterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewRouterRequest) GetRouter() *v1alpha1.Router {
	if x != nil {
		return x.Router
	}
	return nil
}

type PreviewRouterResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Old           *RouterConfigAssignment `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New           *RouterConfigAssignment `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRouterResponse) Reset() {
	*x = PreviewRouterResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRouterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRouterResponse) ProtoMessage() {}

func (x *PreviewRouterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRouterResponse.ProtoReflect.Descriptor instead.
func (*PreviewRouterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewRouterResponse) GetOld() *RouterConfigAssignment {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *PreviewRouterResponse) GetNew() *RouterConfigAssignment {
	if x != nil {
		return x.New
	}
	return nil
}

type RouterConfigAssignment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollectorsToConfigRef map[string]string      `protobuf:"bytes,1,rep,name=collectorsToConfigRef,proto3" json:"collectorsToConfigRef,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RouterConfigAssignment) Reset() {
	*x = RouterConfigAssignment{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterConfigAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterConfigAssignment) ProtoMessage() {}

func (x *RouterConfigAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterConfigAssignment.ProtoReflect.Descriptor instead.
func (*RouterConfigAssignment) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *RouterConfigAssignment) GetCollectorsToConfigRef() map[string]string {
	if x != nil {
		return x.CollectorsToConfigRef
	}
	return nil
}

type MatchRouterRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Router               *v1alpha1.Router       `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	IdentifyingLabels    map[string]string      `protobuf:"bytes,2,rep,name=identifying_labels,json=identifyingLabels,proto3" json:"identifying_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NonIdentifyingLabels map[string]string      `protobuf:"bytes,3,rep,name=non_identifying_labels,json=nonIdentifyingLabels,proto3" json:"non_identifying_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OtelfleetLabels      map[string]string      `protobuf:"bytes,4,rep,name=otelfleet_labels,json=otelfleetLabels,proto3" json:"otelfleet_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MatchRouterRequest) Reset() {
	*x = MatchRouterRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRouterRequest) ProtoMessage() {}

func (x *MatchRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRouterRequest.ProtoReflect.Descriptor instead.
func (*MatchRouterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *MatchRouterRequest) GetRouter() *v1alpha1.Router {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *MatchRouterRequest) GetIdentifyingLabels() map[string]string {
	if x != nil {
		return x.IdentifyingLabels
	}
	return nil
}

func (x *MatchRouterRequest) GetNonIdentifyingLabels() map[string]string {
	if x != nil {
		return x.NonIdentifyingLabels
	}
	return nil
}

func (x *MatchRouterRequest) GetOtelfleetLabels() map[string]string {
	if x != nil {
		return x.OtelfleetLabels
	}
	return nil
}

type MatchRouterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names of the routes traversed, from the root to the matched route.
	RoutePath []string `protobuf:"bytes,1,rep,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	// Index of each traversed route in its parent's routes, from the root down.
	RouteIndexPath []uint32 `protobuf:"varint,2,rep,packed,name=route_index_path,json=routeIndexPath,proto3" json:"route_index_path,omitempty"`
	ConfigRef      string   `protobuf:"bytes,3,opt,name=config_ref,json=configRef,proto3" json:"config_ref,omitempty"`
	// False when no route matched and config_ref is the router default.
	Matched       bool `protobuf:"varint,4,opt,name=matched,proto3" json:"matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRouterResponse) Reset() {
	*x = MatchRouterResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRouterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRouterResponse) ProtoMessage() {}

func (x *MatchRouterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRouterResponse.ProtoReflect.Descriptor instead.
func (*MatchRouterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{6}
}

func (x *MatchRouterResponse) GetRoutePath() []string {
	if x != nil {
		return x.RoutePath
	}
	return nil
}

func (x *MatchRouterResponse) GetRouteIndexPath() []uint32 {
	if x != nil {
		return x.RouteIndexPath
	}
	return nil
}

func (x *MatchRouterResponse) GetConfigRef() string {
	if x != nil {
		return x.ConfigRef
	}
	return ""
}

func (x *MatchRouterResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

type GetCollectorHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorHistoryRequest) Reset() {
	*x = GetCollectorHistoryRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorHistoryRequest) ProtoMessage() {}

func (x *GetCollectorHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetCollectorHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCollectorHistoryRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *GetCollectorHistoryRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetCollectorHistoryRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCollectorHistoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EffectiveConfig []*EffectiveConfig     `protobuf:"bytes,1,rep,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCollectorHistoryResponse) Reset() {
	*x = GetCollectorHistoryResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorHistoryResponse) ProtoMessage() {}

func (x *GetCollectorHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetCollectorHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{8}
}

func (x *GetCollectorHistoryResponse) GetEffectiveConfig() []*EffectiveConfig {
	if x != nil {
		return x.EffectiveConfig
	}
	return nil
}

type ListCollectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithStatus    bool                   `protobuf:"varint,1,opt,name=with_status,json=withStatus,proto3" json:"with_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectorsRequest) Reset() {
	*x = ListCollectorsRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectorsRequest) ProtoMessage() {}

func (x *ListCollectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectorsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectorsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{9}
}

func (x *ListCollectorsRequest) GetWithStatus() bool {
	if x != nil {
		return x.WithStatus
	}
	return false
}

type ListCollectorsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Collectors    []*CollectorDescriptionAndStatus `protobuf:"bytes,1,rep,name=collectors,proto3" json:"collectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectorsResponse) Reset() {
	*x = ListCollectorsResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectorsResponse) ProtoMessage() {}

func (x *ListCollectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectorsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectorsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{10}
}

func (x *ListCollectorsResponse) GetCollectors() []*CollectorDescriptionAndStatus {
	if x != nil {
		return x.Collectors
	}
	return nil
}

type CollectorView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *CollectorRegistration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	Status        *CollectorStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorView) Reset() {
	*x = CollectorView{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorView) ProtoMessage() {}

func (x *CollectorView) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorView.ProtoReflect.Descriptor instead.
func (*CollectorView) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{11}
}

func (x *CollectorView) GetRegistration() *CollectorRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *CollectorView) GetStatus() *CollectorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Deprecated: use CollectorView.
type CollectorDescriptionAndStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collector     *CollectorDescription  `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	Status        *CollectorStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorDescriptionAndStatus) Reset() {
	*x = CollectorDescriptionAndStatus{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorDescriptionAndStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorDescriptionAndStatus) ProtoMessage() {}

func (x *CollectorDescriptionAndStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorDescriptionAndStatus.ProtoReflect.Descriptor instead.
func (*CollectorDescriptionAndStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{12}
}

func (x *CollectorDescriptionAndStatus) GetCollector() *CollectorDescription {
	if x != nil {
		return x.Collector
	}
	return nil
}

func (x *CollectorDescriptionAndStatus) GetStatus() *CollectorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetCollectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorRequest) Reset() {
	*x = GetCollectorRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorRequest) ProtoMessage() {}

func (x *GetCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorRequest.ProtoReflect.Descriptor instead.
func (*GetCollectorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{13}
}

func (x *GetCollectorRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type GetCollectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collector     *CollectorDescription  `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorResponse) Reset() {
	*x = GetCollectorResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorResponse) ProtoMessage() {}

func (x *GetCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorResponse.ProtoReflect.Descriptor instead.
func (*GetCollectorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{14}
}

func (x *GetCollectorResponse) GetCollector() *CollectorDescription {
	if x != nil {
		return x.Collector
	}
	return nil
}

type GetCollectorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorStatusRequest) Reset() {
	*x = GetCollectorStatusRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorStatusRequest) ProtoMessage() {}

func (x *GetCollectorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCollectorStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{15}
}

func (x *GetCollectorStatusRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type GetCollectorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *CollectorStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectorStatusResponse) Reset() {
	*x = GetCollectorStatusResponse{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectorStatusResponse) ProtoMessage() {}

func (x *GetCollectorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectorStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCollectorStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{16}
}

func (x *GetCollectorStatusResponse) GetStatus() *CollectorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteCollectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectorRequest) Reset() {
	*x = DeleteCollectorRequest{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectorRequest) ProtoMessage() {}

func (x *DeleteCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCollectorRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type CollectorStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Health             *ComponentHealth       `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	EffectiveConfig    *EffectiveConfig       `protobuf:"bytes,2,opt,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty"`
	RemoteConfigStatus *RemoteConfigStatus    `protobuf:"bytes,3,opt,name=remote_config_status,json=remoteConfigStatus,proto3" json:"remote_config_status,omitempty"`
	ConnStatus         *ConnectionStatus      `protobuf:"bytes,4,opt,name=conn_status,json=connStatus,proto3" json:"conn_status,omitempty"`
	SyncStatus         *SyncStatus            `protobuf:"bytes,5,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CollectorStatus) Reset() {
	*x = CollectorStatus{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorStatus) ProtoMessage() {}

func (x *CollectorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorStatus.ProtoReflect.Descriptor instead.
func (*CollectorStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{18}
}

func (x *CollectorStatus) GetHealth() *ComponentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *CollectorStatus) GetEffectiveConfig() *EffectiveConfig {
	if x != nil {
		return x.EffectiveConfig
	}
	return nil
}

func (x *CollectorStatus) GetRemoteConfigStatus() *RemoteConfigStatus {
	if x != nil {
		return x.RemoteConfigStatus
	}
	return nil
}

func (x *CollectorStatus) GetConnStatus() *ConnectionStatus {
	if x != nil {
		return x.ConnStatus
	}
	return nil
}

func (x *CollectorStatus) GetSyncStatus() *SyncStatus {
	if x != nil {
		return x.SyncStatus
	}
	return nil
}

type CollectorRegistration struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string                 `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	// Attributes that identify the collector (e.g., service.name, service.version, service.instance.id).
	IdentifyingAttributes []*KeyValue `protobuf:"bytes,3,rep,name=identifying_attributes,json=identifyingAttributes,proto3" json:"identifying_attributes,omitempty"`
	// Attributes that do not necessarily identify the collector but help describe where it runs.
	NonIdentifyingAttributes []*KeyValue `protobuf:"bytes,4,rep,name=non_identifying_attributes,json=nonIdentifyingAttributes,proto3" json:"non_identifying_attributes,omitempty"`
	Capabilities             []string    `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CollectorRegistration) Reset() {
	*x = CollectorRegistration{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorRegistration) ProtoMessage() {}

func (x *CollectorRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorRegistration.ProtoReflect.Descriptor instead.
func (*CollectorRegistration) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{19}
}

func (x *CollectorRegistration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectorRegistration) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *CollectorRegistration) GetIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.IdentifyingAttributes
	}
	return nil
}

func (x *CollectorRegistration) GetNonIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.NonIdentifyingAttributes
	}
	return nil
}

func (x *CollectorRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Deprecated: use CollectorRegistration.
type CollectorDescription struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string                 `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	// Attributes that identify the collector (e.g., service.name, service.version, service.instance.id).
	IdentifyingAttributes []*KeyValue `protobuf:"bytes,3,rep,name=identifying_attributes,json=identifyingAttributes,proto3" json:"identifying_attributes,omitempty"`
	// Attributes that do not necessarily identify the collector but help describe where it runs
	// (e.g., os.type, os.version, host.*, cloud.*).
	NonIdentifyingAttributes []*KeyValue `protobuf:"bytes,4,rep,name=non_identifying_attributes,json=nonIdentifyingAttributes,proto3" json:"non_identifying_attributes,omitempty"`
	Capabilities             []string    `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CollectorDescription) Reset() {
	*x = CollectorDescription{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorDescription) ProtoMessage() {}

func (x *CollectorDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorDescription.ProtoReflect.Descriptor instead.
func (*CollectorDescription) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{20}
}

func (x *CollectorDescription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectorDescription) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *CollectorDescription) GetIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.IdentifyingAttributes
	}
	return nil
}

func (x *CollectorDescription) GetNonIdentifyingAttributes() []*KeyValue {
	if x != nil {
		return x.NonIdentifyingAttributes
	}
	return nil
}

func (x *CollectorDescription) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *AnyValue              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{21}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *AnyValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type AnyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BoolValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_BytesValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_KvlistValue
	Value         isAnyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyValue) Reset() {
	*x = AnyValue{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyValue) ProtoMessage() {}

func (x *AnyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyValue.ProtoReflect.Descriptor instead.
func (*AnyValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{22}
}

func (x *AnyValue) GetValue() isAnyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnyValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AnyValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnyValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AnyValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *AnyValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *AnyValue) GetKvlistValue() *KeyValueList {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnyValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AnyValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AnyValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type AnyValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,6,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type AnyValue_KvlistValue struct {
	KvlistValue *KeyValueList `protobuf:"bytes,7,opt,name=kvlist_value,json=kvlistValue,proto3,oneof"`
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

func (*AnyValue_BoolValue) isAnyValue_Value() {}

func (*AnyValue_IntValue) isAnyValue_Value() {}

func (*AnyValue_DoubleValue) isAnyValue_Value() {}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

func (*AnyValue_ArrayValue) isAnyValue_Value() {}

func (*AnyValue_KvlistValue) isAnyValue_Value() {}

type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AnyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{23}
}

func (x *ArrayValue) GetValues() []*AnyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type KeyValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KeyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueList) Reset() {
	*x = KeyValueList{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueList) ProtoMessage() {}

func (x *KeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueList.ProtoReflect.Descriptor instead.
func (*KeyValueList) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{24}
}

func (x *KeyValueList) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type CollectorConnectionState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectorId    string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	State          CollectorState         `protobuf:"varint,2,opt,name=state,proto3,enum=deployment.v1alpha1.CollectorState" json:"state,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ConnectedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	InstanceUid    []byte                 `protobuf:"bytes,6,opt,name=instance_uid,json=instanceUid,proto3" json:"instance_uid,omitempty"`
	Capabilities   uint64                 `protobuf:"varint,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	SequenceNum    uint64                 `protobuf:"varint,8,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectorConnectionState) Reset() {
	*x = CollectorConnectionState{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorConnectionState) ProtoMessage() {}

func (x *CollectorConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorConnectionState.ProtoReflect.Descriptor instead.
func (*CollectorConnectionState) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{25}
}

func (x *CollectorConnectionState) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *CollectorConnectionState) GetState() CollectorState {
	if x != nil {
		return x.State
	}
	return CollectorState_COLLECTOR_STATE_UNKNOWN
}

func (x *CollectorConnectionState) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *CollectorConnectionState) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *CollectorConnectionState) GetDisconnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectedAt
	}
	return nil
}

func (x *CollectorConnectionState) GetInstanceUid() []byte {
	if x != nil {
		return x.InstanceUid
	}
	return nil
}

func (x *CollectorConnectionState) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *CollectorConnectionState) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type ComponentHealth struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Healthy            bool                        `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	StartTimeUnixNano  uint64                      `protobuf:"varint,2,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	LastError          string                      `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Status             string                      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StatusTimeUnixNano uint64                      `protobuf:"varint,5,opt,name=status_time_unix_nano,json=statusTimeUnixNano,proto3" json:"status_time_unix_nano,omitempty"`
	ComponentHealthMap map[string]*ComponentHealth `protobuf:"bytes,6,rep,name=component_health_map,json=componentHealthMap,proto3" json:"component_health_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{26}
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *ComponentHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetStatusTimeUnixNano() uint64 {
	if x != nil {
		return x.StatusTimeUnixNano
	}
	return 0
}

func (x *ComponentHealth) GetComponentHealthMap() map[string]*ComponentHealth {
	if x != nil {
		return x.ComponentHealthMap
	}
	return nil
}

type EffectiveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigMap     *CollectorConfigMap    `protobuf:"bytes,1,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveConfig) Reset() {
	*x = EffectiveConfig{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveConfig) ProtoMessage() {}

func (x *EffectiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveConfig.ProtoReflect.Descriptor instead.
func (*EffectiveConfig) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{27}
}

func (x *EffectiveConfig) GetConfigMap() *CollectorConfigMap {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

type CollectorConfigMap struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	ConfigMap     map[string]*CollectorConfigFile `protobuf:"bytes,1,rep,name=config_map,json=configMap,proto3" json:"config_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorConfigMap) Reset() {
	*x = CollectorConfigMap{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorConfigMap) ProtoMessage() {}

func (x *CollectorConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorConfigMap.ProtoReflect.Descriptor instead.
func (*CollectorConfigMap) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{28}
}

func (x *CollectorConfigMap) GetConfigMap() map[string]*CollectorConfigFile {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

type CollectorConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorConfigFile) Reset() {
	*x = CollectorConfigFile{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorConfigFile) ProtoMessage() {}

func (x *CollectorConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorConfigFile.ProtoReflect.Descriptor instead.
func (*CollectorConfigFile) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{29}
}

func (x *CollectorConfigFile) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CollectorConfigFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type RemoteConfigStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LastRemoteConfigHash []byte                 `protobuf:"bytes,1,opt,name=last_remote_config_hash,json=lastRemoteConfigHash,proto3" json:"last_remote_config_hash,omitempty"`
	Status               RemoteConfigStatuses   `protobuf:"varint,2,opt,name=status,proto3,enum=deployment.v1alpha1.RemoteConfigStatuses" json:"status,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoteConfigStatus) Reset() {
	*x = RemoteConfigStatus{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteConfigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfigStatus) ProtoMessage() {}

func (x *RemoteConfigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfigStatus.ProtoReflect.Descriptor instead.
func (*RemoteConfigStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{30}
}

func (x *RemoteConfigStatus) GetLastRemoteConfigHash() []byte {
	if x != nil {
		return x.LastRemoteConfigHash
	}
	return nil
}

func (x *RemoteConfigStatus) GetStatus() RemoteConfigStatuses {
	if x != nil {
		return x.Status
	}
	return RemoteConfigStatuses_REMOTE_CONFIG_STATUSES_UNSET
}

func (x *RemoteConfigStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ConnectionStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          CollectorState         `protobuf:"varint,1,opt,name=state,proto3,enum=deployment.v1alpha1.CollectorState" json:"state,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ConnectedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	Sequence       uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{31}
}

func (x *ConnectionStatus) GetState() CollectorState {
	if x != nil {
		return x.State
	}
	return CollectorState_COLLECTOR_STATE_UNKNOWN
}

func (x *ConnectionStatus) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ConnectionStatus) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *ConnectionStatus) GetDisconnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectedAt
	}
	return nil
}

func (x *ConnectionStatus) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type SyncStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           ConfigSyncStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=deployment.v1alpha1.ConfigSyncStatus" json:"status,omitempty"`
	ConfigSyncReason string                 `protobuf:"bytes,2,opt,name=config_sync_reason,json=configSyncReason,proto3" json:"config_sync_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP(), []int{32}
}

func (x *SyncStatus) GetStatus() ConfigSyncStatus {
	if x != nil {
		return x.Status
	}
	return ConfigSyncStatus_CONFIG_SYNC_STATUS_UNKNOWN
}

func (x *SyncStatus) GetConfigSyncReason() string {
	if x != nil {
		return x.ConfigSyncReason
	}
	return ""
}

var File_pkg_api_deployment_v1alpha1_deployment_proto protoreflect.FileDescriptor

const file_pkg_api_deployment_v1alpha1_deployment_proto_rawDesc = "" +
	"\n" +
	",pkg/api/deployment/v1alpha1/deployment.proto\x12\x13deployment.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*pkg/api/resources/v1alpha1/resources.proto\x1a\"pkg/api/route/v1alpha1/route.proto\"G\n" +
	"\x15ValidateRouterRequest\x12.\n" +
	"\x06router\x18\x01 \x01(\v2\x16.route.v1alpha1.RouterR\x06router\"\x18\n" +
	"\x16ValidateRouterResponse\"F\n" +
	"\x14PreviewRouterRequest\x12.\n" +
	"\x06router\x18\x01 \x01(\v2\x16.route.v1alpha1.RouterR\x06router\"\x95\x01\n" +
	"\x15PreviewRouterResponse\x12=\n" +
	"\x03old\x18\x01 \x01(\v2+.deployment.v1alpha1.RouterConfigAssignmentR\x03old\x12=\n" +
	"\x03new\x18\x02 \x01(\v2+.deployment.v1alpha1.RouterConfigAssignmentR\x03new\"\xe0\x01\n" +
	"\x16RouterConfigAssignment\x12|\n" +
	"\x15collectorsToConfigRef\x18\x01 \x03(\v2F.deployment.v1alpha1.RouterConfigAssignment.CollectorsToConfigRefEntryR\x15collectorsToConfigRef\x1aH\n" +
	"\x1aCollectorsToConfigRefEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x04\n" +
	"\x12MatchRouterRequest\x12.\n" +
	"\x06router\x18\x01 \x01(\v2\x16.route.v1alpha1.RouterR\x06router\x12m\n" +
	"\x12identifying_labels\x18\x02 \x03(\v2>.deployment.v1alpha1.MatchRouterRequest.IdentifyingLabelsEntryR\x11identifyingLabels\x12w\n" +
	"\x16non_identifying_labels\x18\x03 \x03(\v2A.deployment.v1alpha1.MatchRouterRequest.NonIdentifyingLabelsEntryR\x14nonIdentifyingLabels\x12g\n" +
	"\x10otelfleet_labels\x18\x04 \x03(\v2<.deployment.v1alpha1.MatchRouterRequest.OtelfleetLabelsEntryR\x0fotelfleetLabels\x1aD\n" +
	"\x16IdentifyingLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19NonIdentifyingLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14OtelfleetLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\x13MatchRouterResponse\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x03(\tR\troutePath\x12(\n" +
	"\x10route_index_path\x18\x02 \x03(\rR\x0erouteIndexPath\x12\x1d\n" +
	"\n" +
	"config_ref\x18\x03 \x01(\tR\tconfigRef\x12\x18\n" +
	"\amatched\x18\x04 \x01(\bR\amatched\"m\n" +
	"\x1aGetCollectorHistoryRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"n\n" +
	"\x1bGetCollectorHistoryResponse\x12O\n" +
	"\x10effective_config\x18\x01 \x03(\v2$.deployment.v1alpha1.EffectiveConfigR\x0feffectiveConfig\"8\n" +
	"\x15ListCollectorsRequest\x12\x1f\n" +
	"\vwith_status\x18\x01 \x01(\bR\n" +
	"withStatus\"l\n" +
	"\x16ListCollectorsResponse\x12R\n" +
	"\n" +
	"collectors\x18\x01 \x03(\v22.deployment.v1alpha1.CollectorDescriptionAndStatusR\n" +
	"collectors\"\x9d\x01\n" +
	"\rCollectorView\x12N\n" +
	"\fregistration\x18\x01 \x01(\v2*.deployment.v1alpha1.CollectorRegistrationR\fregistration\x12<\n" +
	"\x06status\x18\x02 \x01(\v2$.deployment.v1alpha1.CollectorStatusR\x06status\"\xa6\x01\n" +
	"\x1dCollectorDescriptionAndStatus\x12G\n" +
	"\tcollector\x18\x01 \x01(\v2).deployment.v1alpha1.CollectorDescriptionR\tcollector\x12<\n" +
	"\x06status\x18\x02 \x01(\v2$.deployment.v1alpha1.CollectorStatusR\x06status\"8\n" +
	"\x13GetCollectorRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"_\n" +
	"\x14GetCollectorResponse\x12G\n" +
	"\tcollector\x18\x01 \x01(\v2).deployment.v1alpha1.CollectorDescriptionR\tcollector\">\n" +
	"\x19GetCollectorStatusRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"Z\n" +
	"\x1aGetCollectorStatusResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.deployment.v1alpha1.CollectorStatusR\x06status\";\n" +
	"\x16DeleteCollectorRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"\x85\x03\n" +
	"\x0fCollectorStatus\x12<\n" +
	"\x06health\x18\x01 \x01(\v2$.deployment.v1alpha1.ComponentHealthR\x06health\x12O\n" +
	"\x10effective_config\x18\x02 \x01(\v2$.deployment.v1alpha1.EffectiveConfigR\x0feffectiveConfig\x12Y\n" +
	"\x14remote_config_status\x18\x03 \x01(\v2'.deployment.v1alpha1.RemoteConfigStatusR\x12remoteConfigStatus\x12F\n" +
	"\vconn_status\x18\x04 \x01(\v2%.deployment.v1alpha1.ConnectionStatusR\n" +
	"connStatus\x12@\n" +
	"\vsync_status\x18\x05 \x01(\v2\x1f.deployment.v1alpha1.SyncStatusR\n" +
	"syncStatus\"\xa3\x02\n" +
	"\x15CollectorRegistration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfriendly_name\x18\x02 \x01(\tR\ffriendlyName\x12T\n" +
	"\x16identifying_attributes\x18\x03 \x03(\v2\x1d.deployment.v1alpha1.KeyValueR\x15identifyingAttributes\x12[\n" +
	"\x1anon_identifying_attributes\x18\x04 \x03(\v2\x1d.deployment.v1alpha1.KeyValueR\x18nonIdentifyingAttributes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xa2\x02\n" +
	"\x14CollectorDescription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfriendly_name\x18\x02 \x01(\tR\ffriendlyName\x12T\n" +
	"\x16identifying_attributes\x18\x03 \x03(\v2\x1d.deployment.v1alpha1.KeyValueR\x15identifyingAttributes\x12[\n" +
	"\x1anon_identifying_attributes\x18\x04 \x03(\v2\x1d.deployment.v1alpha1.KeyValueR\x18nonIdentifyingAttributes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"Q\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.deployment.v1alpha1.AnyValueR\x05value\"\xcc\x02\n" +
	"\bAnyValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12B\n" +
	"\varray_value\x18\x06 \x01(\v2\x1f.deployment.v1alpha1.ArrayValueH\x00R\n" +
	"arrayValue\x12F\n" +
	"\fkvlist_value\x18\a \x01(\v2!.deployment.v1alpha1.KeyValueListH\x00R\vkvlistValueB\a\n" +
	"\x05value\"C\n" +
	"\n" +
	"ArrayValue\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.deployment.v1alpha1.AnyValueR\x06values\"E\n" +
	"\fKeyValueList\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.deployment.v1alpha1.KeyValueR\x06values\"\x9f\x03\n" +
	"\x18CollectorConnectionState\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x129\n" +
	"\x05state\x18\x02 \x01(\x0e2#.deployment.v1alpha1.CollectorStateR\x05state\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12=\n" +
	"\fconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12C\n" +
	"\x0fdisconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectedAt\x12!\n" +
	"\finstance_uid\x18\x06 \x01(\fR\vinstanceUid\x12\"\n" +
	"\fcapabilities\x18\a \x01(\x04R\fcapabilities\x12!\n" +
	"\fsequence_num\x18\b \x01(\x04R\vsequenceNum\"\xa3\x03\n" +
	"\x0fComponentHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12/\n" +
	"\x14start_time_unix_nano\x18\x02 \x01(\x04R\x11startTimeUnixNano\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x121\n" +
	"\x15status_time_unix_nano\x18\x05 \x01(\x04R\x12statusTimeUnixNano\x12n\n" +
	"\x14component_health_map\x18\x06 \x03(\v2<.deployment.v1alpha1.ComponentHealth.ComponentHealthMapEntryR\x12componentHealthMap\x1ak\n" +
	"\x17ComponentHealthMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.deployment.v1alpha1.ComponentHealthR\x05value:\x028\x01\"Y\n" +
	"\x0fEffectiveConfig\x12F\n" +
	"\n" +
	"config_map\x18\x01 \x01(\v2'.deployment.v1alpha1.CollectorConfigMapR\tconfigMap\"\xd3\x01\n" +
	"\x12CollectorConfigMap\x12U\n" +
	"\n" +
	"config_map\x18\x01 \x03(\v26.deployment.v1alpha1.CollectorConfigMap.ConfigMapEntryR\tconfigMap\x1af\n" +
	"\x0eConfigMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.deployment.v1alpha1.CollectorConfigFileR\x05value:\x028\x01\"L\n" +
	"\x13CollectorConfigFile\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xb3\x01\n" +
	"\x12RemoteConfigStatus\x125\n" +
	"\x17last_remote_config_hash\x18\x01 \x01(\fR\x14lastRemoteConfigHash\x12A\n" +
	"\x06status\x18\x02 \x01(\x0e2).deployment.v1alpha1.RemoteConfigStatusesR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa6\x02\n" +
	"\x10ConnectionStatus\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.deployment.v1alpha1.CollectorStateR\x05state\x127\n" +
	"\tlast_seen\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12=\n" +
	"\fconnected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12C\n" +
	"\x0fdisconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectedAt\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\"y\n" +
	"\n" +
	"SyncStatus\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.deployment.v1alpha1.ConfigSyncStatusR\x06status\x12,\n" +
	"\x12config_sync_reason\x18\x02 \x01(\tR\x10configSyncReason*n\n" +
	"\x0eCollectorState\x12\x1b\n" +
	"\x17COLLECTOR_STATE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19COLLECTOR_STATE_CONNECTED\x10\x01\x12 \n" +
	"\x1cCOLLECTOR_STATE_DISCONNECTED\x10\x02*\xb5\x01\n" +
	"\x10ConfigSyncStatus\x12\x1e\n" +
	"\x1aCONFIG_SYNC_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aCONFIG_SYNC_STATUS_IN_SYNC\x10\x01\x12\"\n" +
	"\x1eCONFIG_SYNC_STATUS_OUT_OF_SYNC\x10\x02\x12\x1f\n" +
	"\x1bCONFIG_SYNC_STATUS_APPLYING\x10\x03\x12\x1c\n" +
	"\x18CONFIG_SYNC_STATUS_ERROR\x10\x04*\xa4\x01\n" +
	"\x14RemoteConfigStatuses\x12 \n" +
	"\x1cREMOTE_CONFIG_STATUSES_UNSET\x10\x00\x12\"\n" +
	"\x1eREMOTE_CONFIG_STATUSES_APPLIED\x10\x01\x12#\n" +
	"\x1fREMOTE_CONFIG_STATUSES_APPLYING\x10\x02\x12!\n" +
	"\x1dREMOTE_CONFIG_STATUSES_FAILED\x10\x032\xd1\x06\n" +
	"\x10CollectorService\x12i\n" +
	"\x0eListCollectors\x12*.deployment.v1alpha1.ListCollectorsRequest\x1a+.deployment.v1alpha1.ListCollectorsResponse\x12c\n" +
	"\fGetCollector\x12(.deployment.v1alpha1.GetCollectorRequest\x1a).deployment.v1alpha1.GetCollectorResponse\x12u\n" +
	"\x10CollectorHistory\x12/.deployment.v1alpha1.GetCollectorHistoryRequest\x1a0.deployment.v1alpha1.GetCollectorHistoryResponse\x12i\n" +
	"\x06Status\x12..deployment.v1alpha1.GetCollectorStatusRequest\x1a/.deployment.v1alpha1.GetCollectorStatusResponse\x12V\n" +
	"\x0fDeleteCollector\x12+.deployment.v1alpha1.DeleteCollectorRequest\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\x0eValidateRouter\x12*.deployment.v1alpha1.ValidateRouterRequest\x1a+.deployment.v1alpha1.ValidateRouterResponse\x12f\n" +
	"\rPreviewRouter\x12).deployment.v1alpha1.PreviewRouterRequest\x1a*.deployment.v1alpha1.PreviewRouterResponse\x12`\n" +
	"\vMatchRouter\x12'.deployment.v1alpha1.MatchRouterRequest\x1a(.deployment.v1alpha1.MatchRouterResponseB<Z:github.com/otelfleet/otelfleet/pkg/api/deployment/v1alpha1b\x06proto3"

var (
	file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescOnce sync.Once
	file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescData []byte
)

func file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescGZIP() []byte {
	file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescOnce.Do(func() {
		file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_deployment_v1alpha1_deployment_proto_rawDesc), len(file_pkg_api_deployment_v1alpha1_deployment_proto_rawDesc)))
	})
	return file_pkg_api_deployment_v1alpha1_deployment_proto_rawDescData
}

var file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_pkg_api_deployment_v1alpha1_deployment_proto_goTypes = []any{
	(CollectorState)(0),                   // 0: deployment.v1alpha1.CollectorState
	(ConfigSyncStatus)(0),                 // 1: deployment.v1alpha1.ConfigSyncStatus
	(RemoteConfigStatuses)(0),             // 2: deployment.v1alpha1.RemoteConfigStatuses
	(*ValidateRouterRequest)(nil),         // 3: deployment.v1alpha1.ValidateRouterRequest
	(*ValidateRouterResponse)(nil),        // 4: deployment.v1alpha1.ValidateRouterResponse
	(*PreviewRouterRequest)(nil),          // 5: deployment.v1alpha1.PreviewRouterRequest
	(*PreviewRouterResponse)(nil),         // 6: deployment.v1alpha1.PreviewRouterResponse
	(*RouterConfigAssignment)(nil),        // 7: deployment.v1alpha1.RouterConfigAssignment
	(*MatchRouterRequest)(nil),            // 8: deployment.v1alpha1.MatchRouterRequest
	(*MatchRouterResponse)(nil),           // 9: deployment.v1alpha1.MatchRouterResponse
	(*GetCollectorHistoryRequest)(nil),    // 10: deployment.v1alpha1.GetCollectorHistoryRequest
	(*GetCollectorHistoryResponse)(nil),   // 11: deployment.v1alpha1.GetCollectorHistoryResponse
	(*ListCollectorsRequest)(nil),         // 12: deployment.v1alpha1.ListCollectorsRequest
	(*ListCollectorsResponse)(nil),        // 13: deployment.v1alpha1.ListCollectorsResponse
	(*CollectorView)(nil),                 // 14: deployment.v1alpha1.CollectorView
	(*CollectorDescriptionAndStatus)(nil), // 15: deployment.v1alpha1.CollectorDescriptionAndStatus
	(*GetCollectorRequest)(nil),           // 16: deployment.v1alpha1.GetCollectorRequest
	(*GetCollectorResponse)(nil),          // 17: deployment.v1alpha1.GetCollectorResponse
	(*GetCollectorStatusRequest)(nil),     // 18: deployment.v1alpha1.GetCollectorStatusRequest
	(*GetCollectorStatusResponse)(nil),    // 19: deployment.v1alpha1.GetCollectorStatusResponse
	(*DeleteCollectorRequest)(nil),        // 20: deployment.v1alpha1.DeleteCollectorRequest
	(*CollectorStatus)(nil),               // 21: deployment.v1alpha1.CollectorStatus
	(*CollectorRegistration)(nil),         // 22: deployment.v1alpha1.CollectorRegistration
	(*CollectorDescription)(nil),          // 23: deployment.v1alpha1.CollectorDescription
	(*KeyValue)(nil),                      // 24: deployment.v1alpha1.KeyValue
	(*AnyValue)(nil),                      // 25: deployment.v1alpha1.AnyValue
	(*ArrayValue)(nil),                    // 26: deployment.v1alpha1.ArrayValue
	(*KeyValueList)(nil),                  // 27: deployment.v1alpha1.KeyValueList
	(*CollectorConnectionState)(nil),      // 28: deployment.v1alpha1.CollectorConnectionState
	(*ComponentHealth)(nil),               // 29: deployment.v1alpha1.ComponentHealth
	(*EffectiveConfig)(nil),               // 30: deployment.v1alpha1.EffectiveConfig
	(*CollectorConfigMap)(nil),            // 31: deployment.v1alpha1.CollectorConfigMap
	(*CollectorConfigFile)(nil),           // 32: deployment.v1alpha1.CollectorConfigFile
	(*RemoteConfigStatus)(nil),            // 33: deployment.v1alpha1.RemoteConfigStatus
	(*ConnectionStatus)(nil),              // 34: deployment.v1alpha1.ConnectionStatus
	(*SyncStatus)(nil),                    // 35: deployment.v1alpha1.SyncStatus
	nil,                                   // 36: deployment.v1alpha1.RouterConfigAssignment.CollectorsToConfigRefEntry
	nil,                                   // 37: deployment.v1alpha1.MatchRouterRequest.IdentifyingLabelsEntry
	nil,                                   // 38: deployment.v1alpha1.MatchRouterRequest.NonIdentifyingLabelsEntry
	nil,                                   // 39: deployment.v1alpha1.MatchRouterRequest.OtelfleetLabelsEntry
	nil,                                   // 40: deployment.v1alpha1.ComponentHealth.ComponentHealthMapEntry
	nil,                                   // 41: deployment.v1alpha1.CollectorConfigMap.ConfigMapEntry
	(*v1alpha1.Router)(nil),               // 42: route.v1alpha1.Router
	(*timestamppb.Timestamp)(nil),         // 43: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 44: google.protobuf.Empty
}
var file_pkg_api_deployment_v1alpha1_deployment_proto_depIdxs = []int32{
	42, // 0: deployment.v1alpha1.ValidateRouterRequest.router:type_name -> route.v1alpha1.Router
	42, // 1: deployment.v1alpha1.PreviewRouterRequest.router:type_name -> route.v1alpha1.Router
	7,  // 2: deployment.v1alpha1.PreviewRouterResponse.old:type_name -> deployment.v1alpha1.RouterConfigAssignment
	7,  // 3: deployment.v1alpha1.PreviewRouterResponse.new:type_name -> deployment.v1alpha1.RouterConfigAssignment
	36, // 4: deployment.v1alpha1.RouterConfigAssignment.collectorsToConfigRef:type_name -> deployment.v1alpha1.RouterConfigAssignment.CollectorsToConfigRefEntry
	42, // 5: deployment.v1alpha1.MatchRouterRequest.router:type_name -> route.v1alpha1.Router
	37, // 6: deployment.v1alpha1.MatchRouterRequest.identifying_labels:type_name -> deployment.v1alpha1.MatchRouterRequest.IdentifyingLabelsEntry
	38, // 7: deployment.v1alpha1.MatchRouterRequest.non_identifying_labels:type_name -> deployment.v1alpha1.MatchRouterRequest.NonIdentifyingLabelsEntry
	39, // 8: deployment.v1alpha1.MatchRouterRequest.otelfleet_labels:type_name -> deployment.v1alpha1.MatchRouterRequest.OtelfleetLabelsEntry
	30, // 9: deployment.v1alpha1.GetCollectorHistoryResponse.effective_config:type_name -> deployment.v1alpha1.EffectiveConfig
	15, // 10: deployment.v1alpha1.ListCollectorsResponse.collectors:type_name -> deployment.v1alpha1.CollectorDescriptionAndStatus
	22, // 11: deployment.v1alpha1.CollectorView.registration:type_name -> deployment.v1alpha1.CollectorRegistration
	21, // 12: deployment.v1alpha1.CollectorView.status:type_name -> deployment.v1alpha1.CollectorStatus
	23, // 13: deployment.v1alpha1.CollectorDescriptionAndStatus.collector:type_name -> deployment.v1alpha1.CollectorDescription
	21, // 14: deployment.v1alpha1.CollectorDescriptionAndStatus.status:type_name -> deployment.v1alpha1.CollectorStatus
	23, // 15: deployment.v1alpha1.GetCollectorResponse.collector:type_name -> deployment.v1alpha1.CollectorDescription
	21, // 16: deployment.v1alpha1.GetCollectorStatusResponse.status:type_name -> deployment.v1alpha1.CollectorStatus
	29, // 17: deployment.v1alpha1.CollectorStatus.health:type_name -> deployment.v1alpha1.ComponentHealth
	30, // 18: deployment.v1alpha1.CollectorStatus.effective_config:type_name -> deployment.v1alpha1.EffectiveConfig
	33, // 19: deployment.v1alpha1.CollectorStatus.remote_config_status:type_name -> deployment.v1alpha1.RemoteConfigStatus
	34, // 20: deployment.v1alpha1.CollectorStatus.conn_status:type_name -> deployment.v1alpha1.ConnectionStatus
	35, // 21: deployment.v1alpha1.CollectorStatus.sync_status:type_name -> deployment.v1alpha1.SyncStatus
	24, // 22: deployment.v1alpha1.CollectorRegistration.identifying_attributes:type_name -> deployment.v1alpha1.KeyValue
	24, // 23: deployment.v1alpha1.CollectorRegistration.non_identifying_attributes:type_name -> deployment.v1alpha1.KeyValue
	24, // 24: deployment.v1alpha1.CollectorDescription.identifying_attributes:type_name -> deployment.v1alpha1.KeyValue
	24, // 25: deployment.v1alpha1.CollectorDescription.non_identifying_attributes:type_name -> deployment.v1alpha1.KeyValue
	25, // 26: deployment.v1alpha1.KeyValue.value:type_name -> deployment.v1alpha1.AnyValue
	26, // 27: deployment.v1alpha1.AnyValue.array_value:type_name -> deployment.v1alpha1.ArrayValue
	27, // 28: deployment.v1alpha1.AnyValue.kvlist_value:type_name -> deployment.v1alpha1.KeyValueList
	25, // 29: deployment.v1alpha1.ArrayValue.values:type_name -> deployment.v1alpha1.AnyValue
	24, // 30: deployment.v1alpha1.KeyValueList.values:type_name -> deployment.v1alpha1.KeyValue
	0,  // 31: deployment.v1alpha1.CollectorConnectionState.state:type_name -> deployment.v1alpha1.CollectorState
	43, // 32: deployment.v1alpha1.CollectorConnectionState.last_seen:type_name -> google.protobuf.Timestamp
	43, // 33: deployment.v1alpha1.CollectorConnectionState.connected_at:type_name -> google.protobuf.Timestamp
	43, // 34: deployment.v1alpha1.CollectorConnectionState.disconnected_at:type_name -> google.protobuf.Timestamp
	40, // 35: deployment.v1alpha1.ComponentHealth.component_health_map:type_name -> deployment.v1alpha1.ComponentHealth.ComponentHealthMapEntry
	31, // 36: deployment.v1alpha1.EffectiveConfig.config_map:type_name -> deployment.v1alpha1.CollectorConfigMap
	41, // 37: deployment.v1alpha1.CollectorConfigMap.config_map:type_name -> deployment.v1alpha1.CollectorConfigMap.ConfigMapEntry
	2,  // 38: deployment.v1alpha1.RemoteConfigStatus.status:type_name -> deployment.v1alpha1.RemoteConfigStatuses
	0,  // 39: deployment.v1alpha1.ConnectionStatus.state:type_name -> deployment.v1alpha1.CollectorState
	43, // 40: deployment.v1alpha1.ConnectionStatus.last_seen:type_name -> google.protobuf.Timestamp
	43, // 41: deployment.v1alpha1.ConnectionStatus.connected_at:type_name -> google.protobuf.Timestamp
	43, // 42: deployment.v1alpha1.ConnectionStatus.disconnected_at:type_name -> google.protobuf.Timestamp
	1,  // 43: deployment.v1alpha1.SyncStatus.status:type_name -> deployment.v1alpha1.ConfigSyncStatus
	29, // 44: deployment.v1alpha1.ComponentHealth.ComponentHealthMapEntry.value:type_name -> deployment.v1alpha1.ComponentHealth
	32, // 45: deployment.v1alpha1.CollectorConfigMap.ConfigMapEntry.value:type_name -> deployment.v1alpha1.CollectorConfigFile
	12, // 46: deployment.v1alpha1.CollectorService.ListCollectors:input_type -> deployment.v1alpha1.ListCollectorsRequest
	16, // 47: deployment.v1alpha1.CollectorService.GetCollector:input_type -> deployment.v1alpha1.GetCollectorRequest
	10, // 48: deployment.v1alpha1.CollectorService.CollectorHistory:input_type -> deployment.v1alpha1.GetCollectorHistoryRequest
	18, // 49: deployment.v1alpha1.CollectorService.Status:input_type -> deployment.v1alpha1.GetCollectorStatusRequest
	20, // 50: deployment.v1alpha1.CollectorService.DeleteCollector:input_type -> deployment.v1alpha1.DeleteCollectorRequest
	3,  // 51: deployment.v1alpha1.CollectorService.ValidateRouter:input_type -> deployment.v1alpha1.ValidateRouterRequest
	5,  // 52: deployment.v1alpha1.CollectorService.PreviewRouter:input_type -> deployment.v1alpha1.PreviewRouterRequest
	8,  // 53: deployment.v1alpha1.CollectorService.MatchRouter:input_type -> deployment.v1alpha1.MatchRouterRequest
	13, // 54: deployment.v1alpha1.CollectorService.ListCollectors:output_type -> deployment.v1alpha1.ListCollectorsResponse
	17, // 55: deployment.v1alpha1.CollectorService.GetCollector:output_type -> deployment.v1alpha1.GetCollectorResponse
	11, // 56: deployment.v1alpha1.CollectorService.CollectorHistory:output_type -> deployment.v1alpha1.GetCollectorHistoryResponse
	19, // 57: deployment.v1alpha1.CollectorService.Status:output_type -> deployment.v1alpha1.GetCollectorStatusResponse
	44, // 58: deployment.v1alpha1.CollectorService.DeleteCollector:output_type -> google.protobuf.Empty
	4,  // 59: deployment.v1alpha1.CollectorService.ValidateRouter:output_type -> deployment.v1alpha1.ValidateRouterResponse
	6,  // 60: deployment.v1alpha1.CollectorService.PreviewRouter:output_type -> deployment.v1alpha1.PreviewRouterResponse
	9,  // 61: deployment.v1alpha1.CollectorService.MatchRouter:output_type -> deployment.v1alpha1.MatchRouterResponse
	54, // [54:62] is the sub-list for method output_type
	46, // [46:54] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_pkg_api_deployment_v1alpha1_deployment_proto_init() }
func file_pkg_api_deployment_v1alpha1_deployment_proto_init() {
	if File_pkg_api_deployment_v1alpha1_deployment_proto != nil {
		return
	}
	file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes[22].OneofWrappers = []any{
		(*AnyValue_StringValue)(nil),
		(*AnyValue_BoolValue)(nil),
		(*AnyValue_IntValue)(nil),
		(*AnyValue_DoubleValue)(nil),
		(*AnyValue_BytesValue)(nil),
		(*AnyValue_ArrayValue)(nil),
		(*AnyValue_KvlistValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_deployment_v1alpha1_deployment_proto_rawDesc), len(file_pkg_api_deployment_v1alpha1_deployment_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_deployment_v1alpha1_deployment_proto_goTypes,
		DependencyIndexes: file_pkg_api_deployment_v1alpha1_deployment_proto_depIdxs,
		EnumInfos:         file_pkg_api_deployment_v1alpha1_deployment_proto_enumTypes,
		MessageInfos:      file_pkg_api_deployment_v1alpha1_deployment_proto_msgTypes,
	}.Build()
	File_pkg_api_deployment_v1alpha1_deployment_proto = out.File
	file_pkg_api_deployment_v1alpha1_deployment_proto_goTypes = nil
	file_pkg_api_deployment_v1alpha1_deployment_proto_depIdxs = nil
}
