// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/api/keyvalue/v1alpha1/keyvalue.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/keyvalue/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// KeyValueServiceName is the fully-qualified name of the KeyValueService service.
	KeyValueServiceName = "keyvalue.v1alpha1.KeyValueService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KeyValueServiceGetProcedure is the fully-qualified name of the KeyValueService's Get RPC.
	KeyValueServiceGetProcedure = "/keyvalue.v1alpha1.KeyValueService/Get"
	// KeyValueServicePutProcedure is the fully-qualified name of the KeyValueService's Put RPC.
	KeyValueServicePutProcedure = "/keyvalue.v1alpha1.KeyValueService/Put"
	// KeyValueServiceListKeysProcedure is the fully-qualified name of the KeyValueService's ListKeys
	// RPC.
	KeyValueServiceListKeysProcedure = "/keyvalue.v1alpha1.KeyValueService/ListKeys"
	// KeyValueServiceListProcedure is the fully-qualified name of the KeyValueService's List RPC.
	KeyValueServiceListProcedure = "/keyvalue.v1alpha1.KeyValueService/List"
	// KeyValueServiceDeleteProcedure is the fully-qualified name of the KeyValueService's Delete RPC.
	KeyValueServiceDeleteProcedure = "/keyvalue.v1alpha1.KeyValueService/Delete"
	// KeyValueServiceHistoryProcedure is the fully-qualified name of the KeyValueService's History RPC.
	KeyValueServiceHistoryProcedure = "/keyvalue.v1alpha1.KeyValueService/History"
	// KeyValueServiceWatchProcedure is the fully-qualified name of the KeyValueService's Watch RPC.
	KeyValueServiceWatchProcedure = "/keyvalue.v1alpha1.KeyValueService/Watch"
)

// KeyValueServiceClient is a client for the keyvalue.v1alpha1.KeyValueService service.
type KeyValueServiceClient interface {
	Get(context.Context, *connect.Request[v1alpha1.GetRequest]) (*connect.Response[v1alpha1.GetResponse], error)
	Put(context.Context, *connect.Request[v1alpha1.PutRequest]) (*connect.Response[v1alpha1.PutResponse], error)
	ListKeys(context.Context, *connect.Request[v1alpha1.ListKeysRequest]) (*connect.Response[v1alpha1.ListKeysResponse], error)
	List(context.Context, *connect.Request[v1alpha1.ListRequest]) (*connect.Response[v1alpha1.ListResponse], error)
	Delete(context.Context, *connect.Request[v1alpha1.DeleteRequest]) (*connect.Response[v1alpha1.DeleteResponse], error)
	History(context.Context, *connect.Request[v1alpha1.GetHistoryRequest]) (*connect.Response[v1alpha1.GetHistoryResponse], error)
	Watch(context.Context, *connect.Request[v1alpha1.WatchRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchEvent], error)
}

// NewKeyValueServiceClient constructs a client for the keyvalue.v1alpha1.KeyValueService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKeyValueServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KeyValueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	keyValueServiceMethods := v1alpha1.File_pkg_api_keyvalue_v1alpha1_keyvalue_proto.Services().ByName("KeyValueService").Methods()
	return &keyValueServiceClient{
		get: connect.NewClient[v1alpha1.GetRequest, v1alpha1.GetResponse](
			httpClient,
			baseURL+KeyValueServiceGetProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		put: connect.NewClient[v1alpha1.PutRequest, v1alpha1.PutResponse](
			httpClient,
			baseURL+KeyValueServicePutProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("Put")),
			connect.WithClientOptions(opts...),
		),
		listKeys: connect.NewClient[v1alpha1.ListKeysRequest, v1alpha1.ListKeysResponse](
			httpClient,
			baseURL+KeyValueServiceListKeysProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("ListKeys")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1alpha1.ListRequest, v1alpha1.ListResponse](
			httpClient,
			baseURL+KeyValueServiceListProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1alpha1.DeleteRequest, v1alpha1.DeleteResponse](
			httpClient,
			baseURL+KeyValueServiceDeleteProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		history: connect.NewClient[v1alpha1.GetHistoryRequest, v1alpha1.GetHistoryResponse](
			httpClient,
			baseURL+KeyValueServiceHistoryProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("History")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1alpha1.WatchRequest, v1alpha1.WatchEvent](
			httpClient,
			baseURL+KeyValueServiceWatchProcedure,
			connect.WithSchema(keyValueServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// keyValueServiceClient implements KeyValueServiceClient.
type keyValueServiceClient struct {
	get      *connect.Client[v1alpha1.GetRequest, v1alpha1.GetResponse]
	put      *connect.Client[v1alpha1.PutRequest, v1alpha1.PutResponse]
	listKeys *connect.Client[v1alpha1.ListKeysRequest, v1alpha1.ListKeysResponse]
	list     *connect.Client[v1alpha1.ListRequest, v1alpha1.ListResponse]
	delete   *connect.Client[v1alpha1.DeleteRequest, v1alpha1.DeleteResponse]
	history  *connect.Client[v1alpha1.GetHistoryRequest, v1alpha1.GetHistoryResponse]
	watch    *connect.Client[v1alpha1.WatchRequest, v1alpha1.WatchEvent]
}

// Get calls keyvalue.v1alpha1.KeyValueService.Get.
func (c *keyValueServiceClient) Get(ctx context.Context, req *connect.Request[v1alpha1.GetRequest]) (*connect.Response[v1alpha1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Put calls keyvalue.v1alpha1.KeyValueService.Put.
func (c *keyValueServiceClient) Put(ctx context.Context, req *connect.Request[v1alpha1.PutRequest]) (*connect.Response[v1alpha1.PutResponse], error) {
	return c.put.CallUnary(ctx, req)
}

// ListKeys calls keyvalue.v1alpha1.KeyValueService.ListKeys.
func (c *keyValueServiceClient) ListKeys(ctx context.Context, req *connect.Request[v1alpha1.ListKeysRequest]) (*connect.Response[v1alpha1.ListKeysResponse], error) {
	return c.listKeys.CallUnary(ctx, req)
}

// List calls keyvalue.v1alpha1.KeyValueService.List.
func (c *keyValueServiceClient) List(ctx context.Context, req *connect.Request[v1alpha1.ListRequest]) (*connect.Response[v1alpha1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Delete calls keyvalue.v1alpha1.KeyValueService.Delete.
func (c *keyValueServiceClient) Delete(ctx context.Context, req *connect.Request[v1alpha1.DeleteRequest]) (*connect.Response[v1alpha1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// History calls keyvalue.v1alpha1.KeyValueService.History.
func (c *keyValueServiceClient) History(ctx context.Context, req *connect.Request[v1alpha1.GetHistoryRequest]) (*connect.Response[v1alpha1.GetHistoryResponse], error) {
	return c.history.CallUnary(ctx, req)
}

// Watch calls keyvalue.v1alpha1.KeyValueService.Watch.
func (c *keyValueServiceClient) Watch(ctx context.Context, req *connect.Request[v1alpha1.WatchRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchEvent], error) {
	return c.watch.CallServerStream(ctx, req)
}

// KeyValueServiceHandler is an implementation of the keyvalue.v1alpha1.KeyValueService service.
type KeyValueServiceHandler interface {
	Get(context.Context, *connect.Request[v1alpha1.GetRequest]) (*connect.Response[v1alpha1.GetResponse], error)
	Put(context.Context, *connect.Request[v1alpha1.PutRequest]) (*connect.Response[v1alpha1.PutResponse], error)
	ListKeys(context.Context, *connect.Request[v1alpha1.ListKeysRequest]) (*connect.Response[v1alpha1.ListKeysResponse], error)
	List(context.Context, *connect.Request[v1alpha1.ListRequest]) (*connect.Response[v1alpha1.ListResponse], error)
	Delete(context.Context, *connect.Request[v1alpha1.DeleteRequest]) (*connect.Response[v1alpha1.DeleteResponse], error)
	History(context.Context, *connect.Request[v1alpha1.GetHistoryRequest]) (*connect.Response[v1alpha1.GetHistoryResponse], error)
	Watch(context.Context, *connect.Request[v1alpha1.WatchRequest], *connect.ServerStream[v1alpha1.WatchEvent]) error
}

// NewKeyValueServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKeyValueServiceHandler(svc KeyValueServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	keyValueServiceMethods := v1alpha1.File_pkg_api_keyvalue_v1alpha1_keyvalue_proto.Services().ByName("KeyValueService").Methods()
	keyValueServiceGetHandler := connect.NewUnaryHandler(
		KeyValueServiceGetProcedure,
		svc.Get,
		connect.WithSchema(keyValueServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	keyValueServicePutHandler := connect.NewUnaryHandler(
		KeyValueServicePutProcedure,
		svc.Put,
		connect.WithSchema(keyValueServiceMethods.ByName("Put")),
		connect.WithHandlerOptions(opts...),
	)
	keyValueServiceListKeysHandler := connect.NewUnaryHandler(
		KeyValueServiceListKeysProcedure,
		svc.ListKeys,
		connect.WithSchema(keyValueServiceMethods.ByName("ListKeys")),
		connect.WithHandlerOptions(opts...),
	)
	keyValueServiceListHandler := connect.NewUnaryHandler(
		KeyValueServiceListProcedure,
		svc.List,
		connect.WithSchema(keyValueServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	keyValueServiceDeleteHandler := connect.NewUnaryHandler(
		KeyValueServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(keyValueServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	keyValueServiceHistoryHandler := connect.NewUnaryHandler(
		KeyValueServiceHistoryProcedure,
		svc.History,
		connect.WithSchema(keyValueServiceMethods.ByName("History")),
		connect.WithHandlerOptions(opts...),
	)
	keyValueServiceWatchHandler := connect.NewServerStreamHandler(
		KeyValueServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(keyValueServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/keyvalue.v1alpha1.KeyValueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KeyValueServiceGetProcedure:
			keyValueServiceGetHandler.ServeHTTP(w, r)
		case KeyValueServicePutProcedure:
			keyValueServicePutHandler.ServeHTTP(w, r)
		case KeyValueServiceListKeysProcedure:
			keyValueServiceListKeysHandler.ServeHTTP(w, r)
		case KeyValueServiceListProcedure:
			keyValueServiceListHandler.ServeHTTP(w, r)
		case KeyValueServiceDeleteProcedure:
			keyValueServiceDeleteHandler.ServeHTTP(w, r)
		case KeyValueServiceHistoryProcedure:
			keyValueServiceHistoryHandler.ServeHTTP(w, r)
		case KeyValueServiceWatchProcedure:
			keyValueServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKeyValueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKeyValueServiceHandler struct{}

func (UnimplementedKeyValueServiceHandler) Get(context.Context, *connect.Request[v1alpha1.GetRequest]) (*connect.Response[v1alpha1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.Get is not implemented"))
}

func (UnimplementedKeyValueServiceHandler) Put(context.Context, *connect.Request[v1alpha1.PutRequest]) (*connect.Response[v1alpha1.PutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.Put is not implemented"))
}

func (UnimplementedKeyValueServiceHandler) ListKeys(context.Context, *connect.Request[v1alpha1.ListKeysRequest]) (*connect.Response[v1alpha1.ListKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.ListKeys is not implemented"))
}

func (UnimplementedKeyValueServiceHandler) List(context.Context, *connect.Request[v1alpha1.ListRequest]) (*connect.Response[v1alpha1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.List is not implemented"))
}

func (UnimplementedKeyValueServiceHandler) Delete(context.Context, *connect.Request[v1alpha1.DeleteRequest]) (*connect.Response[v1alpha1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.Delete is not implemented"))
}

func (UnimplementedKeyValueServiceHandler) History(context.Context, *connect.Request[v1alpha1.GetHistoryRequest]) (*connect.Response[v1alpha1.GetHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.History is not implemented"))
}

func (UnimplementedKeyValueServiceHandler) Watch(context.Context, *connect.Request[v1alpha1.WatchRequest], *connect.ServerStream[v1alpha1.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("keyvalue.v1alpha1.KeyValueService.Watch is not implemented"))
}
