// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/keyvalue/v1alpha1/keyvalue.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterKeyValueServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterKeyValueServiceHandler(mux *mux.Router, svc KeyValueServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/Get", connect.NewUnaryHandler(
		"/keyvalue.v1alpha1.KeyValueService/Get",
		svc.Get,
		opts...,
	))
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/Put", connect.NewUnaryHandler(
		"/keyvalue.v1alpha1.KeyValueService/Put",
		svc.Put,
		opts...,
	))
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/ListKeys", connect.NewUnaryHandler(
		"/keyvalue.v1alpha1.KeyValueService/ListKeys",
		svc.ListKeys,
		opts...,
	))
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/List", connect.NewUnaryHandler(
		"/keyvalue.v1alpha1.KeyValueService/List",
		svc.List,
		opts...,
	))
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/Delete", connect.NewUnaryHandler(
		"/keyvalue.v1alpha1.KeyValueService/Delete",
		svc.Delete,
		opts...,
	))
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/History", connect.NewUnaryHandler(
		"/keyvalue.v1alpha1.KeyValueService/History",
		svc.History,
		opts...,
	))
	mux.Handle("/keyvalue.v1alpha1.KeyValueService/Watch", connect.NewServerStreamHandler(
		"/keyvalue.v1alpha1.KeyValueService/Watch",
		svc.Watch,
		opts...,
	))
}
