// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/api/config/config.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/bootstrap/v1alpha1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "config.v1alpha1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceValidConfigProcedure is the fully-qualified name of the ConfigService's ValidConfig
	// RPC.
	ConfigServiceValidConfigProcedure = "/config.v1alpha1.ConfigService/ValidConfig"
	// ConfigServiceUpdateConfigProcedure is the fully-qualified name of the ConfigService's
	// UpdateConfig RPC.
	ConfigServiceUpdateConfigProcedure = "/config.v1alpha1.ConfigService/UpdateConfig"
	// ConfigServiceDeleteConfigProcedure is the fully-qualified name of the ConfigService's
	// DeleteConfig RPC.
	ConfigServiceDeleteConfigProcedure = "/config.v1alpha1.ConfigService/DeleteConfig"
	// ConfigServiceListConfigsProcedure is the fully-qualified name of the ConfigService's ListConfigs
	// RPC.
	ConfigServiceListConfigsProcedure = "/config.v1alpha1.ConfigService/ListConfigs"
	// ConfigServiceSetDefaultConfigProcedure is the fully-qualified name of the ConfigService's
	// SetDefaultConfig RPC.
	ConfigServiceSetDefaultConfigProcedure = "/config.v1alpha1.ConfigService/SetDefaultConfig"
)

// ConfigServiceClient is a client for the config.v1alpha1.ConfigService service.
type ConfigServiceClient interface {
	ValidConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	UpdateConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	DeleteConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	// ListConfigs by matchers
	ListConfigs(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	SetDefaultConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
}

// NewConfigServiceClient constructs a client for the config.v1alpha1.ConfigService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1alpha1.File_pkg_api_config_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		validConfig: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+ConfigServiceValidConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("ValidConfig")),
			connect.WithClientOptions(opts...),
		),
		updateConfig: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+ConfigServiceUpdateConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateConfig")),
			connect.WithClientOptions(opts...),
		),
		deleteConfig: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+ConfigServiceDeleteConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteConfig")),
			connect.WithClientOptions(opts...),
		),
		listConfigs: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+ConfigServiceListConfigsProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListConfigs")),
			connect.WithClientOptions(opts...),
		),
		setDefaultConfig: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+ConfigServiceSetDefaultConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("SetDefaultConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	validConfig      *connect.Client[emptypb.Empty, emptypb.Empty]
	updateConfig     *connect.Client[emptypb.Empty, emptypb.Empty]
	deleteConfig     *connect.Client[emptypb.Empty, emptypb.Empty]
	listConfigs      *connect.Client[emptypb.Empty, emptypb.Empty]
	setDefaultConfig *connect.Client[emptypb.Empty, emptypb.Empty]
}

// ValidConfig calls config.v1alpha1.ConfigService.ValidConfig.
func (c *configServiceClient) ValidConfig(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.validConfig.CallUnary(ctx, req)
}

// UpdateConfig calls config.v1alpha1.ConfigService.UpdateConfig.
func (c *configServiceClient) UpdateConfig(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.updateConfig.CallUnary(ctx, req)
}

// DeleteConfig calls config.v1alpha1.ConfigService.DeleteConfig.
func (c *configServiceClient) DeleteConfig(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteConfig.CallUnary(ctx, req)
}

// ListConfigs calls config.v1alpha1.ConfigService.ListConfigs.
func (c *configServiceClient) ListConfigs(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.listConfigs.CallUnary(ctx, req)
}

// SetDefaultConfig calls config.v1alpha1.ConfigService.SetDefaultConfig.
func (c *configServiceClient) SetDefaultConfig(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.setDefaultConfig.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the config.v1alpha1.ConfigService service.
type ConfigServiceHandler interface {
	ValidConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	UpdateConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	DeleteConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	// ListConfigs by matchers
	ListConfigs(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	SetDefaultConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1alpha1.File_pkg_api_config_config_proto.Services().ByName("ConfigService").Methods()
	configServiceValidConfigHandler := connect.NewUnaryHandler(
		ConfigServiceValidConfigProcedure,
		svc.ValidConfig,
		connect.WithSchema(configServiceMethods.ByName("ValidConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateConfigHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateConfigProcedure,
		svc.UpdateConfig,
		connect.WithSchema(configServiceMethods.ByName("UpdateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteConfigHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteConfigProcedure,
		svc.DeleteConfig,
		connect.WithSchema(configServiceMethods.ByName("DeleteConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListConfigsHandler := connect.NewUnaryHandler(
		ConfigServiceListConfigsProcedure,
		svc.ListConfigs,
		connect.WithSchema(configServiceMethods.ByName("ListConfigs")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceSetDefaultConfigHandler := connect.NewUnaryHandler(
		ConfigServiceSetDefaultConfigProcedure,
		svc.SetDefaultConfig,
		connect.WithSchema(configServiceMethods.ByName("SetDefaultConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/config.v1alpha1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceValidConfigProcedure:
			configServiceValidConfigHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateConfigProcedure:
			configServiceUpdateConfigHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteConfigProcedure:
			configServiceDeleteConfigHandler.ServeHTTP(w, r)
		case ConfigServiceListConfigsProcedure:
			configServiceListConfigsHandler.ServeHTTP(w, r)
		case ConfigServiceSetDefaultConfigProcedure:
			configServiceSetDefaultConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) ValidConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.ValidConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.UpdateConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.DeleteConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListConfigs(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.ListConfigs is not implemented"))
}

func (UnimplementedConfigServiceHandler) SetDefaultConfig(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1alpha1.ConfigService.SetDefaultConfig is not implemented"))
}
