// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/keyvalue/v1alpha1/keyvalue.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Query         *RangeRequest          `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{0}
}

func (x *GetHistoryRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *GetHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetHistoryRequest) GetQuery() *RangeRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{1}
}

func (x *RangeRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RangeRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Objs          []*KeyValueObject      `protobuf:"bytes,2,rep,name=objs,proto3" json:"objs,omitempty"`
	Position      *RangeRequest          `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *GetHistoryResponse) GetObjs() []*KeyValueObject {
	if x != nil {
		return x.Objs
	}
	return nil
}

func (x *GetHistoryResponse) GetPosition() *RangeRequest {
	if x != nil {
		return x.Position
	}
	return nil
}

type KeyValueObject struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Revision uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash     []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	TypeUrl  string                 `protobuf:"bytes,3,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// unset for a tombstone (deleted) revision
	Obj           *anypb.Any             `protobuf:"bytes,4,opt,name=obj,proto3" json:"obj,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueObject) Reset() {
	*x = KeyValueObject{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueObject) ProtoMessage() {}

func (x *KeyValueObject) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueObject.ProtoReflect.Descriptor instead.
func (*KeyValueObject) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValueObject) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *KeyValueObject) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *KeyValueObject) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *KeyValueObject) GetObj() *anypb.Any {
	if x != nil {
		return x.Obj
	}
	return nil
}

func (x *KeyValueObject) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type PutRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key     string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data    *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// expected revision (current + 1); 0 applies unconditionally without a CAS check
	Revision      uint64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{4}
}

func (x *PutRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *KeyValueObject        `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{5}
}

func (x *PutResponse) GetObject() *KeyValueObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type GetRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key     string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 0 means latest
	Revision      uint64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Object        *KeyValueObject        `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *GetResponse) GetObject() *KeyValueObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Objects       []*KeyValueObject      `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *ListResponse) GetObjects() []*KeyValueObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{10}
}

func (x *ListKeysRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{11}
}

func (x *ListKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{13}
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{14}
}

func (x *WatchRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *WatchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EventType:
	//
	//	*WatchEvent_Modified
	//	*WatchEvent_DeletedKey
	EventType     isWatchEvent_EventType `protobuf_oneof:"eventType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP(), []int{15}
}

func (x *WatchEvent) GetEventType() isWatchEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *WatchEvent) GetModified() *KeyValueObject {
	if x != nil {
		if x, ok := x.EventType.(*WatchEvent_Modified); ok {
			return x.Modified
		}
	}
	return nil
}

func (x *WatchEvent) GetDeletedKey() string {
	if x != nil {
		if x, ok := x.EventType.(*WatchEvent_DeletedKey); ok {
			return x.DeletedKey
		}
	}
	return ""
}

type isWatchEvent_EventType interface {
	isWatchEvent_EventType()
}

type WatchEvent_Modified struct {
	Modified *KeyValueObject `protobuf:"bytes,1,opt,name=modified,proto3,oneof"`
}

type WatchEvent_DeletedKey struct {
	DeletedKey string `protobuf:"bytes,2,opt,name=deletedKey,proto3,oneof"`
}

func (*WatchEvent_Modified) isWatchEvent_EventType() {}

func (*WatchEvent_DeletedKey) isWatchEvent_EventType() {}

var File_pkg_api_keyvalue_v1alpha1_keyvalue_proto protoreflect.FileDescriptor

const file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDesc = "" +
	"\n" +
	"(pkg/api/keyvalue/v1alpha1/keyvalue.proto\x12\x11keyvalue.v1alpha1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x11GetHistoryRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x125\n" +
	"\x05query\x18\x03 \x01(\v2\x1f.keyvalue.v1alpha1.RangeRequestR\x05query\"<\n" +
	"\fRangeRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"\xa3\x01\n" +
	"\x12GetHistoryResponse\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x125\n" +
	"\x04objs\x18\x02 \x03(\v2!.keyvalue.v1alpha1.KeyValueObjectR\x04objs\x12;\n" +
	"\bposition\x18\x03 \x01(\v2\x1f.keyvalue.v1alpha1.RangeRequestR\bposition\"\xc0\x01\n" +
	"\x0eKeyValueObject\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x19\n" +
	"\btype_url\x18\x03 \x01(\tR\atypeUrl\x12&\n" +
	"\x03obj\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x03obj\x12;\n" +
	"\vmodified_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"\x7f\n" +
	"\n" +
	"PutRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\"H\n" +
	"\vPutResponse\x129\n" +
	"\x06object\x18\x01 \x01(\v2!.keyvalue.v1alpha1.KeyValueObjectR\x06object\"U\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\"c\n" +
	"\vGetResponse\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x129\n" +
	"\x06object\x18\x02 \x01(\v2!.keyvalue.v1alpha1.KeyValueObjectR\x06object\"(\n" +
	"\vListRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\"f\n" +
	"\fListResponse\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12;\n" +
	"\aobjects\x18\x02 \x03(\v2!.keyvalue.v1alpha1.KeyValueObjectR\aobjects\",\n" +
	"\x0fListKeysRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\"&\n" +
	"\x10ListKeysResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"<\n" +
	"\rDeleteRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"A\n" +
	"\fWatchRequest\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"|\n" +
	"\n" +
	"WatchEvent\x12?\n" +
	"\bmodified\x18\x01 \x01(\v2!.keyvalue.v1alpha1.KeyValueObjectH\x00R\bmodified\x12 \n" +
	"\n" +
	"deletedKey\x18\x02 \x01(\tH\x00R\n" +
	"deletedKeyB\v\n" +
	"\teventType2\xad\x04\n" +
	"\x0fKeyValueService\x12D\n" +
	"\x03Get\x12\x1d.keyvalue.v1alpha1.GetRequest\x1a\x1e.keyvalue.v1alpha1.GetResponse\x12D\n" +
	"\x03Put\x12\x1d.keyvalue.v1alpha1.PutRequest\x1a\x1e.keyvalue.v1alpha1.PutResponse\x12S\n" +
	"\bListKeys\x12\".keyvalue.v1alpha1.ListKeysRequest\x1a#.keyvalue.v1alpha1.ListKeysResponse\x12G\n" +
	"\x04List\x12\x1e.keyvalue.v1alpha1.ListRequest\x1a\x1f.keyvalue.v1alpha1.ListResponse\x12M\n" +
	"\x06Delete\x12 .keyvalue.v1alpha1.DeleteRequest\x1a!.keyvalue.v1alpha1.DeleteResponse\x12V\n" +
	"\aHistory\x12$.keyvalue.v1alpha1.GetHistoryRequest\x1a%.keyvalue.v1alpha1.GetHistoryResponse\x12I\n" +
	"\x05Watch\x12\x1f.keyvalue.v1alpha1.WatchRequest\x1a\x1d.keyvalue.v1alpha1.WatchEvent0\x01B:Z8github.com/otelfleet/otelfleet/pkg/api/keyvalue/v1alpha1b\x06proto3"

var (
	file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescOnce sync.Once
	file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescData []byte
)

func file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescGZIP() []byte {
	file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescOnce.Do(func() {
		file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDesc), len(file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDesc)))
	})
	return file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDescData
}

var file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_goTypes = []any{
	(*GetHistoryRequest)(nil),     // 0: keyvalue.v1alpha1.GetHistoryRequest
	(*RangeRequest)(nil),          // 1: keyvalue.v1alpha1.RangeRequest
	(*GetHistoryResponse)(nil),    // 2: keyvalue.v1alpha1.GetHistoryResponse
	(*KeyValueObject)(nil),        // 3: keyvalue.v1alpha1.KeyValueObject
	(*PutRequest)(nil),            // 4: keyvalue.v1alpha1.PutRequest
	(*PutResponse)(nil),           // 5: keyvalue.v1alpha1.PutResponse
	(*GetRequest)(nil),            // 6: keyvalue.v1alpha1.GetRequest
	(*GetResponse)(nil),           // 7: keyvalue.v1alpha1.GetResponse
	(*ListRequest)(nil),           // 8: keyvalue.v1alpha1.ListRequest
	(*ListResponse)(nil),          // 9: keyvalue.v1alpha1.ListResponse
	(*ListKeysRequest)(nil),       // 10: keyvalue.v1alpha1.ListKeysRequest
	(*ListKeysResponse)(nil),      // 11: keyvalue.v1alpha1.ListKeysResponse
	(*DeleteRequest)(nil),         // 12: keyvalue.v1alpha1.DeleteRequest
	(*DeleteResponse)(nil),        // 13: keyvalue.v1alpha1.DeleteResponse
	(*WatchRequest)(nil),          // 14: keyvalue.v1alpha1.WatchRequest
	(*WatchEvent)(nil),            // 15: keyvalue.v1alpha1.WatchEvent
	(*anypb.Any)(nil),             // 16: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_depIdxs = []int32{
	1,  // 0: keyvalue.v1alpha1.GetHistoryRequest.query:type_name -> keyvalue.v1alpha1.RangeRequest
	3,  // 1: keyvalue.v1alpha1.GetHistoryResponse.objs:type_name -> keyvalue.v1alpha1.KeyValueObject
	1,  // 2: keyvalue.v1alpha1.GetHistoryResponse.position:type_name -> keyvalue.v1alpha1.RangeRequest
	16, // 3: keyvalue.v1alpha1.KeyValueObject.obj:type_name -> google.protobuf.Any
	17, // 4: keyvalue.v1alpha1.KeyValueObject.modified_at:type_name -> google.protobuf.Timestamp
	16, // 5: keyvalue.v1alpha1.PutRequest.data:type_name -> google.protobuf.Any
	3,  // 6: keyvalue.v1alpha1.PutResponse.object:type_name -> keyvalue.v1alpha1.KeyValueObject
	3,  // 7: keyvalue.v1alpha1.GetResponse.object:type_name -> keyvalue.v1alpha1.KeyValueObject
	3,  // 8: keyvalue.v1alpha1.ListResponse.objects:type_name -> keyvalue.v1alpha1.KeyValueObject
	3,  // 9: keyvalue.v1alpha1.WatchEvent.modified:type_name -> keyvalue.v1alpha1.KeyValueObject
	6,  // 10: keyvalue.v1alpha1.KeyValueService.Get:input_type -> keyvalue.v1alpha1.GetRequest
	4,  // 11: keyvalue.v1alpha1.KeyValueService.Put:input_type -> keyvalue.v1alpha1.PutRequest
	10, // 12: keyvalue.v1alpha1.KeyValueService.ListKeys:input_type -> keyvalue.v1alpha1.ListKeysRequest
	8,  // 13: keyvalue.v1alpha1.KeyValueService.List:input_type -> keyvalue.v1alpha1.ListRequest
	12, // 14: keyvalue.v1alpha1.KeyValueService.Delete:input_type -> keyvalue.v1alpha1.DeleteRequest
	0,  // 15: keyvalue.v1alpha1.KeyValueService.History:input_type -> keyvalue.v1alpha1.GetHistoryRequest
	14, // 16: keyvalue.v1alpha1.KeyValueService.Watch:input_type -> keyvalue.v1alpha1.WatchRequest
	7,  // 17: keyvalue.v1alpha1.KeyValueService.Get:output_type -> keyvalue.v1alpha1.GetResponse
	5,  // 18: keyvalue.v1alpha1.KeyValueService.Put:output_type -> keyvalue.v1alpha1.PutResponse
	11, // 19: keyvalue.v1alpha1.KeyValueService.ListKeys:output_type -> keyvalue.v1alpha1.ListKeysResponse
	9,  // 20: keyvalue.v1alpha1.KeyValueService.List:output_type -> keyvalue.v1alpha1.ListResponse
	13, // 21: keyvalue.v1alpha1.KeyValueService.Delete:output_type -> keyvalue.v1alpha1.DeleteResponse
	2,  // 22: keyvalue.v1alpha1.KeyValueService.History:output_type -> keyvalue.v1alpha1.GetHistoryResponse
	15, // 23: keyvalue.v1alpha1.KeyValueService.Watch:output_type -> keyvalue.v1alpha1.WatchEvent
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_init() }
func file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_init() {
	if File_pkg_api_keyvalue_v1alpha1_keyvalue_proto != nil {
		return
	}
	file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes[15].OneofWrappers = []any{
		(*WatchEvent_Modified)(nil),
		(*WatchEvent_DeletedKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDesc), len(file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_goTypes,
		DependencyIndexes: file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_depIdxs,
		MessageInfos:      file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_msgTypes,
	}.Build()
	File_pkg_api_keyvalue_v1alpha1_keyvalue_proto = out.File
	file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_goTypes = nil
	file_pkg_api_keyvalue_v1alpha1_keyvalue_proto_depIdxs = nil
}
