// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/bootstrap/v1alpha1/bootstrap.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterTokenServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterTokenServiceHandler(mux *mux.Router, svc TokenServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/bootstrap.v1alpha1.TokenService/CreateToken", connect.NewUnaryHandler(
		"/bootstrap.v1alpha1.TokenService/CreateToken",
		svc.CreateToken,
		opts...,
	))
	mux.Handle("/bootstrap.v1alpha1.TokenService/ListTokens", connect.NewUnaryHandler(
		"/bootstrap.v1alpha1.TokenService/ListTokens",
		svc.ListTokens,
		opts...,
	))
	mux.Handle("/bootstrap.v1alpha1.TokenService/DeleteToken", connect.NewUnaryHandler(
		"/bootstrap.v1alpha1.TokenService/DeleteToken",
		svc.DeleteToken,
		opts...,
	))
	mux.Handle("/bootstrap.v1alpha1.TokenService/Signatures", connect.NewUnaryHandler(
		"/bootstrap.v1alpha1.TokenService/Signatures",
		svc.Signatures,
		opts...,
	))
}

// RegisterBootstrapServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterBootstrapServiceHandler(mux *mux.Router, svc BootstrapServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/bootstrap.v1alpha1.BootstrapService/Bootstrap", connect.NewUnaryHandler(
		"/bootstrap.v1alpha1.BootstrapService/Bootstrap",
		svc.Bootstrap,
		opts...,
	))
}
