// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pkg/api/bootstrap/v1alpha1/bootstrap.proto

package v1alpha1

import (
	v1alpha1 "github.com/otelfleet/otelfleet/pkg/api/config/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenID       string                 `protobuf:"bytes,1,opt,name=tokenID,proto3" json:"tokenID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetTokenID() string {
	if x != nil {
		return x.TokenID
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *v1alpha1.Config       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfig() *v1alpha1.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type BootstrapAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClientPubKey  []byte                 `protobuf:"bytes,3,opt,name=clientPubKey,proto3" json:"clientPubKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAuthRequest) Reset() {
	*x = BootstrapAuthRequest{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAuthRequest) ProtoMessage() {}

func (x *BootstrapAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAuthRequest.ProtoReflect.Descriptor instead.
func (*BootstrapAuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapAuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BootstrapAuthRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BootstrapAuthRequest) GetClientPubKey() []byte {
	if x != nil {
		return x.ClientPubKey
	}
	return nil
}

type BootstrapAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerPubKey  []byte                 `protobuf:"bytes,1,opt,name=serverPubKey,proto3" json:"serverPubKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAuthResponse) Reset() {
	*x = BootstrapAuthResponse{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAuthResponse) ProtoMessage() {}

func (x *BootstrapAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAuthResponse.ProtoReflect.Descriptor instead.
func (*BootstrapAuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapAuthResponse) GetServerPubKey() []byte {
	if x != nil {
		return x.ServerPubKey
	}
	return nil
}

type BootstrapToken struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ID     string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Secret string                 `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"`
	TTL    *durationpb.Duration   `protobuf:"bytes,3,opt,name=TTL,proto3" json:"TTL,omitempty"`
	Expiry *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Expiry,proto3,oneof" json:"Expiry,omitempty"`
	// TODO: eventually this will be insufficient, should refactor to a message ConfigReference in config.proto
	ConfigReference *string           `protobuf:"bytes,5,opt,name=configReference,proto3,oneof" json:"configReference,omitempty"`
	Labels          map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BootstrapToken) Reset() {
	*x = BootstrapToken{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapToken) ProtoMessage() {}

func (x *BootstrapToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapToken.ProtoReflect.Descriptor instead.
func (*BootstrapToken) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{4}
}

func (x *BootstrapToken) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *BootstrapToken) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *BootstrapToken) GetTTL() *durationpb.Duration {
	if x != nil {
		return x.TTL
	}
	return nil
}

func (x *BootstrapToken) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *BootstrapToken) GetConfigReference() string {
	if x != nil && x.ConfigReference != nil {
		return *x.ConfigReference
	}
	return ""
}

func (x *BootstrapToken) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListTokenReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*BootstrapToken      `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokenReponse) Reset() {
	*x = ListTokenReponse{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokenReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokenReponse) ProtoMessage() {}

func (x *ListTokenReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokenReponse.ProtoReflect.Descriptor instead.
func (*ListTokenReponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{5}
}

func (x *ListTokenReponse) GetTokens() []*BootstrapToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CreateTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TTL             *durationpb.Duration   `protobuf:"bytes,1,opt,name=TTL,proto3" json:"TTL,omitempty"`
	ConfigReference *string                `protobuf:"bytes,2,opt,name=configReference,proto3,oneof" json:"configReference,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTokenRequest) GetTTL() *durationpb.Duration {
	if x != nil {
		return x.TTL
	}
	return nil
}

func (x *CreateTokenRequest) GetConfigReference() string {
	if x != nil && x.ConfigReference != nil {
		return *x.ConfigReference
	}
	return ""
}

func (x *CreateTokenRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DeleteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenRequest) Reset() {
	*x = DeleteTokenRequest{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenRequest) ProtoMessage() {}

func (x *DeleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTokenRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type SignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    map[string][]byte      `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureResponse) Reset() {
	*x = SignatureResponse{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureResponse) ProtoMessage() {}

func (x *SignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureResponse.ProtoReflect.Descriptor instead.
func (*SignatureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{8}
}

func (x *SignatureResponse) GetSignatures() map[string][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClientPubKey  []byte                 `protobuf:"bytes,3,opt,name=clientPubKey,proto3" json:"clientPubKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{9}
}

func (x *BootstrapRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *BootstrapRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BootstrapRequest) GetClientPubKey() []byte {
	if x != nil {
		return x.ClientPubKey
	}
	return nil
}

var File_pkg_api_bootstrap_v1alpha1_bootstrap_proto protoreflect.FileDescriptor

const file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"*pkg/api/bootstrap/v1alpha1/bootstrap.proto\x12\x12bootstrap.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$pkg/api/config/v1alpha1/config.proto\",\n" +
	"\x10GetConfigRequest\x12\x18\n" +
	"\atokenID\x18\x01 \x01(\tR\atokenID\"D\n" +
	"\x11GetConfigResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.config.v1alpha1.ConfigR\x06config\"j\n" +
	"\x14BootstrapAuthRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fclientPubKey\x18\x03 \x01(\fR\fclientPubKey\";\n" +
	"\x15BootstrapAuthResponse\x12\"\n" +
	"\fserverPubKey\x18\x01 \x01(\fR\fserverPubKey\"\xef\x02\n" +
	"\x0eBootstrapToken\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Secret\x18\x02 \x01(\tR\x06Secret\x12+\n" +
	"\x03TTL\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03TTL\x127\n" +
	"\x06Expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x06Expiry\x88\x01\x01\x12-\n" +
	"\x0fconfigReference\x18\x05 \x01(\tH\x01R\x0fconfigReference\x88\x01\x01\x12F\n" +
	"\x06labels\x18\x06 \x03(\v2..bootstrap.v1alpha1.BootstrapToken.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_ExpiryB\x12\n" +
	"\x10_configReference\"N\n" +
	"\x10ListTokenReponse\x12:\n" +
	"\x06tokens\x18\x01 \x03(\v2\".bootstrap.v1alpha1.BootstrapTokenR\x06tokens\"\x8b\x02\n" +
	"\x12CreateTokenRequest\x12+\n" +
	"\x03TTL\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03TTL\x12-\n" +
	"\x0fconfigReference\x18\x02 \x01(\tH\x00R\x0fconfigReference\x88\x01\x01\x12J\n" +
	"\x06labels\x18\x03 \x03(\v22.bootstrap.v1alpha1.CreateTokenRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_configReference\"$\n" +
	"\x12DeleteTokenRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xa9\x01\n" +
	"\x11SignatureResponse\x12U\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v25.bootstrap.v1alpha1.SignatureResponse.SignaturesEntryR\n" +
	"signatures\x1a=\n" +
	"\x0fSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"Z\n" +
	"\x10BootstrapRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fclientPubKey\x18\x03 \x01(\fR\fclientPubKey2\xb4\x03\n" +
	"\fTokenService\x12Y\n" +
	"\vCreateToken\x12&.bootstrap.v1alpha1.CreateTokenRequest\x1a\".bootstrap.v1alpha1.BootstrapToken\x12J\n" +
	"\n" +
	"ListTokens\x12\x16.google.protobuf.Empty\x1a$.bootstrap.v1alpha1.ListTokenReponse\x12M\n" +
	"\vDeleteToken\x12&.bootstrap.v1alpha1.DeleteTokenRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\n" +
	"Signatures\x12\x16.google.protobuf.Empty\x1a%.bootstrap.v1alpha1.SignatureResponse\x12a\n" +
	"\x12GetBootstrapConfig\x12$.bootstrap.v1alpha1.GetConfigRequest\x1a%.bootstrap.v1alpha1.GetConfigResponse2t\n" +
	"\x10BootstrapService\x12`\n" +
	"\tBootstrap\x12(.bootstrap.v1alpha1.BootstrapAuthRequest\x1a).bootstrap.v1alpha1.BootstrapAuthResponseBDZBgithub.com/otelfleet/otelfleet/pkg/api/bootstrap/v1alpha1;v1alpha1b\x06proto3"

var (
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescOnce sync.Once
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescData []byte
)

func file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP() []byte {
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescOnce.Do(func() {
		file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc), len(file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc)))
	})
	return file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescData
}

var file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_goTypes = []any{
	(*GetConfigRequest)(nil),      // 0: bootstrap.v1alpha1.GetConfigRequest
	(*GetConfigResponse)(nil),     // 1: bootstrap.v1alpha1.GetConfigResponse
	(*BootstrapAuthRequest)(nil),  // 2: bootstrap.v1alpha1.BootstrapAuthRequest
	(*BootstrapAuthResponse)(nil), // 3: bootstrap.v1alpha1.BootstrapAuthResponse
	(*BootstrapToken)(nil),        // 4: bootstrap.v1alpha1.BootstrapToken
	(*ListTokenReponse)(nil),      // 5: bootstrap.v1alpha1.ListTokenReponse
	(*CreateTokenRequest)(nil),    // 6: bootstrap.v1alpha1.CreateTokenRequest
	(*DeleteTokenRequest)(nil),    // 7: bootstrap.v1alpha1.DeleteTokenRequest
	(*SignatureResponse)(nil),     // 8: bootstrap.v1alpha1.SignatureResponse
	(*BootstrapRequest)(nil),      // 9: bootstrap.v1alpha1.BootstrapRequest
	nil,                           // 10: bootstrap.v1alpha1.BootstrapToken.LabelsEntry
	nil,                           // 11: bootstrap.v1alpha1.CreateTokenRequest.LabelsEntry
	nil,                           // 12: bootstrap.v1alpha1.SignatureResponse.SignaturesEntry
	(*v1alpha1.Config)(nil),       // 13: config.v1alpha1.Config
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 16: google.protobuf.Empty
}
var file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_depIdxs = []int32{
	13, // 0: bootstrap.v1alpha1.GetConfigResponse.config:type_name -> config.v1alpha1.Config
	14, // 1: bootstrap.v1alpha1.BootstrapToken.TTL:type_name -> google.protobuf.Duration
	15, // 2: bootstrap.v1alpha1.BootstrapToken.Expiry:type_name -> google.protobuf.Timestamp
	10, // 3: bootstrap.v1alpha1.BootstrapToken.labels:type_name -> bootstrap.v1alpha1.BootstrapToken.LabelsEntry
	4,  // 4: bootstrap.v1alpha1.ListTokenReponse.tokens:type_name -> bootstrap.v1alpha1.BootstrapToken
	14, // 5: bootstrap.v1alpha1.CreateTokenRequest.TTL:type_name -> google.protobuf.Duration
	11, // 6: bootstrap.v1alpha1.CreateTokenRequest.labels:type_name -> bootstrap.v1alpha1.CreateTokenRequest.LabelsEntry
	12, // 7: bootstrap.v1alpha1.SignatureResponse.signatures:type_name -> bootstrap.v1alpha1.SignatureResponse.SignaturesEntry
	6,  // 8: bootstrap.v1alpha1.TokenService.CreateToken:input_type -> bootstrap.v1alpha1.CreateTokenRequest
	16, // 9: bootstrap.v1alpha1.TokenService.ListTokens:input_type -> google.protobuf.Empty
	7,  // 10: bootstrap.v1alpha1.TokenService.DeleteToken:input_type -> bootstrap.v1alpha1.DeleteTokenRequest
	16, // 11: bootstrap.v1alpha1.TokenService.Signatures:input_type -> google.protobuf.Empty
	0,  // 12: bootstrap.v1alpha1.TokenService.GetBootstrapConfig:input_type -> bootstrap.v1alpha1.GetConfigRequest
	2,  // 13: bootstrap.v1alpha1.BootstrapService.Bootstrap:input_type -> bootstrap.v1alpha1.BootstrapAuthRequest
	4,  // 14: bootstrap.v1alpha1.TokenService.CreateToken:output_type -> bootstrap.v1alpha1.BootstrapToken
	5,  // 15: bootstrap.v1alpha1.TokenService.ListTokens:output_type -> bootstrap.v1alpha1.ListTokenReponse
	16, // 16: bootstrap.v1alpha1.TokenService.DeleteToken:output_type -> google.protobuf.Empty
	8,  // 17: bootstrap.v1alpha1.TokenService.Signatures:output_type -> bootstrap.v1alpha1.SignatureResponse
	1,  // 18: bootstrap.v1alpha1.TokenService.GetBootstrapConfig:output_type -> bootstrap.v1alpha1.GetConfigResponse
	3,  // 19: bootstrap.v1alpha1.BootstrapService.Bootstrap:output_type -> bootstrap.v1alpha1.BootstrapAuthResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_init() }
func file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_init() {
	if File_pkg_api_bootstrap_v1alpha1_bootstrap_proto != nil {
		return
	}
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc), len(file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_goTypes,
		DependencyIndexes: file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_depIdxs,
		MessageInfos:      file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes,
	}.Build()
	File_pkg_api_bootstrap_v1alpha1_bootstrap_proto = out.File
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_goTypes = nil
	file_pkg_api_bootstrap_v1alpha1_bootstrap_proto_depIdxs = nil
}
