// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: github.com/otelfleet/otelfleet/pkg/api/bootstrap/v1alpha1/bootstrap.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapToken) Reset() {
	*x = BootstrapToken{}
	mi := &file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapToken) ProtoMessage() {}

func (x *BootstrapToken) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapToken.ProtoReflect.Descriptor instead.
func (*BootstrapToken) Descriptor() ([]byte, []int) {
	return file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapToken) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *BootstrapToken) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto protoreflect.FileDescriptor

const file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"Igithub.com/otelfleet/otelfleet/pkg/api/bootstrap/v1alpha1/bootstrap.proto\x12\tbootstrap\"8\n" +
	"\x0eBootstrapToken\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Secret\x18\x02 \x01(\tR\x06SecretB;Z9github.com/otelfleet/otelfleet/pkg/api/bootstrap/v1alpha1b\x06proto3"

var (
	file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescOnce sync.Once
	file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescData []byte
)

func file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescGZIP() []byte {
	file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescOnce.Do(func() {
		file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc), len(file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc)))
	})
	return file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDescData
}

var file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_goTypes = []any{
	(*BootstrapToken)(nil), // 0: bootstrap.BootstrapToken
}
var file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_init() }
func file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_init() {
	if File_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc), len(file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_goTypes,
		DependencyIndexes: file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_depIdxs,
		MessageInfos:      file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_msgTypes,
	}.Build()
	File_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto = out.File
	file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_goTypes = nil
	file_github_com_otelfleet_otelfleet_pkg_api_bootstrap_v1alpha1_bootstrap_proto_depIdxs = nil
}
