// Code generated by protoc-gen-connect-go-mux. DO NOT EDIT.
//
// Source: pkg/api/resources/v1alpha1/resources.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

// RegisterResourceServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterResourceServiceHandler(mux *mux.Router, svc ResourceServiceHandler, opts ...connect.HandlerOption) {
	mux.Handle("/resources.v1alpha1.ResourceService/GetEntity", connect.NewUnaryHandler(
		"/resources.v1alpha1.ResourceService/GetEntity",
		svc.GetEntity,
		opts...,
	))
	mux.Handle("/resources.v1alpha1.ResourceService/PutEntity", connect.NewUnaryHandler(
		"/resources.v1alpha1.ResourceService/PutEntity",
		svc.PutEntity,
		opts...,
	))
	mux.Handle("/resources.v1alpha1.ResourceService/DeleteEntity", connect.NewUnaryHandler(
		"/resources.v1alpha1.ResourceService/DeleteEntity",
		svc.DeleteEntity,
		opts...,
	))
	mux.Handle("/resources.v1alpha1.ResourceService/ListEntity", connect.NewUnaryHandler(
		"/resources.v1alpha1.ResourceService/ListEntity",
		svc.ListEntity,
		opts...,
	))
	mux.Handle("/resources.v1alpha1.ResourceService/WatchEntity", connect.NewServerStreamHandler(
		"/resources.v1alpha1.ResourceService/WatchEntity",
		svc.WatchEntity,
		opts...,
	))
	mux.Handle("/resources.v1alpha1.ResourceService/HistoryEntity", connect.NewUnaryHandler(
		"/resources.v1alpha1.ResourceService/HistoryEntity",
		svc.HistoryEntity,
		opts...,
	))
}

// RegisterDiscoveryServiceHandler register an HTTP handler to a mux.Router from the service
// implementation.
func RegisterDiscoveryServiceHandler(mux *mux.Router, svc DiscoveryServiceHandler, opts ...connect.HandlerOption) {
}
